### ISSUE TITLE
[Health Data Log-New Metrics] Working File stat count increases on closing the files from working set 

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#11406] opened 2015-07-16 04:48 UTC
Steps:
1) Launch Brackets
2) Open some php files
3) open health data report
4) Close some files in the working set which is already opened and open health data report

Result : 
Working File stat count in "fileStats" increments on closing the files in working set

**Comment by abose** [comment] 2015-07-16 07:20
Checked this issue out, what is happening is, when you close a file, brackets will open the next file in working set , which is rightfully logged as a file open. If there are no files open in the working set, the counter is not incremented. This behavior is inline with our measurement goals, so closing as intended.

**Closed by abose** 2015-07-16 07:20 UTC
Labels: IQE, medium priority
