### ISSUE TITLE
Brackets asking to connect to internet when is already connected

### ISSUE THREAD

**Issue by tofanelli** [adobe/brackets#11147] opened 2015-05-21 12:05 UTC
hey guys....

i've been experiencing a weird issue.... my laptop is already connected to the internet, but, when I click to sign-in to upload a psd to use the Extracts, it shows me a warning message saying I need to connect to the internet... what I supposed to do to use it??

Cheers =)

**Comment by prafulVaishnav** [comment] 2015-05-21 12:38
@tofanelli Can you please open the developer tool ("Debug > Show Developer Tools") and see if there is any error in the console?

**Comment by tofanelli** [comment] 2015-05-21 15:30
Hey @prafulVaishnav .... is it this?

![untitled-1](https://cloud.githubusercontent.com/assets/5512922/7752256/d6a8aaae-ffb4-11e4-9422-2fa84d8d715a.png)

**Comment by petetnt** [comment] 2015-05-22 05:34
Most likely a duplicate of #9793, check your firewall settings.

**Comment by tofanelli** [comment] 2015-05-22 15:32
hey @petetnt .... there is no firewall in my machine but the windows one.... im at my home, so there is no proxy, no hardware firewall... nothing but my windows and internet connection.... that's it.... i don't think this could be an error caused by firewall.. 

Cheers =)

**Comment by nethip** [comment] 2015-05-24 19:19
@tofanelli From the log it appears you have some Brackets extensions installed on your system. Could you reload Brackets from *Debug->Reload Without Extensions* and see if you are still facing this issue? If that does not work, I would also suggest renaming the Brackets folder in `%appdata%\Roaming` to rule out any possibility with bad preference.

**Comment by tofanelli** [comment] 2015-05-26 03:51
hey @nethip .... it was, indeed, some plugin causing this bad behavior.... as long the issue was being caused by the Brackets Extract, I couldn't test it reloading the Brackets without the extensions... so, i removed all of them and reload it.... and, voila =)... its working flawlessly now... but, before I removed all of them, I installed another to save all of them ((Extensions Bulk Installer)), so, this extension saved this list.... if you are interested to check a little bit deeper if it was some extension, here follows the list

    "brackets-beautify": true,
    "deddy.additional-right-click-menu": true,
    "brackets-compare": true,
    "vcfvct.brackets-file-format": true,
    "brackets-css-shapes-editor": true,
    "brackets-display-shortcuts": true,
    "torin.duplicate": true,
    "milosh86.extensions-bulk-installer": false,
    "adobe.brackets.extract": true,
    "quick-dark": true,
    "brackets-robotframework": true,
    "ws-sanitizer": true

I only have these ones installed.... 


Well... thanks very much for help =)


Cheers =)

**Closed** 2015-05-26 04:07 UTC

**Comment by nethip** [comment] 2015-05-26 06:17
@tofanelli Glad you were able to resolve this issue :smile:
