### ISSUE TITLE
Block Comments don't take indentation into account

### ISSUE THREAD

**Issue by recursionbane** [adobe/brackets#13169] opened 2017-03-11 01:34 UTC
### Prerequisites

* [Y] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [Y] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [Y] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

The dynamic indentation of Brackets is great, especially for cleaning up HTML.
When one or more indented lines are selected, and Edit->"Toggle Line Comment" is clicked, the indentation is also commented.

### Steps to Reproduce

1. Select one or more lines of indented code
2. Click Edit -> Toggle Line Comment

**Input:**
```HTML
                    <md-content class="md-padding ">
```

**Expected behavior:** 
```HTML
                    <!-- <md-content class="md-padding "> -->
```

**Actual behavior:**
```HTML
<!--                    <md-content class="md-padding ">-->
```

### Versions

Please include the OS and what version of the OS you're running: Windows 7 SP1
Please include the version of Brackets.: Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4); build timestamp: Wed Nov 02 2016 12:07:29 GMT+0000

**Comment by blairdow** [comment] 2017-03-24 17:01
I would love a fix for this as well!

**Comment by redmunds** [comment] 2017-03-24 21:54
This is a duplicate of #8012 which has been fixed. It looks like the fix is to add the `indentLineComment` preference and set it to `true`.

**Comment by ficristo** [comment] 2017-03-26 12:18
Reopening: `indentLineComment` does work only for languages which defines single line comments.
Html language defines only block comments.

**Closed** 2017-04-24 20:21 UTC
