### ISSUE TITLE
Errors are not highlighted in the default dark theme

### ISSUE THREAD

**Issue by ficristo** [adobe/brackets#13057] opened 2017-01-22 12:09 UTC
### Prerequisites

* [x] Can you reproduce the problem with `Debug -> Reload Without Extensions`?
* [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

For more information on how to write a good bug report read [here](https://github.com/adobe/brackets/wiki/How-to-Report-an-Issue)
For more information on how to contribute read [here](https://github.com/adobe/brackets/blob/master/CONTRIBUTING.md)

### Description

In the default dark theme, errors are not highlighted.
![theme-error](https://cloud.githubusercontent.com/assets/10583268/22182309/a06a96e8-e0a2-11e6-8898-285364be82c6.png)

CodeMirror add the class `cm-error` correctly and in `src/extensions/default/DarkTheme/main.less` there is a class for `cm-error` which should highlight the tag in red.

### Steps to Reproduce

1. Switch to the default dark theme
2. Paste this snippet
```html
<html>
    <div>
</html>
```

### Versions
Windows 10
master

**Comment by ficristo** [comment] 2017-01-22 12:10
Since I believe (I don't have investigated) it is a problem of overriding correctly the styles, marking as starter issue.
/cc @swmitra @MiguelCastillo

**Comment by swmitra** [comment] 2017-01-22 13:26
@ficristo you are absolutely right.  The problem is the position and grouping of cm-error.  Ideally cm-error should be defined after defining all the CM token selectors in the theme less file. We will fix this in 1.9.

**Comment by petetnt** [comment] 2017-01-23 11:19
Weird, I fixed this in the light theme a long while back: https://github.com/adobe/brackets/pull/11894 🤔

**Comment by swmitra** [comment] 2017-01-24 03:11
@petetnt yes,  that's exactly the fix what we need in dark theme as well.

**Comment by petetnt** [comment] 2017-01-29 21:58
Fixed in #13068

**Closed by petetnt** 2017-01-29 21:58 UTC
Labels: Starter bug
