### ISSUE TITLE
The "Next Document" and "Previous Document" commands have inconsistent behavior 

### ISSUE THREAD

**Issue by bemjb** [adobe/brackets#10418] opened 2015-01-19 23:58 UTC
Normally, the "Next Document" command (Cmd+}) navigates downwards in the Working Flies list, and the "Previous Document" command (Cmd+{) navigates upwards in the list.

However, on a few occasions now, I have had the order that these commands iterate through the working files not match the order in which the files are displayed in the "Working Files" list. It does seem like it goes back and forth in the same order, it's not an obvious order, as it doesn't match the order that the list is displayed in. Reordering the "Working Files" list by dragging and dropping doesn't seem to fix it, nor does quitting and restarting Brackets. It does seems to get fixed if all of the files are closed (clearing the "Working Files" list). 

I have not yet figured out what series of steps causes Brackets to get into this state. If I figure that out, I will update this issue.

**Comment by JeffryBooher** [comment] 2015-01-20 03:51
@bemjb the next/prev document commands work in MRU order.  On startup, however, or when opening a new project the MRU order is the order they are listed in the working set(s).

**Comment by redmunds** [comment] 2015-01-20 16:18
@JeffryBooher It's supposed to be MRU order, and that's how it works on Windows, but it seems to work differently on Mac.

**Comment by JeffryBooher** [comment] 2015-01-20 17:24
@redmunds i don't know how it could be different the it's the same code for both platforms.

**Comment by bemjb** [comment] 2015-01-20 17:56
@JeffryBooher Why is it MRU order rather than the order displayed in the UI? That seems unnecessarily different from every other app I've used: the "Cmd+{" and "Cmd+}" shortcuts always iterate through tabs in the order they are displayed.

**Comment by JeffryBooher** [comment] 2015-01-20 19:26
The convension is that `Ctrl/Cmd+Tab` goes to the previous document that was active in most Devloper IDEs -- Sublime Text, Visual Studio, Web Storm, etc... 

But, you're right, in non-developer interfaces such as Chrome, Safari, IE, etc... Ctrl/Cmd+Tab goes to the next tab in the display order.  

Brackets makes it easy for users of Sublime Text, Web Storm, etc... to switch between Brackets and their other editors.

**Comment by bemjb** [comment] 2015-01-20 21:09
On the Mac, it's not bound to Cmd+Tab (which wouldn't make sense, as that's "switch applications"), or Cmd+` (which would be closer to making sense, but that's "switch windows in the current application"). It's bound to cmd+{ (for cycle forward) and cmd+} (for cycle backwards), which is usually bound to switch tabs in the currently active window. I am quite familiar with developer interfaces on the Mac, and cycling through tabs in Xcode, Sublime, MacVim, BBEdit, etc all use the shortcuts in the same way as Chrome, Safari, etc: Cmd+` cycles through windows in the current application in MRU order (and Cmd+~ cycles backwards), but Cmd+{ and Cmd+} cycle though tabs in the visual order. So to me, that's what they should do in Brackets.

**Comment by JeffryBooher** [comment] 2015-01-20 21:46
You can map the keys by opening the user key map and changing the designations for those commands.  `Debug > Open User Key Map`

**Comment by bemjb** [comment] 2015-01-20 22:39
Unless I could also make the visual representation be a window per document, mapping "Next Document" and "Previous Document" to Cmd+\` and Cmd+~ wouldn't help me, because everywhere else in the OS, those commands navigate between windows, not between items inside a single window. It sounds like you don't consider this lack of consistency with other applications in the OS a bug, so I guess we'll have to agree to disagree.

**Comment by redmunds** [comment] 2015-01-22 03:00
@bemjb This is *supposed* to go in MRU order. It works correctly on Windows using `Ctrl-Tab` and `Ctrl-Shift-Tab` and also on Mac using `Control-Tab` (*not* `Cmd-Tab`) and `Control-Shift-Tab`.

But there's a bug when using `Cmd-Shift-]` and `Cmd-Shift-[` shortcuts because the [keyup handler that updates the MRU list](https://github.com/adobe/brackets/blob/master/src/document/DocumentCommandHandlers.js#L1439) only looks for "control" key, so it appears like it's supposed to go in working set order in certain cases.

So there's no feature that does what you want, but you did find a bug, so we'll leave this open to fix that.

It sounds like the **File Navigation Shortcuts** extension by @peterflynn does what you want. Have you tried that?

cc @JeffryBooher

**Comment by mdziedzic** [comment] 2015-02-21 01:57
Just throwing my 2¢ in... but I really wish there was a way to navigate the Working Files in the order that they are displayed in the UI (as opposed, or in addition to, MRU order). That's the way it works for me in Sublime Text 3 on the Mac, and I don't understand why this isn't an option in Brackets.

**Comment by lucasdewet** [comment] 2015-03-03 08:31
I second the suggestion to allow the user to choose the ctrl+tab behaviour. It just slows you down when you just want to go to the file above the one you are currently on, but alas, no, it jumps 5 files in the opposite direction and now you have to waste time reaching for your mouse to just click on the file you want. I am a developer and I use my keyboard extensively. It wastes time to use the mouse when the UI should be there to make my life easier. Why have a sorting order in Working Files in the first place if it is going to get ignored? I vote for ctrl+tab going in the order that Working Files is sorted in at the moment.

**Comment by peterflynn** [comment] 2015-03-03 08:51
@mdziedzic Did Sublime 3 change behavior from Sublime 2?  On my Mac, in Sublime 2 pressing Ctrl-Tab always uses MRU order...

At any rate, I'm going to close this as a duplicate of #6273.  It seems highly consistent across text editors that Ctrl-Tab, _by default_ at least, navigates in MRU order.  To navigate in visual list order, you can currently use my [File Navigation Shortcuts](https://github.com/peterflynn/brackets-editor-nav) extension (and then I think you can map those shortcuts as a replacement for Ctrl-Tab if desired).  The fix for #6273 will make those shortcuts built-in, without requiring an extension -- but they'll still be a different shortcut by default.

If there's evidence that other editors provide a simpler preference for switching the behavior of Ctrl-Tab (simpler than remapping shortcut keys), we certainly could do the same in Brackets.  Please post comments in support of that over in #6273.

**Closed by peterflynn** 2015-03-03 08:51 UTC

**Comment by mdziedzic** [comment] 2015-03-03 16:50
@peterflynn I do not believe that the behavior changed for me between Sublime 2 & 3. That said, I'm not certain, but I don't remember ever feeling frustrated with Sublime 2. Also, I used Cmd-Shift-[ and Cmd-Shift-].

**Comment by peterflynn** [comment] 2015-03-03 19:30
Oh sorry, thought you were talking about Ctrl-Tab.  Cmd-Shift-[/] will be fixed by #6273 to work the way you expect.

**Comment by bemjb** [comment] 2015-03-03 20:02
@mdziedzic FWIW, I did end up trying @peterflynn 's extension, and it does work just fine, though it defaults to Cmd+[/] so I had to remap it to be Cmd+Shift+[/].
