### ISSUE TITLE
Option to indent PHP code based on the HTML around it

### ISSUE THREAD

**Issue by davion100** [adobe/brackets#10038] opened 2014-11-28 10:03 UTC
Hello. I have a problem with the PHP code not indenting properly. What happens is every time I type "<?php" all the code after this line does not indent. I tried removing all the plugins , same thing. Here is an example: 
![mxx2yqi](https://cloud.githubusercontent.com/assets/6960329/5226342/7c2f80b2-76f6-11e4-9e05-695e73122249.png)

**Comment by rifton007** [comment] 2015-08-03 09:17
Hi all,
I have the same problem, the news about it?

**Comment by juliancesar** [comment] 2015-08-26 13:53
I have the same problem! Any news?

**Comment by klarkc** [comment] 2015-08-26 18:12
+1

**Comment by MarcelGerber** [comment] 2015-08-28 17:49
Just submitted the CodeMirror tracking issue https://github.com/codemirror/CodeMirror/issues/3488

**Comment by MarcelGerber** [comment] 2015-09-03 08:02
This will work as described beginning in Release 1.5.
Closing.

**Closed by MarcelGerber** 2015-09-03 08:02 UTC
Labels: codemirror, F Editor, low priority, tracking

**Comment by vidukapoor** [comment] 2015-09-03 17:33
php code writing error.

**Comment by mikael1000** [comment] 2015-12-30 11:28
I have 1.5... and it don't work. This should be fixed!
However you get a little better experience if you do the hack with { and }:
<?php {
}?>

But that's a bad way to have to do this.

**Comment by ficristo** [comment] 2015-12-30 17:46
@mikael1000 Brackets align the code at the same level of `<?php`: so it's indented.
In general I think it should indent one more time but I don't know enough of `php` to say it's the right thing to do.
Since I can reproduce the "issue" on the [demo page](http://codemirror.net/mode/php/) of CodeMirror you should file a bug there.
