### ISSUE TITLE
PHP open/close tag not behaving properly

### ISSUE THREAD

**Issue by baileyherbert** [adobe/brackets#11919] opened 2015-11-15 23:20 UTC
When creating an opening PHP tag and pressing Enter, the editor does not automatically add tabs before the next line as expected.

The result is this cursor placement:

![Example](http://seohub.io/xp.jpg)

After manually adding the tabs and hitting enter, the editor still does not add the tabs.

However, enclosing the PHP code with brackets does seem to fix this issue, but is not feasible, and also when I type the brackets, it re-positions it to the first character of the line:

![Example 2](https://i.gyazo.com/2336aca0642fb1acd41455ce1c85acec.gif)

This is a problem that has existed in Brackets for many many versions and exists in a clean install. I have no extensions.

**Comment by petetnt** [comment] 2015-11-16 06:53
Use the language dropdown menu to select `PHP` mode instead of `HTML` (and optionally set `PHP` as the default for `.html`-files from top of that same menu after selecting the mode).

**Comment by baileyherbert** [comment] 2015-11-17 22:18
The file I had open in my screenshots was a .php file, and the mode was set to PHP. 

However, even if I create a .html file and follow your steps, the issue persists.

**Comment by petetnt** [comment] 2015-11-18 07:00
@baileyherbert Oh, the issue was fixed in https://github.com/codemirror/CodeMirror/commit/9018087c161f32abac9f3ba43e6591f1b9bcab05 (#3488) which didn't land to 1.5. I think. 

Can you try the latest master (https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to see if the issue is fixed?

**Closed** 2015-12-17 21:14 UTC
