### ISSUE TITLE
Problem with vertical/horizontal side left/top side dont exist is hidden or something else

### ISSUE THREAD

**Issue by bardhkrasniqi** [adobe/brackets#11340] opened 2015-07-02 22:30 UTC
Problem with vertical/horizontal side left/top side dont exist is hidden 
Hi i have trouble with bracket on vertical/horizontal split view left/top side dont show is hidden or something else just show a white space screen only right/bottom side work even if i go at normal split its just white screen so u cant do nothing.
I tryed to fix to reinstall , reloading bracket but nothing change its again same problem
![bracket](https://cloud.githubusercontent.com/assets/13149255/8489324/a9e3f424-211a-11e5-8d4e-bbbad6a8f57d.png)
![bracket1](https://cloud.githubusercontent.com/assets/13149255/8489322/a9e144f4-211a-11e5-8c4a-c5c2a5bef2f4.png)
![bracket2](https://cloud.githubusercontent.com/assets/13149255/8489323/a9e3209e-211a-11e5-89fd-6c3fe42be418.png)

**Comment by sprintr** [comment] 2015-07-02 22:58
You should reload via `Debug -> Reload Without Extensions` and see if it still happens. Maybe you could share the logged messages as well by `Debug -> Show Developer Tools` and Selecting `Console` tab.

**Comment by ficristo** [comment] 2016-08-21 07:01
@bardhkrasniqi could you try the latest release to see if you can still reproduce?

**Comment by ficristo** [comment] 2016-10-30 08:04
I close this since we didn't hear back from you.

**Closed by ficristo** 2016-10-30 08:04 UTC
Labels: Waiting for user
