### ISSUE TITLE
LOC:DEU/FRA:Win only: Missing shortcut key for Toggle Panels.

### ISSUE THREAD

**Issue by chunyan1047** [adobe/brackets#12131] opened 2016-01-22 08:40 UTC
1. Launch Brackets.
2. Expand View panel.

Result:
Missing shortcut key for Toggle Panels.
And shortcut key Ctrl+Shirt+` does not work.

Expect:
Adding correct shortcut key for Toggle Panels.
And shortcut key Ctrl+Shirt+` should be worked correctly.

![deu_shortcut key](https://cloud.githubusercontent.com/assets/16832986/12505926/d21dbece-c125-11e5-8e43-faf9caa60473.png)

**Comment by petetnt** [comment] 2016-01-22 08:50
Related to this: https://github.com/adobe/brackets/issues/11004

**Comment by chunyan1047** [comment] 2016-01-22 09:57
No shortcut key for German.
In French, the shortcut key is displayed in view panel at first time, But when use local input method, then restart brackets, the shortcut key for Toggle Panels is missing.

**Comment by chunyan1047** [comment] 2016-01-22 10:16
This issue only reproduce on Local input method. When we change to ENU input method, then relaunch Brackets the shortcut key will be displayed correctly in view drop down list.

**Comment by nethip** [comment] 2016-01-29 11:00
@abose Could you please take a look at this and update the thread?

**Comment by abose** [comment] 2016-01-29 11:07
It looks like the shortcut is already in use.
Please go to `debug> show developer tools> console` and copy the error message here.

**Comment by petetnt** [comment] 2016-01-29 11:13
I debugged the issue back in https://github.com/adobe/brackets/issues/11004#issuecomment-96786444, the issue is that it's practically impossible to do some of the shortcuts on non-US keyboards.

For example on a finnish keyboard you need to press shift to create a backtick, making a `Ctrl + Shift + backtick` combination impossible. 

See the Finnish keyboard layout (backtick on the left side of backspace)

![image](https://cloud.githubusercontent.com/assets/7641760/12674152/0460f9a0-c68a-11e5-857c-8da6380d71f1.png)

US keybord (backtick below above tab with the tilde key)

![image](https://cloud.githubusercontent.com/assets/7641760/12674174/2111336c-c68a-11e5-8d30-50b98a913484.png)

**Comment by nethip** [comment] 2016-01-29 11:18
Thanks @petetnt for looking into this! appreciate it!

We are having the same issue with Fr keyboards. Could you then reassign the shortcuts for these two locales alone?

**Comment by petetnt** [comment] 2016-01-29 11:27
I think it would make sense to allow overriding shortcuts by locale either in [keyboard.json](https://github.com/adobe/brackets/blob/master/src/base-config/keyboard.json) or by creating new files such as `keyboard-fi-fi.json` or `keyboard-fr-fr.json` that contain the overrides. The second option might be more flexible in the long run. 

For the Extensions `KeyBindingManager#addBinding` could be extended too:

```
KeyBindingManager.addBinding(CMD_TOGGLE_PANELS, [ {key: togglePanelsKey}, {key: togglePanelsKeyMac, platform: "mac", {key: togglePanelsKeyFr, locale: "fr-fr"} ]);
```

Only thing that I don't know: is there an existing way of polling what kind of keyboard the user is using?

**Comment by YanChen002** [comment] 2016-03-07 11:39
Verified this issue on build 1.7.0-16739,it still reproduce.
![fr](https://cloud.githubusercontent.com/assets/17636671/13568453/405d4cee-e49c-11e5-836e-63f9877d743b.png)

**Comment by ZuoBaogang** [comment] 2016-03-11 10:37
Check this issue on 1.6 refresh build 1.6.0-16692, FRA and DEU has been fixed.
![deu](https://cloud.githubusercontent.com/assets/17721679/13699863/2fee3656-e7b8-11e5-82fd-96c26e48ab3c.png)
![fra](https://cloud.githubusercontent.com/assets/17721679/13699867/34f3a172-e7b8-11e5-9063-c31840fb2129.png)

**Closed** 2018-02-08 05:33 UTC
Labels: French, IQE
