### ISSUE TITLE
Code folding markers broken after deleting selection across collapsed section

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10857] opened 2015-04-09 00:57 UTC
1. Start with this JS code:
```
define(function () {
    var foo;
    
    function one() {
        foo = 1;
    }
    
    function two() {
        foo = 2;
    }
    
    function three() {
        foo = 3;
    }
    
});
```

1. Collapse "two"
2. Select from the start of the `function` keyword in "two", to the start of the `function` keyword in "three"
3. Press delete
    * Result: folding triangle for "one" now shows it's collapsed, even though function "one" is _not_ collapsed
4. Click the folding triangle for "one" repeatedly
    * Result: nothing happens; triangle is nonresponsive
5. Undo
    * Result: triangle for "one" still show's it's collapsed. Triangle for "two" shows it's _not_ collapsed even though it _is_
6. Click triangle for "two" repeatedly
    * Result nothing happens on first click, but on 2nd click it starts working correctly
7. Click triangle for "one" repeatedly
    * Result: it still does nothing

**Comment by peterflynn** [comment] 2015-04-09 01:00
In other cases, this can cause phantom code-folding triangles to appear in places where no triangle was present before.  E.g.

1. Open CodeFolding/main.js
2. Collapse the block that starts with `var foldGutter`
3. Select from just before the "f" in `foldGutter` to just after the "n" in `function restoreL...`
4. Delete
    * Now there's a triangle on line 57 (`COLLAPSE_CUSTOM_REGIONS = ...`)

**Comment by nethip** [comment] 2015-04-09 02:52
@peterflynn Thanks for testing this extensively.

**Comment by abose** [comment] 2015-04-09 12:24
The problems are not present in https://codemirror.net/demo/folding.html

**Comment by thehogfather** [comment] 2015-04-13 17:02
The culprit function here is in foldgutter.js `updateFoldsCache`. Changes to the document and their corresponding effects on the line folds are not been correctly handled. The issue isn't present in the codemirror demo because it doesn't attempt to cache the lineFolds. 

A related issue is to hit `Ctrl-Z` after either one of the scenarios described above. The result is that the collapsed region is restored but the indicator on the gutter is wrong.

**Comment by abose** [comment] 2015-04-13 17:13
@thehogfather #10888 proposes a fix for the issue. can you check it out.

Also the issue of Ctrl-Z after either one of the scenarios described above. The result is that the collapsed region is restored but the indicator on the gutter is wrong.-- i still have not fixed that, any clue on what could be going wrong in that case?

**Comment by thehogfather** [comment] 2015-04-13 17:18
@abose checking #10888 at the moment.

The issue with the Ctrl-Z issue is that the lineFolds cache would be stale (after deletion of a folded code fragment). I would suggest checking the textMarker for the given line to see if the line is folded.

**Comment by abose** [comment] 2015-04-14 13:57
Thanks for the quick response @thehogfather. I have updated the PR with fixes for the undo-redo and fold state persistence case using textMarkers as you suggested. 
Please take a look at the change.

**Comment by thehogfather** [comment] 2015-04-14 22:46
@abose looks good from my point of view. I've had a play around at work all day and the undo works as expected.

**Comment by abose** [comment] 2015-04-15 05:37
Thaks for checking this out.
Verified the fix. closing.

**Closed by abose** 2015-04-15 05:37 UTC
Labels: F Code Folding, fix in progress, high priority
