### ISSUE TITLE
Tag closing added on selfclosing HTML tags

### ISSUE THREAD

**Issue by olivtv** [adobe/brackets#13333] opened 2017-04-24 10:30 UTC
I think the bug came with the 1.9 version.

When I write a selfclosing tag in HTML (br, img, hr, etc.), Brackets write the closing (`</br>`).

So I get `<br></br>` instead of `<br>`.

Thanks,

_:oliv'_

_Mac OS 10.11.16 – Barcket Release 1.9 build 1.9.0-17312 (release 189f6d39a)_

**Comment by ficristo** [comment] 2017-04-26 18:16
Do you have modified your `closeTags` preference?
Something like this should work:
```json
"closeTags": {
  "whenClosing": false,
  "whenOpening": true
}
```

**Comment by olivtv** [comment] 2017-04-27 06:46
Thanks for your answer :)

The problem is not that I don't want them (the HTML self-closing tags –`<img>`,`<br>`, `<link>`, etc.) to be closed, it's they don't have to be.

Maybe my explanation wasn't that good neither was my English ;)

But your solution show me a way to correct this.
I've tested with the `<img>` tag  by editing the preferences like this 👍 

``` 
"closeTags": {
        "dontCloseTags": ["img"],
        "indentTags": [],
        "whenClosing": true,
        "whenOpening": true
}
``` 
But we haven't to do this in previous versions (1.8 or below) and it's a standard feature of HTML that these tags shouldn't be closed with a close tag `</foo>`.

I'm a vocational teacher in a applied art school, and all my students have this bug since the last update.

 So I think it's a **bug in this version**. If it's not the case, all users will have to change their preferences :/ .

**Comment by ficristo** [comment] 2017-04-27 07:39
So you don't have closeTags defined neither in your local preferences nor in the global ones?
I should have been clearer: my point is you should not define `dontCloseTags` at all. Try to remove it from the "closeTags" object.
I switched my version of Brackets to the git release `release-1.9` and I cannot reproduce (I don't have closeTags defined).

**Comment by olivtv** [comment] 2017-04-27 07:54
Thanks, it works fine without it :D

I've made a full clear install to see when this preference appears. 

This preference is added after the first use of the "**Preferences setup UI**" extension. It had a few preferences by default including the one who causes this problem. Wasn't the case in previous versions. 

Thanks a lot for your help. :)

**Comment by ficristo** [comment] 2017-04-27 18:04
Good job finding the culprit!
Closing as answered.

**Closed by ficristo** 2017-04-27 18:04 UTC
Labels: Waiting for user
