### ISSUE TITLE
Window title on OS X

### ISSUE THREAD

**Issue by olivergraphix** [adobe/brackets#12873] opened 2016-11-04 14:58 UTC
I'm running Brackets 1.7.0 on Mac OS 10.7.5 and 10.11.6.
I'm tracking my time in Brackets using RescueTime. 

RescueTime is tracking the time in apps by logging the name of the app, version and window title. Window Title displays the file name of the document with the focus.

My problem is that for Brackets I don't see the info for Window Title, so RescueTime logs just the name of the app and not the file's name I'm working on.
It looks like what I need is requested here, too https://github.com/adobe/brackets/issues/12868

**Comment by ficristo** [comment] 2016-11-06 11:30
For now I close this as a dupe of #12868

**Closed by ficristo** 2016-11-06 11:30 UTC
