### ISSUE TITLE
Move Find bar to bottom of window / Question about external changes message

### ISSUE THREAD

**Issue by laramjo** [adobe/brackets#10828] opened 2015-04-04 17:02 UTC
Hi I have two questions:

1. could be passed the searchbox above to below, as in sublime text?

<IMG SRC="https://farm9.staticflickr.com/8708/16411832303_546bd5a3c8_o.png">

How do I avoid that whenever I save the file I exit this window?

<IMG SRC="https://farm9.staticflickr.com/8712/17030566262_cb3592ab77_o.png">

He did not speak English  google translation

**Comment by peterflynn** [comment] 2015-04-07 06:47
1) I think what you're asking is: could the Find bar be located at the bottom of the window, instead of the top of the window?  We don't get that request often, so we may not make this an option in Brackets core -- but it's something an extension could easily do.  Adding the 'extension idea' tag so extension authors will see this.

2) You _should_ only see this message if you do the following steps:
1. Modify a file in Brackets but do _not_ save it
2. Modify the same file in a different application _and_ save it
3. Then go back to Brackets and try to save the file

Did you do something like that?  Do you have a background process running that might be automatically modifying your files?

**Comment by laramjo** [comment] 2015-04-07 15:13
all right. Thank you very much. Hopefully someone will develop the extension

**Comment by gserrg** [comment] 2015-04-08 18:16
1) +1 and please do not close the search when the search field has lost focus.

**Comment by peterflynn** [comment] 2015-04-08 22:43
@gserrg Please upvote [Find/Replace: Leave search bar open & highlights visible when editor focused, until first edit](https://trello.com/c/TD4qOgxG/1084-find-replace-leave-search-bar-open-highlights-visible-when-editor-focused-until-first-edit) on our feature backlog.

**Comment by prksingh** [comment] 2015-04-13 11:36
@laramjo Closing it since that's out standard process for extension suggestions that we're not likely to turn into core features. Please let us know, if you see some unexpected behavior from the 'external changes' reload dialog and I will reopen this. Thanks.

**Closed by prksingh** 2015-04-13 11:36 UTC
Labels: Extension Idea
