### ISSUE TITLE
Native menus on Linux

### ISSUE THREAD

**Issue by iampepe** [adobe/brackets#12791] opened 2016-09-18 09:14 UTC
Why there is still no native menus on linux?

**Comment by zaggino** [comment] 2016-09-18 10:13
Duplicate of https://github.com/adobe/brackets/issues/7236
Brackets-Electron has native menus on Linux: https://github.com/zaggino/brackets-electron/releases

**Closed by zaggino** 2016-09-18 10:13 UTC

**Comment by iampepe** [comment] 2016-09-18 10:38
I will try it out, thank you.
