### ISSUE TITLE
trouble with Cyrillic in Extract for Brackets (Preview)

### ISSUE THREAD

**Issue by h0m1c1de** [adobe/brackets#10824] opened 2015-04-03 20:40 UTC
![brackets-bug](https://cloud.githubusercontent.com/assets/9438211/6988470/716882f6-da5a-11e4-8503-6464ca43f53d.png)

not help:
reinstall brackets,
 instal version 1.1 ,
 new adobe acc, 
new windows.

Please help

**Comment by abose** [comment] 2015-04-08 10:37
Could you share a sample psd with the Cyrillic font problem?

**Comment by h0m1c1de** [comment] 2015-04-08 11:11
Problem is in all psd files with Cyrillic text
http://rghost.ru/6bLpqgXSc for exemple

**Comment by abose** [comment] 2015-04-09 13:34
@h0m1c1de thanks for the upload, I was able to reproduce the issue in brackets. Most probably a font issue, the issue is not present in cc web.

**Comment by MarcelGerber** [comment] 2015-04-09 14:01
#8985 will probably fix that issue.

**Comment by peterflynn** [comment] 2015-04-09 18:29
@MarcelGerber I think this one is different -- it's not just an ugly font, it's glyphs not getting encoded right and showing up as "X"es, which is probably a server-side Extract bug.

**Comment by abose** [comment] 2016-06-30 12:05
Deprecated feature [See details](http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/) . Closing.

**Closed by abose** 2016-06-30 12:05 UTC
Labels: F Extract
