### ISSUE TITLE
need to click twice to close Brackets

### ISSUE THREAD

**Issue by yx91490** [adobe/brackets#11137] opened 2015-05-18 14:53 UTC
OS : Debian 8-amd64,
Version : 1.3.
when I want to close Brackets, I usually need to click the  button twice, to make sure it really closed.This situation happens after I have saved all files, and if I didn't save all files before, I only need to click once after Brackets reminding me of saving.
It seems that this bug is an old bug since 1.1 .

**Comment by busykai** [comment] 2015-05-18 15:43
@yx91490, this is a known Linux issue. Duplicate of #4611. Closing.

**Closed by busykai** 2015-05-18 15:43 UTC
Labels: Linux only
