### ISSUE TITLE
accident F5 refresh clears all my undo/redo options

### ISSUE THREAD

**Issue by rajilesh** [adobe/brackets#11849] opened 2015-10-23 09:04 UTC
Please remove F5 shortcut key from brackets as it reloads and clear all undo/redo options entirely. I usually use chrome and brackets together to check every changes by pressing F5. And whenerver I press F5 from brackets, it simply clears all my undo/redo options.

It would be better using another shortcut for reloading brackets

Thanks Brackets Team

**Comment by petetnt** [comment] 2015-10-23 09:16
You might like my [brackets-persistent-history-extension](https://github.com/petetnt/brackets-persistent-history), which saves your editing history between changing projects and closing/reloading Brackets. 

*Note that the extension is still quite alpha as I haven't had much time to improve it lately, but I have been using it since I made it with small / negliable issues). Contributions to improve it are of course welcome!*

**Comment by abose** [comment] 2015-10-23 09:20
This is by design in brackets. But if you like to override it,
goto `debug>open user key map file` add the following in the json file

"overrides": {
        "F5" : ""
    }

**Comment by abose** [comment] 2015-10-23 09:21
Closing as designed, and user override already available.

**Closed by abose** 2015-10-23 09:21 UTC

**Comment by rajilesh** [comment] 2015-10-30 05:30
thanks petent and abose for your valuable comments :+1: . I have override using keymap file. It works perfectly well now. 

Thanks again :)

**Comment by sliterok** [comment] 2019-03-03 11:26
I guess that's worst design idea that i've ever met in my IDE experience
