### ISSUE TITLE
Brackets doesn't show up when I start the program 

### ISSUE THREAD

**Issue by destrik** [adobe/brackets#10313] opened 2015-01-05 16:01 UTC
Hi,

when I wanna use Brackets and I click on the Brackets Icon the program doesn't show up on my screen. If i hover over the Brackets Icon I see a little display of the program. That is all. I tried to uninstal and instal many times but that don't work. 

![naamloos](https://cloud.githubusercontent.com/assets/10401379/5615538/67987e50-94fc-11e4-8312-4e25979ebde6.jpg)

**Comment by redmunds** [comment] 2015-01-05 21:52
@destrik Did you run Brackets in a secondary monitor which has now been detached? If so, try clearing this Registry key: `HKEY_CURRENT_USER\Software\Brackets\Window Position`

**Comment by peterflynn** [comment] 2015-01-06 00:12
Yeah, this sounds exactly like #9742...

**Comment by TundeVm** [comment] 2015-01-10 08:38
I have this same issue, and I've been able to fix it following @redmunds fix. Thanks @redmunds

**Comment by peterflynn** [comment] 2015-01-27 23:53
Closing -- assuming it's a duplicate of #9742, which is fixed in 1.2

**Closed by peterflynn** 2015-01-27 23:53 UTC
