### ISSUE TITLE
Right click copy/cut/paste

### ISSUE THREAD

**Issue by phillip-haydon** [adobe/brackets#11303] opened 2015-06-24 02:15 UTC
Why does the context menu have a bunch of items that are useless but does not have copy/cut/paste???

![image](https://cloud.githubusercontent.com/assets/895629/8321484/f11df154-1a59-11e5-87b7-bff417df5219.png)

This is the same for me in all languages.

**Comment by sprintr** [comment] 2015-06-24 04:15
Duplicate of #11243

**Comment by nethip** [comment] 2015-06-24 04:18
@phillip-haydon We have captured adding "cut/copy/paste" to editor contex menu on this [card](https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu). Please up-vote it.

**Closed by nethip** 2015-06-24 04:18 UTC

**Comment by phillip-haydon** [comment] 2015-06-24 04:27
Upvoted. Thanks. I see it was created a LONG time ago :( hope it gets sorted out.

**Comment by nethip** [comment] 2015-06-24 04:41
@phillip-haydon Sure! We will prioritize this. Meanwhile you could look at this extension which adds `cut/copy/paste` menu entries to editor context menu. https://github.com/Denisov21/Popup-menu-extension

**Comment by phillip-haydon** [comment] 2015-06-24 04:49
Yup I grabbed that extension! It's great. Good intern solution.

Thanks!
