### ISSUE TITLE
Brackets hangs when using protocol relative urls with requirejs

### ISSUE THREAD

**Issue by fdefalco** [adobe/brackets#10566] opened 2015-02-10 15:19 UTC
using the following configuration will cause brackets to hang when switching between the file containing this content and other files.

```javascript
requirejs.config({
	baseUrl: 'js',
	shim: {
		"bootstrap": {
			"deps": ['jquery']
		}
	},
	paths: {
		"jquery": "//code.jquery.com/jquery-1.11.2.min",
		"bootstrap": "//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min"
	}
});
```

changing this to a protocol specific url resolves the issue

```javascript
requirejs.config({
	baseUrl: 'js',
	shim: {
		"bootstrap": {
			"deps": ['jquery']
		}
	},
	paths: {
		"jquery": "http://code.jquery.com/jquery-1.11.2.min",
		"bootstrap": "http://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min"
	}
});
```

**Comment by peterflynn** [comment] 2015-02-10 20:42
Where are you adding this?  In the `requirejs-config.json of an extension?  Are you editing Brackets core code?  Or are you using the native brackets-shell to host your own project that is different from Brackets?

**Comment by fdefalco** [comment] 2015-02-10 21:33
Sorry for being obtuse.  I'm using Brackets to edit a web site.  I had a few different extensions installed (github, beautify, code folding) but confirmed the issue persists with or without them.  Also did a clean install (release 1.1) and was able to recreate the issue.  If you like I can zip up a directory with minimal files that demonstrates this issue when you open the folder using brackets.

**Comment by peterflynn** [comment] 2015-02-10 23:39
@fdefalco Ah, so this is just a file you are editing inside Brackets?  Please do post a zip in that case -- I tried pasting the first snippet above into a JS file and Brackets still works fine for me after switching to a different file.

Also, make sure the problem still happens after _Debug > Reload Without Extensions_.

**Comment by fdefalco** [comment] 2015-02-11 15:54
Here is a link to a zip of a sample project directory that you should be able to unzip and then open the folder in Brackets.  I was able to recreate with Debug > Reload Without Extensions.

https://drive.google.com/file/d/0B_cXwlY8JUfILTJEVzRaZVRCX3M/view?usp=sharing

I wish I could give clear instructions on how to recreate the issue but it almost appears to be periodic, as if Brackets has a background loop on a timer where it tries to resolve URLs in the document (for intellisense features perhaps).  The good news it doesn't take more than 90 seconds or so to see the behavior.  I'll be switching files back and forth, then it begins to hang.  It repeats periodically.

Another pure guess, I'm on windows, wondering if could have something to do with the OS trying to resolve the protocol relative url as a local file or something.  Anyway, hope you are able to recreate so I know I'm not crazy.

**Comment by MarcelGerber** [comment] 2015-02-13 19:29
I can assure you you're not crazy. I can repro this issue, and it's weird. Investigating.

**Comment by MarcelGerber** [comment] 2015-02-13 22:48
It's an issue in tern-worker, and it happens only with the `requirejs` Tern plugin loaded.

The weird thing is, the hang is caused by a long pause (~8 seconds) in the WebWorker. The worker is idle during that time...

**Comment by MarcelGerber** [comment] 2015-02-14 08:07
So I've bisected the culprit in Tern, it's marijnh/tern@ed952de.
Now trying to put up a fix.

**Comment by rroshan1** [comment] 2015-06-22 06:25
The fix has been merged into master.
@fdefalco Can you please verify the fix and close the issue.

**Comment by MarcelGerber** [comment] 2015-06-22 18:16
@fdefalco Notice you have to wait for Release 1.4 to come out until you can try to see whether this is fixed.

**Comment by MarcelGerber** [comment] 2015-07-28 19:10
@fdefalco Release 1.4 is now available, hence you can try and see if this bug is fixed for you.
If you can still repro it, go ahead and let us know so we can reopen this issue.

Closing.

**Closed by MarcelGerber** 2015-07-28 19:10 UTC
Labels: fixed but not closed
