### ISSUE TITLE
Asks to save files with no changes

### ISSUE THREAD

**Issue by bobrocke** [adobe/brackets#11188] opened 2015-05-31 21:25 UTC
If I open a document, look at it, and then close it, Brackets thinks there have been changes and wants to save them. I can always choose "don't save," but it's annoying.

**Comment by MarcelGerber** [comment] 2015-05-31 23:10
Per our discussion on Slack, this issue was caused by https://github.com/brad-jones/whitespace (cc @brad-jones) and is now fixed.
Closing as extension problem (not extension idea, heh).

**Closed by MarcelGerber** 2015-05-31 23:10 UTC
Labels: extension problem
