### ISSUE TITLE
[CEF 2171] Droplists appear in wrong location

### ISSUE THREAD

**Issue by JeffryBooher** [adobe/brackets#10208] opened 2014-12-17 18:53 UTC
the container list list containing Options for `<select>` elements is positioned incorrectly after the `<select>` element moves

1. Start Brackets 
1. `View > Themes` 
1. Click on the `Current Theme` droplist
1. Dismiss the droplist and the dialog
1. Resize and Move Brackets so that it's a minimal size in the lower right-hand corner of the display
1. Repeat steps 2 & 3  
==> Drop list appears in the wrong place  

If you move Brackets to another Monitor it is on the wrong monitor even.  
It appears that the first invocation is where it lives forevermore.   

https://code.google.com/p/chromiumembedded/issues/detail?id=1208

**Comment by peterflynn** [comment] 2015-01-12 23:14
Fixes bug #5291.  Since this is a longstanding issue, removing milestone (though it's likely to land in 1.2 anyway since it's already making progress).

**Comment by redmunds** [comment] 2015-01-13 20:03
Confirmed. Closing.

**Closed by redmunds** 2015-01-13 20:03 UTC
Labels: cef, fix in progress, medium priority, native shell, Review, Win only
