### ISSUE TITLE
Fullscreen mode on second monitor is bugged after windows creator update

### ISSUE THREAD

**Issue by rmmc** [adobe/brackets#13349] opened 2017-05-03 12:19 UTC
### Description

After Windows Creator update, when drag brackets to a second monitor, it will not go on fullscreen mode and layout (UI) has a strange behavior

### Steps to Reproduce

1. Open brackets
2. Drag to second monitor
3. Try Fullscreen mode

**Expected behavior:** Fullscreen on entire screen

**Actual behavior:** Broken layout
http://imgur.com/S5Bxfyg

### Versions

OS: Windows 10 Home Edition
Version: 1703
Brackets Version: Release 1.9 build 1.9.0-17312 (release 189f6d39a)

**Comment by Yarik91** [comment] 2017-05-11 07:50
I'm here to tell same problem after Creator update.
I have two monitors :
1.Widescreen 1920x1080 
2. Old peace of sh***t 1280x1024

When I open brackets on second monitor and then drag to first and make it bigger than resolution of second monitor,  Brackets is cropped like that : http://prntscr.com/f6i2eq

**Comment by ficristo** [comment] 2017-05-11 18:07
In electron there were also some problems related to hidpi monitors. I think they were mostly fixed by updating to a new version of Chrome.
Also they mentioned the dpiAware field present in the manifest to change from `true` to `true/pm`.
Maybe we should also change our appshell.exe.manifest file.

**Comment by clarkejm** [comment] 2017-06-02 01:13
I'm having a similar issue. My laptop is 2560x1440 and my external display is 2560 x 1600 however if I open brackets on the laptop screen and move it to the external display it will not use more than ~%60 of the screen capital either when using "maximize" or by manually resizing.
If I then close Brackets and reopen it with the display connected, it seems to work normally.

**Comment by SirTobey1337** [comment] 2017-06-07 18:21
I could repro this problem. Seems to be a bug related to DPI density. Monitor specs are: 1366x768 (1) and 1920x1080 (2). Also resizing due to the sticky sides left and right does not work either way.

Maybe Microsoft is the one to blame?

System specs:
Windows 10 Version 1703 (Creators Update)
Brackets Release 1.9 Build 1.9.0-17312 (release 189f6d39a)

**Comment by iceuponfire** [comment] 2017-06-09 12:19
Another me too comment since i updated to creator update.

**Comment by SirTobey1337** [comment] 2017-06-11 04:04
Well, the problem only occurs if the Brackets window is moved from a lower resolution monitor to a high-res one. 
If you exit Brackets while it's opened on the high-res monitor, there's no buggy window if it gets maximized the other way round it *is* actually buggy.

**Comment by iceuponfire** [comment] 2017-06-12 08:05
I can confirm that, same behavior here and the problem still exist in 1.10 pre release 2

**Comment by jmmartinc** [comment] 2017-09-15 10:55
I have this error in Release 1.10 build 1.10.0-17483
![9c6f6f0dac2299dbcf24fec7caad7829](https://user-images.githubusercontent.com/10836503/30479331-07dfecac-9a15-11e7-86bb-4824936974f5.png)

**Comment by jayther** [comment] 2017-10-02 20:38
Still the same issue on Brackets Release 1.11, in the steps described in https://github.com/adobe/brackets/issues/13349#issuecomment-305662359

Something that wasn't mentioned is that the hidden parts of the UI on the bottom and right are still interactive (change tab/space and size, language picker, etc). It's just not visible.

System spec:
Microsoft Surface Pro 3, resolution: 2160 x 1440 with 150% scaling (default)
Dell U2410 external monitor, resolution: 1920 x 1200
Windows 10  Pro Version 1703
Brackets Release 1.11 build 1.11.0-17524 (release 86b5e2d4e)

<img width="964" alt="screenshot 2017-10-02 13 23 48" src="https://user-images.githubusercontent.com/2321030/31098110-6bab94c0-a776-11e7-8ce8-c16755606b9a.png">

**Comment by Sr33r4g** [comment] 2017-10-06 04:21
The temporary solution is to open Brackets directly in the second monitor.
Create a  shortcut in the second monitor's desktop and open it.

**Comment by josch87** [comment] 2017-11-09 08:41
Same with scalling in windows.

I have monitors with same resolution (1920x1080) but different dimensions. First monitor is smaller so it is scalled to 125% in Windows. Second monitor is scalled at 100%. Same behavior as comments above. If I scale both monitors at same percentage, I don't have problems as both have same resolution. But that's not an option of course.

**Comment by sciencedude100** [comment] 2018-01-10 05:28
same issue here on a 1680x1050 monitor

**Comment by nethip** [comment] 2018-01-10 08:27
@navch, @boopeshmahendran does either of you have some bandwidth to into this?

**Comment by alymck** [comment] 2018-02-02 16:22
Same issue. Brackets opens fine on my Surface Book screen. When moved to the (lower resolution) second monitor, the right hand side of the interface is not visible.

**Comment by nethip** [comment] 2018-02-06 04:24
@alymck We are working on fixing this. Apologies for the inconvenience. I would update this thread on the status as and when we make some progress.

**Comment by nethip** [comment] 2018-04-13 11:06
PR raised for fixing this issue. https://github.com/adobe/brackets-shell/pull/638

**Comment by vickramdhawal** [comment] 2018-04-24 06:05
Issue is resolved with [adobe/brackets-shell#638](https://github.com/adobe/brackets-shell/pull/638)

**Closed by vickramdhawal** 2018-04-24 06:05 UTC
Labels: Win only, cef, native shell
