### ISSUE TITLE
Copy Paste from the "box" in context menu.

### ISSUE THREAD

**Issue by VitaliyAT** [adobe/brackets#12651] opened 2016-08-04 19:46 UTC
It was very big negative surprise that such powerful and wonderful instrument have not such elementary things. It like make it without "Quit" option - just kill from manager task, All extensions that people did work very bad. 3 times copy is OK, 5 times - NO. Some nothing at all. Could you add normal copy paste context options from "box"?

**Comment by ficristo** [comment] 2016-08-06 07:59
On which OS are you?
Are you sayng there isn't a Quit option or it doesnt' work?

Some extensions are not always updated by their author. If you have troubles with them you should open issues on their repository.

Are you saing `Ctrl / Cmd + C` and `Ctrl / Cmd + V` don't work well?

There are already some issues about adding `Copy / Cut / Paste` to the context menu.

**Comment by petetnt** [comment] 2016-08-06 18:59
Duplicate of #12063

**Closed** 2016-09-03 17:54 UTC
Labels: Waiting for user
