### ISSUE TITLE
Enabled Experimental live preview is always on.

### ISSUE THREAD

**Issue by abdelouahabb** [adobe/brackets#10777] opened 2015-03-21 13:34 UTC
Hi, if this feature is enabled, it stays even if disabled, it will enable again, to disable it, it must be done from `brackets.json` and put `"livedev.multibrowser": false,`.

`Release 1.2 build 1.2.0-15697 (release 8f82e2a97) `

**Comment by prksingh** [comment] 2015-03-23 08:54
Do you mean you can't turn Experimental live preview off from the menu? Which OS is this? I just tried reproducing this in windows but couldn't. Could it be a timing issue (Can you check waiting for a few seconds and then turning it off to see if it fixes it)? Is it intermittent for you or you see this happening all the time

**Comment by abdelouahabb** [comment] 2015-03-23 13:01
Here is a trick to do:
1- Open the preferences file.

2- Enable or disable the experimental live preview from the Menu.

3- You will see that the file will not get modified!

here is an example, notice that there is no star near the name to tell that it has been modified.
![sans titre](https://cloud.githubusercontent.com/assets/2527234/6780400/24e704be-d165-11e4-8ff9-453436d24675.jpg)

**Comment by prksingh** [comment] 2015-03-25 07:36
Thats strange. I tried doing the same but it works fine for me
![prefchange](https://cloud.githubusercontent.com/assets/1701706/6819950/c2782966-d2ef-11e4-9fac-30b0a8932ecb.gif)

**Comment by abdelouahabb** [comment] 2015-03-25 19:33
@prksingh here is a video i made, the problem happens when you reload brackets.
http://youtu.be/g_XdEfRe8lg

**Comment by prafulVaishnav** [comment] 2015-03-26 11:23
@abdelouahabb Preference is not getting written to the file. Can you check by changing some other preference like space units, tab char and check if it is getting written to the file. Also, can you check if there is any error on the console (Help -> Show Developer Tools. Open console tab). Can you try reload brackets without extensions to make sure it is not caused by any buggy extension (Debug Reload Without Extensions)

**Comment by abdelouahabb** [comment] 2015-03-26 14:43
@prafulVaishnav this worked when extensions were off!

Here is the console content: http://pastebin.com/Ckv5uxNb

**Comment by prksingh** [comment] 2015-03-31 18:15
It would help if you could follow these steps to help us narrow, which extension is causing this:
https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually 

That way we can file a bug to the extension developer and try to get this fixed.

**Comment by ficristo** [comment] 2016-08-18 07:25
Closing as extension problem.
@abdelouahabb if you still have problems reopen or open a new issue.

**Closed by ficristo** 2016-08-18 07:25 UTC
