### ISSUE TITLE
Error when installing in Lubuntu 16.04

### ISSUE THREAD

**Issue by DiegoTc** [adobe/brackets#12875] opened 2016-11-06 04:53 UTC
### Description
Getting the following trying to install brackets.
`Error dependency is not satisfiable libgcrypt11 (>= 1.4.5)
`
Installation shouldn't cause any issue at the moment of executing the deb.

### Steps to Reproduce

1. Download Brackets Deb
2. Install the deb
3. Error appears

**Expected behavior:**  Brackets should be install with no complications

**Actual behavior:** Brackets isn't being installed.

### Versions

Please include the OS and what version of the OS you're running. Ubuntu 16.04.1 LTS

Please include the version of Brackets. 1.7.32

**Comment by zaggino** [comment] 2016-11-06 05:31
@DiegoTc try this link from README: https://nathanjplummer.github.io/Brackets

**Comment by ficristo** [comment] 2016-11-06 11:29
Dupe of #10255
Usual suggestion, give a try to https://github.com/zaggino/brackets-electron

**Closed by ficristo** 2016-11-06 11:29 UTC

**Comment by ErikThiart** [comment] 2017-04-03 09:04
Same issue seems brackets relies on outdated software.
