### ISSUE TITLE
Entering a new line with multi-line selection causes malformed code

### ISSUE THREAD

**Issue by krypsin** [adobe/brackets#11062] opened 2015-05-07 11:51 UTC
When I make a multiple line selection (in order to create a new line beneath each of the lines my cursor is on) it doesn't behave as expected.

To replicate this, I just do this:
1. Ctrl+Left click at the end of each line I want to enter a new line under.
2. Press Enter on my keyboard.
3. Lines are now messed up.

Instead it breaks my code and messes up it's formatting.
![Normal Code](http://puu.sh/hEzbQ/dd71fa0bea.png)
![Malformed Code](http://puu.sh/hEzcL/ac0f80d8b4.png)

Happens on v1.2 and v1.3

**Comment by redmunds** [comment] 2015-05-07 14:33
I don't have the same exact markup as your example, but this seems to work correctly for me. Use *Debug > Reload Without Extensions* and then try again to make sure this isn't caused by an extension.

**Comment by krypsin** [comment] 2015-05-08 12:11
Should have tried it without extensions first, thanks for that reminder.

...seems to work now.

Now I'll have to sift through which plugins cause this.

Did see this in Devtools, though (no extensions enabled)
![Dev tools](http://puu.sh/hFOdM/72c33524ab.png)

**Comment by peterflynn** [comment] 2015-05-08 21:33
Closing since this is not a core Brackets issue.

@krypsin If you're able to figure out what steps cause that 'foldgutter.js' error though, please file a new bug with steps to reproduce -- we should definitely fix that if we can get a handle on it.

**Closed by peterflynn** 2015-05-08 21:33 UTC
Labels: extension problem
