### ISSUE TITLE
Mousewheel Delta Track bar jumps

### ISSUE THREAD

**Issue by cbaldwinweb** [adobe/brackets#10730] opened 2015-03-10 01:13 UTC
Need to have a central option to change the speed of the track bar. When I scroll I miss half of my code because it's jumping way to much down. It seems to me the +50 in CodeMirror code could be doing this on the function `setScrollTop`. It should scroll nice and smoothly not jumping like this guys.

**Comment by peterflynn** [comment] 2015-03-10 01:35
Duplicate of #10214

**Closed by peterflynn** 2015-03-10 01:35 UTC
Labels: cef, Win only
