### ISSUE TITLE
Ability to open two folders at once in the same Brackets window

### ISSUE THREAD

**Issue by luissalitrero** [adobe/brackets#10691] opened 2015-03-04 16:59 UTC
1- Remember previous searches.
2- Add 'whole word' to search options.
3- Enhance search-replace when using regexp: if I search for "blabla" and replace it for "\nblabla" it adds the string "\n" instead of a new line.
4- Highlight matches when double click a word.
5- Be able to load/open multiple proyects/folders in same window, since right now it allows to open only one at a time.
6- If I press F5 it refreshes the editor and I lose change history.

Thank you

**Comment by peterflynn** [comment] 2015-03-04 22:20
1. See [Find: Recent search history](https://trello.com/c/IzACddEv/344-find-recent-search-history) -- you can upvote this and other items on our feature backlog to help raise their priority.
2. See [Find/Replace: 'Whole Word' toggle](https://trello.com/c/xabJJVcu/1078-find-replace-whole-word-toggle)
3. See [Find/Replace: Allow matching across lines (\n or multiline regex) or replacement text containing newlines](https://trello.com/c/yho8jb7y/1082-find-replace-allow-matching-across-lines-n-or-multiline-regex-or-replacement-text-containing-newlines) -- consider using [multiple cursors](https://github.com/adobe/brackets/wiki/Working-with-Multiple-Selections) via _Find > Add Next Match to Selection_ as a workaround
4. Enable the `highlightMatches` [preference](https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#preferences)
5. We do not currently plan to support this.  Could you describe your use case in more detail?  (Note that you can switch projects very quickly via the Recent Projects dropdown, and you can include a symlink folder in your project if you want to see files from another location in the same tree view).
6. This is a duplicate of #10222.  Note that you will never lose _unsaved_ changes this way. You can disable the shortcut by editing your key map as described [here](https://github.com/adobe/brackets/issues/10222#issuecomment-67525496).

**Comment by luissalitrero** [comment] 2015-03-05 00:19
Thank you for your quick reply, is very useful to know that maybe those items are already reported, I tried to search in Trello for what i am asking for but didn't find anything, i think i should have done something wrong. About point number five, what I mean is this scenario:

I am working in my project and have a lot of changes in my local history in every file i have modified, then i need a file which is in another folder, out of my current project, so i go to the Recent Projects dropdown and open the other project. Brackets closes my current project and opens the one i just selected from the dropdown list, then go back to my initial project and all the change history is gone.

Hope I was clear, my english is not as good as i wish.

**Comment by peterflynn** [comment] 2015-03-05 01:31
Do you mean unsaved changes?  I would recommend saving changes to disk much more frequently -- that's good practice no matter what editor you're using :-)

Also, as a workaround, you can always open individual files from another project using File > Open or by dragging file(s) onto the Brackets window from an OS folder view.

**Comment by MarcelGerber** [comment] 2015-03-05 21:19
@peterflynn I suppose what he means is undo history, as Brackets would show a "Save changes" dialog when switching away from the project with unsaved changes.

**Comment by luissalitrero** [comment] 2015-03-06 16:10
Hello, that's right, I mean "undo history", when i switch between projects, i lose my undo history, for that reason it would be nice to be able to open more than one project at a time. Thank you =)

**Comment by peterflynn** [comment] 2015-03-06 23:43
Reopening as move to backlog to consider adding that one piece to our feature backlog, since it's not currently represented there.  ([Multiple separate windows - official "New Window" command](https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command) is fairly similar though -- we could also just merge this into that card).

I suspect a feature like that would be a long way out in the future though.  For the near future, I'd suggest just opening the file(s) you need without switching projects, or getting comfortable with dropping your undo history when you do switch projects (don't forget it also gets cleared if you close a file without switching projects, or if the file changes externally on disk; and there's a limit to how many undo steps are stored in the history).

**Comment by luissalitrero** [comment] 2015-03-07 20:01
Hello, that's ok, and thanks again for your comments, see you =)

2015-03-06 16:43 GMT-07:00 Peter Flynn <notifications@github.com>:

**Comment by peterflynn** [comment] 2015-03-17 22:07
Ah, actually I just realized that last remaining part -- "Ability to open two folders at once in the same Brackets window" -- is already captured in #8632, so I'll close this as a duplicate.

**Closed by peterflynn** 2015-03-17 22:07 UTC
Labels: move to backlog
