### ISSUE TITLE
Add explanation string to jasmine's expect() failure message

### ISSUE THREAD

**Issue by gruehle** [adobe/brackets#2752] opened 2013-01-31 17:25 UTC
### _The Brackets team does not own or maintain Jasmine_

**Please direct your feedback to [this discussion thread](https://groups.google.com/forum/?fromgroups=#!topic/jasmine-js/1dG11nfnsu8)**, where the maintainers of Jasmine might actually see it.
<br>

-----

This came up during our architecture meeting.

The output of a failing unit test is cryptic. It shows the name of the test and a simple error like "expected false to be true". In the worst case scenario, you can get a bunch of failures where the name is exactly the same and the error messages are things like "expected 3 to be 4", "expected true to be false", etc. You need to scour through the stack report, find the line that caused the error and go to the source to see the error.

It would be nice if we could include a contextually relevant message to the error string.

**Comment by davidemannone** [comment] 2015-01-17 19:53
So I did it for my own for jasmine 2.0 and the related definitely-typed and I've posted it here: https://github.com/davidemannone/jasmine2.0-explained
Here is how to use it: expect(SOMETHING).toEqual(WHAT-EXPECTED).byFailReport("YOUR-CUSTOM-REPORT!");
and this reports only in case of the match fails this: "Expected SOMETHING to be WHAT-EXPECTED. >YOUR-CUSTOM-REPORT!<
For more details read the Readme.Me file.

**Comment by peterflynn** [comment] 2015-01-18 11:14
Closing -- official word from the Jasmine team (https://github.com/jasmine/jasmine/issues/641#issuecomment-54736801) is that this is unofficially supported already -- just pass an extra arg to the matcher (the function called after expect() -- but the preferred "Jasmine way" of accomplishing this is to write your own custom matcher that has enough context to provide a nicer message.

**Closed by peterflynn** 2015-01-18 11:14 UTC
Labels: low priority

**Comment by davidemannone** [comment] 2015-01-18 15:42
Hy Peter,

I saw it and I've rad all about them on every blog.  
For the first: the definitely typed has no other args provided and what about matchers they need variable lenght arguments? There are also some default of them in jasmine.
For the latter: that's ok and surely a good choice, but you have to provide for them costantly and in any test file and "override" any jasmine's default ones, for just printing out a string more that helps localize faster the exactly point of the problem (without starting then a debugging session).

I agree also that in BDD test could/should be treatet such a right way they do not need any other description other than the describe-it paradigm permits, but I think there is too much closure about such a simple feature like add an additional text to what already exists, whitout presenting it as a workaround or as it would be judged as a evil's help. I posted it right to suggest to continue the debate for find-out at least any official-default implementation. My personal opinion is: it would be easier to sopport it properly, extending the paradigm to a describe-it-accurately form, and then it is left to the user decide to use it or not. Could it be simply a choice of the developer to choose if use just one expect clause or many of them in one single Specs and supporting them anyway rightly if something fails?

I made it for me and I found it to be usefull, and I just decided to share it.

**Comment by sudharsan94** [comment] 2016-03-22 08:52
Could someone please give me a sample piece of code for configuring jasmine-custom-message with protractor.

**Comment by avrelian** [comment] 2016-03-22 11:30
@sudharsan94, It may be of [help](https://github.com/avrelian/jasmine-custom-message/issues/6)

**Comment by VenkatRamReddyK** [comment] 2016-07-11 18:49
I am trying to write **unit tests** using **karma** and trying to use `since` block provided by `jasmine-custom-message` framework to console the **failure** message.
So I was wondering if I missed something ?. 
I did the following: 
- **jasmine (1.3.1) and jasmine-custom-message (0.8.2)** are installed using `bower`
The `require('jasmine-custom-message');` in one of my test file` *.spec.js` is throwing the following error.
- ```PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: require```
- Issue: [ReferenceError: Can't find variable require](https://github.com/webpack/karma-webpack/issues/20) refers to the `karma.conf.js` file but not `*.spec.js` files.

**Comment by askucher** [comment] 2016-08-02 14:30
+1

**Comment by roopkt** [comment] 2017-02-03 17:45
I also think we should show the detail message. Currently it just says expected false to be true and bunch of useless file references like : buildExpectationResult@file:/// ..., expectationResultFactory@file:... , addExpectationResult@file:///C:/Users/, addExpectationResult@file://... in ..file (line 52) 
Which is not that helpful.

**Comment by roopkt** [comment] 2017-02-03 17:46
I also think we should show the detail message. Currently it just says expected false to be true and bunch of useless file references like : buildExpectationResult@file:/// ..., expectationResultFactory@file:... , addExpectationResult@file:///C:/Users/, addExpectationResult@file://... in ..file (line 52)
Which is not that helpful.

**Comment by nicomfe** [comment] 2017-02-10 01:59
Almost 3 years with this opened and we still dont have a custom message for expect :(

**Comment by ficristo** [comment] 2017-02-10 11:21
This issue is closed AFAICT. Also in the first comment there is written very clearly that Brackets team doesn't own or mantain jasmine.
If the issue is fixed in jasmine 2.0 keep in mind that we are using jasmine 1.3 and upgrading require most probably a complete rewrite of all our tests.
