### ISSUE TITLE
Crash: White screen after making edits

### ISSUE THREAD

**Issue by J-92** [adobe/brackets#13502] opened 2017-07-02 21:52 UTC
![screenshot](https://user-images.githubusercontent.com/7443257/27773764-bc14858e-5f78-11e7-9df3-37318d3b3b65.png)

I seem to be getting this problem above where brackets will crash after making some edits. I am not sure which key is triggering it, maybe backspace.

_/command/KeyBindingManager.js:747 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUp_addBinding @ /command/KeyBindingManager.js:747
/command/KeyBindingManager.js:747 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDown_addBinding @ /command/KeyBindingManager.js:747_

**Comment by petetnt** [comment] 2017-07-03 00:01
Hi @J-92,

does this occur with extensions disabled? (Debug -> Reload Without Extensions)?

**Comment by swmitra** [comment] 2017-07-04 03:56
@J-92 I don't think the errors in the console are relevant to the crash. Failure in keybinding can't cause app crash. Can you please let us know some elaborate steps to reproduce the crash. Most likely, it is caused by some extension which is trying to handle edits. 
As @petetnt suggested, try to reload Brackets without any extensions and see if you can reproduce the crash.

**Comment by J-92** [comment] 2017-07-04 09:18
I have "brackets-emmet" in my user install directory and have tried running with and without it using the above method. I unexpectedly have had no crash today which is unusual since I haven't changed anything I can think of, ill try report back again if it restarts crashing.

**Comment by swmitra** [comment] 2017-07-04 10:19
Thanks @J-92 for quick confirmation. You can close this now and re-open if you encounter the same problem again, and do let us know some more details like steps to reproduce the issue or any console errors.

**Closed** 2017-07-08 04:32 UTC
