### ISSUE TITLE
Quick Open dropdown – wrong position

### ISSUE THREAD

**Issue by valtlait** [adobe/brackets#9283] opened 2014-09-25 13:03 UTC
I noticed two bugs on Quick Open dropdown:

1) When no file is open and user selects *Navigate* → *Quick Open*, opens dropdown partially top of text field:

![brackets-quick-open-layout-bug-pic-1](https://cloud.githubusercontent.com/assets/5496284/4404535/27850472-44b2-11e4-836a-0d45aaa8f64f.png)

This doesn’t occur when using shortcut key (Ctrl-Shift-O).

2) When resizing window, Quick Open dropdown stays horizontally wrong position:

![brackets-quick-open-layout-bug-pic-2](https://cloud.githubusercontent.com/assets/5496284/4404647/a17bceea-44b3-11e4-9be0-74ad2520886a.png)

![brackets-quick-open-layout-bug-pic-3](https://cloud.githubusercontent.com/assets/5496284/4404674/e7b9ee1e-44b3-11e4-9f6c-2ee0474bef52.png)

**Comment by drfy55** [comment] 2015-02-27 05:11
the dropdown that should be be just below the quick open field covers the whole field so that I cannot type anything. (or typing is possible but invisible)

![image](https://cloud.githubusercontent.com/assets/4571420/6407780/01f6ba70-bdfc-11e4-8ff6-7741b69ca7e4.png)

**Comment by MarcelGerber** [comment] 2015-02-27 21:30
I sometimes saw the popover being positioned over the text box as well, but I'm not able to consistently repro it. Looks like a race condition.

**Comment by peterflynn** [comment] 2015-03-10 18:25
This seems to be something that came in with the new CEF in 1.1.  I'll check to see if my pending PR #7227 fixes this...

**Comment by peterflynn** [comment] 2015-04-07 19:47
The first issue will be fixed in the 1.3 release.  The second issue is a duplicate of #1157, so this overall issue can be closed.

**Closed by peterflynn** 2015-04-07 19:47 UTC
Labels: F QuickOpen, fix in progress, low priority
