### ISSUE TITLE
Hitting enter quickly can sometimes cause file rename to cut off new name

### ISSUE THREAD

**Issue by njx** [adobe/brackets#10531] opened 2015-02-05 23:28 UTC
Running into this on Mac 10.10.2.

1. In the file tree, right-click and choose New File
2. Type a new name like "foobar.js" and very quickly hit return after typing the "js"

Result: sometimes the new file will be named "foobar.j".

**Comment by njx** [comment] 2015-02-05 23:28
I'm hitting this pretty often.

**Comment by codymaines** [comment] 2015-02-06 03:34
I'm unable to reproduce this on Windows - what version & operating system are you using?

**Comment by njx** [comment] 2015-02-06 17:32
Mac 10.10.2. I just tried it in master again and it seems to be much harder to hit than in 1.1, so maybe something's improved, but I can get it if I type fast enough - I can see the last character show up in the input field but get truncated in the final filename. But it's hard enough to hit now that it's probably low priority - I'll try it again when 10.2 releases and see if it's still hard to hit.

**Comment by njx** [comment] 2015-02-06 18:31
I do still seem to be hitting this in master with some frequency, so probably still worth looking into at some point.

**Comment by peterflynn** [comment] 2015-02-06 19:23
@njx Sounds like a dupe of #10048, which we also had trouble reproducing...

**Comment by njx** [comment] 2015-02-06 19:25
That does sound like it, but I seem to be hitting it even without everything being slow (although it did seem more common, and also a tad slower, when I was using 1.1, which might have been because I had it open for longer or was working in a larger project).

**Comment by peterflynn** [comment] 2015-02-18 08:22
@njx The filer of #10618 reports that this happens when you haven't released the last letter key before pressing Enter -- i.e. the Enter keydown precedes the last letter key's keyup.  Do you think that could be what's happening in your case too?

**Comment by njx** [comment] 2015-02-18 17:59
That certainly seems plausible (and I can reproduce that reported behavior). Thanks to @ElegantScripting for figuring it out.

**Comment by prksingh** [comment] 2015-05-27 10:00
Should be fixed with #10648

**Closed by prksingh** 2015-05-27 10:00 UTC
Labels: F Project Management
