### ISSUE TITLE
Theme. How to apply differents styles to differents kind of comments ?

### ISSUE THREAD

**Issue by FletcherPink** [adobe/brackets#10220] opened 2014-12-18 17:18 UTC
Hello,
I discovered " Brackets" today and created a theme.
I will wish to apply a CSS style according to the kind of comment:

    /* Comment */ (style one)
    /** Comment **/ (style two)
    // Comment (style three)

Is there a way to do this?
Thank you

**Comment by redmunds** [comment] 2015-01-06 18:40
@FletcherPink This is an interesting technique. To work on changes, you'll need to keep track of the current document and listen for the "change" event.

Marking as an `Extension Idea`. Since this is not a bug, I'm closing.

**Closed by redmunds** 2015-01-06 18:40 UTC

**Comment by MiguelCastillo** [comment] 2015-01-06 18:43
@FletcherPink I can help you get this working if you start an extension you point me to it.

**Comment by peterflynn** [comment] 2015-01-07 01:20
@MiguelCastillo may have this in mind already, but just as a note: doing this on every "change" event would probably make typing performance very poor.  The best option is probably to implement a CodeMirror overlay mode.  See [here](http://codemirror.net/demo/mustache.html) for an example and [here](https://groups.google.com/forum/#!topic/brackets-dev/cePUzc4oOTs) for discussion of applying overlay modes within Brackets.

**Comment by peterflynn** [comment] 2015-01-07 01:21
Another way to approach this btw would be a pull request to CodeMirror to apply such distinguishing classes for everyone.  This would probably be very helpful in other places too (e.g. it might significantly simplify the comment-toggling code in our EditorCommandHandlers module).

**Comment by FletcherPink** [comment] 2015-01-07 08:12
@peterflynn That's exactly what I thought. CodeMirror seems to be the source to work. I tried to understand how CodeMirror works but my knowledge is too low so I gave up . Have you some tips and some explanation to tell me ?

@MiguelCastillo Thank you for your proposal . As an amateur , I will be honored to perform extension partenanriat with an expert. I have much to learn. I will focus on the overlay parsing and as soon as I wrote something , I will share it here .

**Comment by MiguelCastillo** [comment] 2015-01-14 16:12
@FletcherPink how is it going?  Thanks for the kind words, I am humbled. :)   Have you had any success starting up the project on github?

@peterflynn Yeah overlay seems like the way to go.  No need to really do on change events.
