### ISSUE TITLE
How to retrieve mistakenly deleted file from brackets?

### ISSUE THREAD

**Issue by bansalvks** [adobe/brackets#12547] opened 2016-06-25 09:45 UTC
Instead of `rename` I clicked on `delete` and the file got deleted (without any confirmation).

The file was very important and I need to get it back. please help. Urjent!!

**Comment by redmunds** [comment] 2016-06-25 16:49
@bansalvks Deleted files should be in your Recycle Bin (aka Trash Can).

**Comment by bansalvks** [comment] 2016-06-25 17:12
@redmunds many thanks. I am so silly that I did not check the file there.... However a confirmation message could save people a lot of time. is there a setting to activate the confirmation before delete?

**Comment by redmunds** [comment] 2016-06-26 16:52
Currently no setting for this. This issue is a duplicate of #8651. Closing.

**Closed by redmunds** 2016-06-26 16:52 UTC
