### ISSUE TITLE
UNIX Format

### ISSUE THREAD

**Issue by DatN3xus** [adobe/brackets#12639] opened 2016-08-02 09:35 UTC
I would love to see an option to change the format of wordwrap from Windows to UNIX. I'm often writing code for linux console (under Mac OS X or Win10) and get errors like: "/usr/bin/php^M: bad interpreter" because the line-end isn't in UNIX format. Notepad++ does have a possibility to change, but it's ugly. 

Please include it in the next update! :)

FYI:

http://stackoverflow.com/questions/14219092/bash-my-script-bin-bashm-bad-interpreter-no-such-file-or-directory
http://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter
http://askubuntu.com/questions/304999/not-able-to-execute-a-sh-file-bin-bashm-bad-interpreter

**Comment by ficristo** [comment] 2016-08-06 07:29
There are already some issues about line ending.
Closing as a dupe of the first I found: https://github.com/adobe/brackets/issues/10594
There is a pending PR https://github.com/adobe/brackets/pull/10346

**Closed by ficristo** 2016-08-06 07:29 UTC
