### ISSUE TITLE
Wrong parameter suggestions for JavaScript DOM Function

### ISSUE THREAD

**Issue by tjgerot** [adobe/brackets#12212] opened 2016-02-15 04:26 UTC
As I was coding, I realized that unlike `document.getElementsByTagName`, when I type in `document.getElementsByClassName` it is suggested not as a function (as it should), but as a method (like `.toLowerCase`).

Also, if I ignore the suggestion and keep typing it, brackets recognizes it as the method and proceeds to tell me there are no parameters (when there should be a string 'name').

Here are links to Mozilla's documentation on the `document.getElementByClassName`:
[click here.](https://developer.mozilla.org/en-US/docs/Web/API/Document/getElementsByClassName)

If this is truly an issue, the fix probably won't take that long. Thank you.

**Comment by petetnt** [comment] 2016-02-15 21:01
I can confirm, as can #12216. It is there on https://github.com/ternjs/tern/blob/master/defs/browser.json#L366 though. Weird.

**Comment by tjgerot** [comment] 2016-02-16 01:10
Yes the two JSON files you linked to showed it properly implemented. I compared it to the `document.getElementsByTagName` function, and I did notice while they were both declared as part of the giant `prototype` section of the JSON, our troubled function, `document.getElementsByClassName` was also referenced down on line 1278 which leads me to believe the error has something to do with bracket's interpretation of that reference (that similar functions did not have). My best guess is it has to do with brackets 'reading' (for lack of better  term) that function differently. Thanks for looking into this issue.

**Comment by petetnt** [comment] 2016-02-16 06:46
@tjgerot I was thinking the same, but then  again `querySelector` and `querySelectorAll` work as intended.

**Comment by busykai** [comment] 2016-02-18 01:26
It works for me, guys. Do you have any related extensions, such as `ternific`, installed?

**Comment by petetnt** [comment] 2016-02-18 06:58
@busykai I can replicate it without using any extensions too. I'm on `Release 1.7 development build 1.7.0-0 (master 01737d2a7)`.

**Comment by busykai** [comment] 2016-02-18 16:00
Nope, I was wrong. It does not work for me. I was trying `document.getElementsByTagName' instead. I'll have to look at what happens with our tern. Next week, perhaps.

**Comment by busykai** [comment] 2016-02-18 18:27
Oh, it's been fixed in `tern`. Our version hasn't been synced for over a year now. We're ternjs/tern@7606a64, so we don't have it. We need to update it.

**Comment by petetnt** [comment] 2016-02-18 19:14
@busykai cool :+1: 

I tried to update `tern` and `acorn` around a week ago but ran into troubles with `acorn`, is the package is now `browserified` which didn't play very nicely with ´requirejs` for some reason. I didn't spend much time with it and it did work on my [npm'd version of Brackets](https://github.com/adobe/brackets/issues/12006#issuecomment-166005753) in december though so it shouldn't be too hard to figure out when given some more thought.

**Comment by MiguelCastillo** [comment] 2016-02-18 21:03
@busykai we have a PR for bringing latest tern... I will take a look tonight to try to merge it soon.  I have neglected @MarcelGerber on that PR.

**Comment by petetnt** [comment] 2016-02-18 21:06
Oh yeah, totally forgot about the PR. #11569. It's up-to-date too.

**Comment by busykai** [comment] 2016-02-19 00:27
Thanks @MiguelCastillo! Merging that will fix this issue. I'll look into that PR as well.

**Comment by MarcelGerber** [comment] 2016-08-26 13:32
This is fixed with the merge of #11569 and will come to you in Release 1.8.
Please let us know if it still doesn't work for you when the Release ships.

**Closed by MarcelGerber** 2016-08-26 13:32 UTC
