### ISSUE TITLE
Could not load folders

### ISSUE THREAD

**Issue by ndaidong** [adobe/brackets#10399] opened 2015-01-17 09:55 UTC
Brackets Release 1.1 and Brackets Extract 1.1 do not work as well for me after I upgrade my OS from Linux Mint 17 to 17.1

Now it's just able to open single file, but could not load the folders.  

The error message after opening: http://i.imgur.com/uFlYy9D.png

If I try to choose another folder, it does not show any message, but there is not any file within specified folder is being listed out.

I'm using Linux Mint 17.1, 64-bit, with Nodejs v0.10.35, npm v1.4.28 and Chrome v39

Does Brackets require any other package?

Thanks.

**Comment by redmunds** [comment] 2015-01-17 17:19
@ndaidong It sounds like your Brackets installation may have been corrupted. Try uninstalling and re-installing Brackets.

**Comment by ApfelUser** [comment] 2015-01-18 11:49
@redmunds 

This is occurring on my PC too. I've re-installed Brackets and deleted the 
```
/home/<username/.cache/Brackets
```
and
```
/home/<username/.config/Brackets
```
folder. My developer tools output:


![brackets](https://cloud.githubusercontent.com/assets/7549136/5792268/4beb8814-9f10-11e4-8fb2-1894e097a2a9.png)

**Comment by ApfelUser** [comment] 2015-01-18 11:59
Oh, and I forgot to mention that the "file" sidebar is empty if I switch the folder from "getting started" to some of my project folders. So right now brackets is unusable for me.

This is occurring Ubuntu, Elementary OS and Linux Mint.

**Comment by ApfelUser** [comment] 2015-01-18 12:16
It also always re-opens "Getting started" when I reload with F5. So it seems like Brackets has no read / write permissions on `/home/<username/.cache/Brackets` and `/home/<username/.config/Brackets`

**Comment by redmunds** [comment] 2015-01-18 18:14
@ApfelUser 

Since this is "occurring on my PC too", I suspect that an extension has corrupted your **state.json** file. Be sure that you delete that file from `~/.config/Brackets` folder when Brackets is shutdown, or it will just rewrite it.

> when I reload with F5...

Try using Shift+F5 (Reload *Without Extensions*)

If it still doesn't work, try manually giving Brackets permission for those folders.

**Comment by ApfelUser** [comment] 2015-01-18 21:20
As I've said, I deleted `~/.config/Brackets` and re-installed Brackets. How do I give manually permissions to Brackets? I already own these folders.

**Comment by ndaidong** [comment] 2015-01-19 04:25
@redmunds : Thanks, I've tried to remove ~/.config/Brackets and re-install it. I also change permission of ~/.config/Brackets to 0777. The issue is still occurring, even I open Brackets with or without extensions.

@ApfelUser : Thanks, I got same result in the developer tool as your screenshot.

It seems this issue relates to  system language settings. Here are what I see with "locale":

> ndaidong@bella-mint-lab / $ locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8


Thanks for your time.

**Comment by peterflynn** [comment] 2015-03-06 20:33
This sounds like a duplicate of #9883.  Does adding `export LANG="en_US.UTF-8"` as suggested there help?  (It seems like your locale is already not set to "C", but it's worth making sure those settings are getting exported properly).

Also maybe try the fixes suggested here: http://askubuntu.com/questions/359753/gtk-warning-locale-not-supported-by-c-library-when-starting-apps-from-th (which suggests something is screwed up about your OS locale config if you're seeing errors like this).

**Closed** 2018-04-24 01:48 UTC
Labels: Linux only, low priority
