### ISSUE TITLE
Can not dismiss heath report window

### ISSUE THREAD

**Issue by AndZii** [adobe/brackets#12584] opened 2016-07-09 14:50 UTC
Can not dismiss heath report window

**Comment by ficristo** [comment] 2016-08-02 11:35
Are you able to click on the x icon and it doesn't close?
Can you look at `Debug \ Show developer tools` to see if is there any errors?

**Comment by ficristo** [comment] 2016-10-01 09:15
For now closing as a dupe of https://github.com/adobe/brackets/issues/12748 which is Linux only.

**Closed by ficristo** 2016-10-01 09:15 UTC
Labels: Waiting for user
