### ISSUE TITLE
Some Colors Are Repeated

### ISSUE THREAD

**Issue by PlanetVaster** [adobe/brackets#10693] opened 2015-03-04 20:33 UTC
In the dropdown colors list that appears when you type "color:" in a css file some colors such as darkslategrey, darkgrey, and dimgrey appear more than once in the list.
![dimgrey](https://cloud.githubusercontent.com/assets/11320438/6492751/b5bab38c-c283-11e4-9651-092e1db35ed7.PNG)
![darkgrey](https://cloud.githubusercontent.com/assets/11320438/6492752/b5bce1a2-c283-11e4-8559-265471faaf72.PNG)
![darkslategrey](https://cloud.githubusercontent.com/assets/11320438/6492753/b5c0c678-c283-11e4-954f-fd75d140259d.PNG)

**Comment by PlanetVaster** [comment] 2015-03-04 20:45
Ah i see its gray and grey but still shouldn't there only be one since it's the same color?

**Comment by MarcelGerber** [comment] 2015-03-04 21:15
It's supposed to be like this as the CSS Spec defines both `...grey` and `...gray`

**Comment by peterflynn** [comment] 2015-03-04 21:57
Yep, this is the expected behavior.  I could imagine having a pref to exclude one variant or the other, but since there are only a few of these cases that complexity might be overkill.

It's also a little odd that darkgray/darkgrey aren't sorted right next to each other -- probably a quirk or bug of the StringMatch heuristics.  Not sure that's worth keeping this bug open for either, though...

**Comment by MarcelGerber** [comment] 2015-03-04 22:19
It's not a bug in StringMatch, they are actually simply sorted alphabetically, but `darkgreen` comes before `darkgrey`.

**Comment by peterflynn** [comment] 2015-03-04 22:23
Ah, good point.

**Comment by PlanetVaster** [comment] 2015-03-04 22:51
Ok

**Comment by redmunds** [comment] 2015-03-05 00:31
We could check locale and show the *grey* variations for the British English (`en-gb`) and *gray* for American English (`root`). :)

**Comment by MarcelGerber** [comment] 2015-03-05 20:38
I don't think it's worth the effort doing something fancy here.

**Comment by PlanetVaster** [comment] 2015-03-05 21:59
I think it is worth the effort to do something fancy I might try to fix it myself and then submit a PR

**Comment by redmunds** [comment] 2015-03-05 22:04
In case you missed it, I ended my comment with a smiley face (i.e. I was joking). There are many other languages other than what I mentioned.

@PlanetVaster You should discuss with the team what you are thinking about implementing before you put a lot of effort into it.

**Comment by PlanetVaster** [comment] 2015-03-05 22:10
@redmunds I'm not sure yet because I'm more of a newbie web developer, I'm Intermediate with Java and know bits and bobs of multiple languages. I know html and css pretty good but I'm still learning Javascript. I would love to hear other people's ideas on this. I'm gonna start a discussion with the brackets dev google group.

**Comment by PlanetVaster** [comment] 2015-03-05 22:16
Just started a discussion https://groups.google.com/forum/#!topic/brackets-dev/Z9F0wIauYxQ

**Comment by peterflynn** [comment] 2015-03-05 23:45
I still think doing anything here is probably overkill (does any other editor filter these?)...

_But_ if we do anything I think it should be a preference, rather than something automatic based on locale.  For example: if one developer in the UK is working with a team in the US, they probably want to standardize their CSS code on the US spelling, so it would be annoying if Brackets refused to hint that version unless the UK user changed their whole OS locale.

**Comment by le717** [comment] 2015-03-06 00:31
I've read this issue over multiple times since it was filed: I don't see an issue here. The color names are correctly sorted alphabetically, and attempting to "fix" this would require highly specific, edge-case code, not to mention an untold amount of updating if new named colors are created by the CSS Working Group that recreate this issue. So yea, IMO, this is a complete non-issue.

**Comment by PlanetVaster** [comment] 2015-03-06 01:08
It's not an issue but still a bug in my opinion because it's spelled color in brackets not colour so it should either be gray or a preference, in fact we could make a feature where in preference (idk if there is preferences, but if there isn't then we could create one) there's an option to choose your language and there should be 2 english options one for U.S and one for British (U.K) that changes everything in brackets to that language. This is really annoying to me because i really got to pay attention to if its an e or an a in the gray, darkslategray, etc. colors as i'm from the U.S so i like to choose gray.

**Comment by PlanetVaster** [comment] 2015-03-06 01:09
It's kinda a mix between a bug and a feature i guess

**Comment by PlanetVaster** [comment] 2015-03-06 01:23
Also how many people know about: http://prime4commit.com/projects/153

**Comment by mackenza** [comment] 2015-03-06 01:32
@PlanetVaster what instances of `color` or `gray` would you be changing with the preference?  Certainly you aren't suggesting that it's in CSS or HTML that you would type a locale-specific entry like:

```css
colour: grey;
```
??

**Comment by Equinoxdawg** [comment] 2015-03-06 01:49
For those of us that aren't Americans; it can certainly be a pain in the ass. I've many, many times put "colour" instead of color and it's taken me ages and ages to remember that I have to accommodate for it all being in American. It'd definitely be a nice feature, but probably not that important.

**Comment by PlanetVaster** [comment] 2015-03-06 02:41
Yes it would be a minor feature but very nice to have, if anyone can figure out how to implement this please tell me.

**Comment by peterflynn** [comment] 2015-03-06 06:18
@Equinoxdawg That's a very different ask: `colour` is not valid CSS, and Brackets should not get involved in changing the spelling to make invalid code valid.

On the other hand `gray` and `grey` are both valid CSS and part of the specification -- the question is whether Brackets code hints should pretend one of the two are not, for the sake of convenience.  I'm still curious if any other code editor available today does this, though.

**Comment by redmunds** [comment] 2015-03-06 17:19
@Equinoxdawg If this truly bothers you, the https://github.com/idiot/spiffing repo tried to address the issue by creating a css preprocessor, but I always thought that it was more of an attempt at humor than anything else.

**Comment by PlanetVaster** [comment] 2015-03-06 20:07
@peterflynn Ah i just thought of an idea,i agree brackets should not make invalid css valid but if you type colour maybe it could have a red squiggly under it and when you hover over it it says "Did you mean color", And i have no idea if other code editors do this, but they should.

**Comment by MarcelGerber** [comment] 2015-03-06 20:50
Actually, with CSS Code Hints, it shouldn't be much of an issue to remember it's `color`:
![image](https://cloud.githubusercontent.com/assets/2641501/6536082/b8d13fb4-c44a-11e4-83e0-8ff0a20247f7.png)

**Comment by PlanetVaster** [comment] 2015-03-06 21:29
Whateves i really don't care about that part as im from the u.s so i spell it color anyway but i still don't like that it lists gray and grey as it's the exact same thing just spelled different

**Comment by le717** [comment] 2015-03-06 21:39
@PlanetVaster Then you'll need to take it up with the W3C, WHATWG and CSS Working Group about how all standardized web development should be pro-America only, form a viral hashtag to rally all web devs to remove all non-American spellings and references from standardized web code, persuade non-American developers to support your America-only stance, and convince browser makers to immediately drop support for the other spellings without any regard to backward compatibility. :wink:

Otherwise, this is a FOL (Fact of Life) and nothing can or really should be done about it. :)

**Comment by Equinoxdawg** [comment] 2015-03-06 21:41
@redmunds I wouldn't say it bothers me, and like I said, it'd definitely be a nice feature - if done correctly, but definitely not crucial to anything or even worth doing.

**Comment by PlanetVaster** [comment] 2015-03-06 21:48
@le717 I just want brackets to show gray if your american and grey if your british

**Comment by peterflynn** [comment] 2015-03-06 23:02
@PlanetVaster For the red-underline thing, please upvote ["Live" real-time linting as you type](https://trello.com/c/z1PBjZxt/588-live-real-time-linting-as-you-type) on our feature backlog.

**Comment by Moter8** [comment] 2015-08-07 15:07
Please don't fix this, stuff like this is feature creep. Further, i don't think many people still use these color names except maybe black and white.

**Comment by abose** [comment] 2015-08-10 05:58
As the hints are per W3c specification, This is expected behavio[u]r. Since brackets only impliments the standard, we cannot take this change unless the w3c spec says so. Closing.

**Closed by abose** 2015-08-10 05:58 UTC
Labels: F Code Hints, no priority
