### ISSUE TITLE
Add find and replace text in selection

### ISSUE THREAD

**Issue by engkusk** [adobe/brackets#12704] opened 2016-08-22 03:13 UTC
Its amazing text editor with much of features, but I and probably everybody need this features : please add features which I can **find and replace text in a block selection**. Don't make extension just make that features, cause it's important and usefull, and most of another editor has that features. Thanks

**Comment by ficristo** [comment] 2016-08-22 08:30
Closing as a dupe of #11194

**Closed by ficristo** 2016-08-22 08:30 UTC
