### ISSUE TITLE
Won't save when making changes in CSS file.

### ISSUE THREAD

**Issue by apolloinfinity** [adobe/brackets#10526] opened 2015-02-05 02:39 UTC
If I make a changes in my CSS file. Whether I make a small change in color or add a new rule, the file will not save. It will only save after I quit the program. I don't know if its brackets itself or one of the plug-ins that is causing this problem.

**Comment by redmunds** [comment] 2015-02-05 15:32
@apolloinfinity You can quickly check to see if this is caused by an extension by using Debug > Reload Without Extensions and then trying again to save.

**Comment by apolloinfinity** [comment] 2015-02-05 17:22
Thank you. It is an extension. Now I got to figuire out which one.

**Comment by redmunds** [comment] 2015-02-05 17:44
Closing. Please let us know here which extension it was. Also, open an issue on the repo of the extension.

**Closed by redmunds** 2015-02-05 17:44 UTC
Labels: extension problem

**Comment by peterflynn** [comment] 2015-02-05 20:34
The instructions at https://github.com/adobe/brackets/wiki/Troubleshooting#disabling-extensions-individually should help you figure out which extension.

**Comment by mainstreetmark** [comment] 2016-02-23 19:56
brackets-beautify v1.2.0 is causing this issue for me on .scss files (and i presume .css too)
