### ISSUE TITLE
Can't place cursor with mouse

### ISSUE THREAD

**Issue by GregS2** [adobe/brackets#10605] opened 2015-02-16 00:28 UTC
I had a situation where I could not place the cursor in any position to the right of column 44.  If I clicked on a position to the left of that point, and then moved the cursor with the arrow keys, that worked. Upon restarting Brackets, the problem went away. If I slowly moved the mouse pointer across the row of characters, from left to right, the pointer would change from the "text placement" vertical bar to the normal arrow as I moved from column 44 to 45. (I did nevertheless try clicking the mouse, to no avail)

Environment:
Brackets version:  1.1 build 1.1.0-15558
Windows 8.1

**Comment by abose** [comment] 2015-02-16 06:30
I could not see any of these behaviors in my setup. Where you able to repro this issue agan? Does this happen only to a particluar file?

**Comment by GregS2** [comment] 2015-02-16 07:14
I tried creating a new file, and the same problem occurred. I am editing .JS files. (and I'm pretty sure that I gave the new file the same extension)

No, it has not re-occurred yet after having restarted Brackets - I'll report back if/when it does.

**Comment by peterflynn** [comment] 2015-02-18 08:24
@GregS2 Do you have any extensions installed?  If so, please try running with extensions disabled for a while (_Debug > Reload Without Extensions_) to see if that makes the problem go away.

**Comment by GregS2** [comment] 2015-02-23 04:02
It's happened again. The maximum column number has changed - it is now 52. I.e, I can place the cursor at column position 1 through 52 inclusive - any further right than that, and the cursor switches to the standard mouse pointer arrow, and I can't set the edit point.

I do have some extensions installed, but the only non-theme extension is "HTML Templates": https://github.com/talmand/Brackets-HTML-Templates

I have not tried running without extensions yet. 

Before I restart Brackets, does anyone want me to gather any info or do any tests?

**Comment by GregS2** [comment] 2015-02-26 01:01
I've found the trigger. It happens when I close down a Live Preview browser session. When I do this, Brackets displays a pop-up alert. It appears that the area in the editor window that this pop-up covers can not be clicked on with the mouse, even after that pop-up has gone away. 

This problem occurs even with no extensions loaded.

**Comment by redmunds** [comment] 2015-02-26 01:14
@GregS2 Thanks for the detective work. Closing this issue as a duplicate of https://github.com/adobe/brackets/issues/10309.

**Closed by redmunds** 2015-02-26 01:14 UTC
