### ISSUE TITLE
Scrolling with mousewheel while marking text is stuttering

### ISSUE THREAD

**Issue by dr460neye** [adobe/brackets#12845] opened 2016-10-21 10:58 UTC
Issue:
Each time I select text at the End of an HTML File and start scrolling by mousewheel to the beginning the scrolling stutters. What do I mean by that? I do a 3 line scroll (Windows Default) by scrolling with the mouse wheel for one tick upwards. Now everything look fine. If I scroll up for another tick, I go 3 lines up and after this I scroll 1 line down automatically.

Environment:
Windows 10 - 64 Bit
Brackets Release 1.7 Build 1.7.0-16898 (release b0a363b71) 

How to reproduce:
Until now I wasn't able to reproduce this.
It just happens sometimes.

Did you perform a cursory search to see if your bug or enhancement is already reported?
I am not sure if it has something in common with the smoth scroll bugs.

**Comment by ficristo** [comment] 2016-10-21 16:31
Since you mention smooth scrolling, could you try to start brackets with a commandline switch:
`Brackets.exe --disable-smooth-scrolling` to see if it fixes your problem?

**Comment by ficristo** [comment] 2017-01-02 07:52
Since there were no answer closing as a dupe of #12520.

**Closed by ficristo** 2017-01-02 07:52 UTC
Labels: Waiting for user
