### ISSUE TITLE
Main Window shows up offscreen when Monitor is unplugged or screen size changes

### ISSUE THREAD

**Issue by bwighthunter** [adobe/brackets#9742] opened 2014-10-29 20:14 UTC
When I open up brackets after having an external monitor connected and close it after the monitor has been disconnected, the next time I open Brackets, I can't get to the window, even after plugging the same monitor in again.

Should always open on my main desktop window.

**Comment by peterflynn** [comment] 2015-01-06 00:13
Nominating for 1.2 -- this was in the 1.1 milestone originally but was dropped from that milestone without comment.  Seems like it should be an easy fix though.

**Comment by redmunds** [comment] 2015-01-08 22:04
Looks like I tried to fix this in [brackets-shell PR 144](https://github.com/adobe/brackets-shell/pull/144) (which was so long ago I forgot about it). Issue #2180 is also related.

**Comment by JeffryBooher** [comment] 2015-01-08 23:34
@redmunds it looks like your change may have gotten lost when the dark shell changes were merged.

It may be as easy as reintroducing that change to `CefMainWindow::RestoreWindowPlacement()`

**Comment by redmunds** [comment] 2015-01-13 20:04
Confirmed. Closing.

**Closed by redmunds** 2015-01-13 20:04 UTC
Labels: F General UI, fix in progress, medium priority, native shell, Review
