### ISSUE TITLE
Install on Ubuntu 16.04 fails, wants libgcrypt11, only has libgcrypt20

### ISSUE THREAD

**Issue by jdittrich** [adobe/brackets#12380] opened 2016-04-22 12:56 UTC
When attempting to install *Brackets* on *Ubuntu 16.04 LTS*, the installation fails silently (if not done via `dpkg` on the command line). This is  because *Brackets* depends on *libgcrypt11*; the installation routine remarks that *libgcrypt11* is not installed. *Ubuntu 16.04* only comes with *libgcrypt20*. 

The installation of the transitional *libgcrypt11-dev* does not resolve the problem (is only a dummy-package)

The attempted installation leaves the packaging system in a state of unresolved dependencies `sudo apt-get -f install` fixes the problem though.

**Comment by Learn-Digital-Audio** [comment] 2016-04-22 17:07
Hello,

I am a total Linux newb. I was about to try Ubuntu 16.04 LTS and Brackets in an attempt to get Windows 10 out of my life. First thing I find in my research is your post. Would you be so kind as to tell me:

1. Can i do a successful install of Brackets and Ubuntu 16.04 LTS? If so, *exactly* what should i do?
2. In your experience, is Brackets on Linux as reliable and excellent as it is on Win 7? Any problems that I might encounter?

MANY thanks.

**Comment by jdittrich** [comment] 2016-04-22 18:26
1. No, this is seemingly not possible until the dependency is fixed. 
2. It is pretty reliable; I encountered only #4611 as a bug, and it does not do anything bad.

**Comment by jdittrich** [comment] 2016-04-22 18:30
related (duplicates?): #11877 #10255

**Comment by petetnt** [comment] 2016-04-22 19:48
Like @jdittrich mentions, this issue is tracked at #10255, which contains workarounds for the issue too. The Linux version is looking for contributors to fix this and other issues (such as missing features, CEF update...) if you'd like to help out or happen to know someone who might be. 👍

**Comment by Learn-Digital-Audio** [comment] 2016-04-23 12:41
After a lot of reading it seems there was no legal way for Adobe to add the missing dependency in the official build, so some kind person has done it anyway:

https://brbsix.github.io/2015/10/28/fix-missing-libgcrypt11-for-brackets-text-editor/

I have not had time to test it yet.

The whole thing has been dealt with terribly by Adobe, real shame. There is no clear official info on this, it should be printed in massive bold letters next to the official download button! How long does it take someone to add a sentence next to a button? Here we go, i will do it:

A modern, open source text editor that understands web design.
Download Brackets 1.6
+ Extract (Preview) by Adobe 

**PLEASE NOTE: Linux build will not work on the following distributions due to a missing dependency:

ubuntu-16.04-desktop-amd64
.........etc etc......

Unofficial builds are available and can be found online.**

I am afraid I don't have the skills yet to help or I would.

**Comment by vankasteelj** [comment] 2016-04-24 12:40
Works fine for me, they're both installed: 

```
> dpkg -l | grep libgcrypt
ii  libgcrypt11:amd64                           1.5.3-2ubuntu4.2                                    amd64        LGPL Crypto library - runtime library
ii  libgcrypt20:amd64                           1.6.5-2                                             amd64        LGPL Crypto library - runtime library
ii  libgcrypt20:i386                            1.6.5-2                                             i386         LGPL Crypto library - runtime library
```

**Comment by guilherup** [comment] 2016-05-20 13:26
@Learn-Digital-Audio sugested site now it is on https://brbsix.github.io/2015/10/**29**/fix-missing-libgcrypt11-for-brackets-text-editor/
There aready have the *.deb files.
Thks!

**Comment by arezi** [comment] 2016-06-10 19:54
It has not been fixed in 1.7 version, unfortunatly.
Well, I installed unzipping the .deb, so I unziped the data.tar.xz
the data directory have the opt folder, so I put the opt/brackets folder into my /opt
but still miss the libgcrypt11, so I get it from @brbsix blog and put the lib into /opt/brackets/
and finally I can run: /opt/brackets/brackets

lib x64 https://www.dropbox.com/s/qkcnf8724ko9vos/libgcrypt.so.11?dl=1
lib x32 https://www.dropbox.com/s/43ij4lovqmhcddb/libgcrypt.so.11?dl=1

And I create in ~/.local/share/applications/ a .desktop descriptor to launch from menu

I hope to help someone :)

**Comment by iamrudra** [comment] 2016-06-11 01:48
A simple temporary fix is to install the libgcrypt11 from [Canonical LaunchPad website]  (https://launchpadlibrarian.net/201289896/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb). It is a deb package. Install it and retry installing Brackets. Works for me for Brackets v1.7.

Btw good job @brbsix! :+1:

**Comment by raghuveer-kurdi** [comment] 2016-07-08 14:50
@iamrudra Thanks for the solution, It worked for me. I also found other steps to install it. i.e via PPA
Follow this link http://www.webupd8.org/2013/11/install-brackets-in-ubuntu-via-ppa-open.html

sudo add-apt-repository ppa:webupd8team/brackets
sudo apt-get update
sudo apt-get install brackets

These three commands will also install the brackets, but i think the above solution is better as It also creates a luncher icon where as PPA doesn't. Not sure though.

**Comment by Learn-Digital-Audio** [comment] 2016-07-08 14:51
This is an automated reply to your message "Re: [adobe/brackets] Install on Ubuntu 16.04 fails, wants
 libgcrypt11, only has libgcrypt20 (#12380)" sent to david@learndigitalaudio.com.

Dear raghuveer-kurdi <notifications@github.com>

Thank you for your email. I am away from the office until the 13th July and will reply as soon as possible after that.

**Comment by ficristo** [comment] 2016-08-02 12:02
We are tacking the problem on #10255.
Closing as dupliclate.

**Closed by ficristo** 2016-08-02 12:02 UTC

**Comment by iamrudra** [comment] 2016-08-02 20:44
Just went through the comments on #10255 - Folks on that thread would be disappointed to know that the most appreciated comment on _this_ issue is something that they've termed as **ugly dangerous etc etc etc** 😈

**Comment by blbwd** [comment] 2016-08-20 15:53
@iamrudra you have saved my day, installing  libgcrypt11 separately worked for me like a charm. Thanks a lot.

**Comment by iamrudra** [comment] 2016-08-21 21:37
@blbwd - Cheers! 👍

**Comment by SamyCoenen** [comment] 2016-09-01 16:05
Install the official deb from launchpad https://launchpad.net/ubuntu/+archive/primary/+files/libgcrypt11_1.5.3-2ubuntu4.2_amd64.deb 
and then the brackets installation works flawlessly.

**Comment by kahon** [comment] 2017-04-27 19:27
Just install .deb of this site:

[](https://packages.debian.org/wheezy/amd64/libgcrypt11/download)

`sudo dpkg -i libgcrypt11_1.5.0-5+deb7u5_amd64.deb`

And then all right :).
Best!!

**Comment by ankit9j** [comment] 2017-05-01 04:06
Thank you @kahon 
Brackets installed now

**Comment by aryehbeitz** [comment] 2017-05-13 05:18
What about a real solution?
When someone tries downloading, they have to search for a solution.
The official packages should include the fix

**Comment by mgraves9803** [comment] 2017-05-15 01:42
You can get the latest files here (https://fourthfruit.github.io/fixes/)

**Comment by wayneworkman** [comment] 2017-08-13 15:00
@raghuveer-kurdi  your fix is the best here - this keeps all the packages installed within scope of a package manager.

**Comment by mgraves9803** [comment] 2017-08-13 15:05
*|MC:SUBJECT|*    

 		  [1] 

	Dear wayneworkman, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [adobe/brackets] Install on Ubuntu 16.04
fails, wants libgcrypt11, only has libgcrypt20 (#12380)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=1c91e3088f1b209e5337593a320d5330a5fc05a3

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org

**Comment by ebrahimkarimi** [comment] 2018-03-01 19:48
thanks to @kahon , it works perfectly but you should use `apt-get install -f` not `dpkg` command

**Comment by mgraves9803** [comment] 2018-03-01 19:51
*|MC:SUBJECT|*    

 		  [1] 

	Dear Ebrahim Karimi, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [adobe/brackets] Install on Ubuntu 16.04
fails, wants libgcrypt11, only has libgcrypt20 (#12380)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=cb253671ec4ae9d6e11cc3be15ce5c74efc226d5

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org

**Comment by ticout** [comment] 2018-03-18 06:49
thanks for all @kahon 
work fine for me!

**Comment by mgraves9803** [comment] 2018-03-18 06:52
*|MC:SUBJECT|*    

 		  [1] 

	Dear ticout, 

	maxg@kmail.org is only allowed to receive email from approved
senders. This means that your email to maxg@kmail.org will be delayed
until the parent of this child reviews and approves the message. There
is no guarantee that your message will be delivered to its intended
recipient. SUBJECT: Re: [adobe/brackets] Install on Ubuntu 16.04
fails, wants libgcrypt11, only has libgcrypt20 (#12380)
 STATUS: Delayed / In Parent's Mail Queue

	This approval process is due to a safety setting being set by this
child's parent. The parent is using KidsEmail.org to protect his/her
family. 

	Protect your family with KidsEmail.org! 

 		  [2] 

 		  [3] 

 		  [4] 

 		  [5] 

 		  [6] 

This message was intended for
reply@reply.github.com.
If you do not wish to receive _ANY_ emails from KidsEmail.org in the
future, please follow the link below to unsubscribe.
http://www.kidsemail.org/unsubscribe.php?SM_USER=reply@reply.github.com&DE_USER=eb89e42822d8c2b02df4b9885d166df97b2c241a

Links:
------
[1] https://www.kidsemail.org
[2] https://twitter.com/KidsEmail
[3] https://www.instagram.com/kidsemail/
[4] https://www.facebook.com/KidsEmail.org
[5] https://www.pinterest.com/kidsemail1/
[6] https://www.kidsemail.org
