### ISSUE TITLE
Allow setting default file type for files without extension

### ISSUE THREAD

**Issue by CupOfTea696** [adobe/brackets#12766] opened 2016-09-09 14:53 UTC
### Prerequisites
- [x] Can you reproduce the problem with `Debug \ Reload Without Extensions`?
- [x] Did you perform a cursory search to see if your bug or enhancement is already reported?
- [x] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?
### Description

Setting the default language for files with no file extension has no effect.
### Steps to Reproduce
1. Open file with no file extension
2. Click file-type selector in bottom bar (says "Text" by default for unknown file types)
3. Select a different file-type (e.g. "Bash")
4. Reload Brackets or open another file with no extension

**Expected behavior:** The file-type is Bash and it is syntax highlighting the content

**Actual behavior:** The file-type is Text and there is no syntax highlighting
### Versions

OS X Yosemite
Release 1.7 build 1.7.0-16898 (release b0a363b71)

**Comment by petetnt** [comment] 2016-09-11 10:40
Dupe of #12655 but this one is more meaty so I'll just close the old one :+1:

**Comment by petetnt** [comment] 2016-09-11 10:44
I made some work on this a while ago but didn't have to finish it yet. See this commit: https://github.com/petetnt/brackets/commit/b069d3ea9ce85f7cb8af62a66530b3c2402e69f0

Things that are missing: 

- Following file renames and deletes
- Unit tests

**Comment by alanbares** [comment] 2016-09-11 20:56
Well been wanting to help with Brackets since it's my usual IDE but not sure if if I can handle this issue. I'll try and give it a shot anyway.

**Comment by mpettaw2** [comment] 2016-09-26 15:18
I would love to work on this issue as well if that's ok.

**Comment by petetnt** [comment] 2016-09-26 15:23
@mpettaw2 of course! @alanbares have you made much progress? Could you perhaps coordinate together? 👍

**Comment by alanbares** [comment] 2016-09-26 18:21
@petetnt Not really, I feel completely lost tackling the issue :(.

**Comment by ficristo** [comment] 2016-09-26 18:26
@petetnt do we need to land @sprintr PR first?

**Comment by petetnt** [comment] 2016-09-26 19:26
@ficristo maybe not *need* for this feature,, but it would be a great addition on it's own and would be a good starting point for this feature too.

**Comment by mpettaw2** [comment] 2016-09-26 21:30
so i found the getFilenameWithoutExtension function. i was going to change that instead of the getFileExtension because I didn't want change the file before it got written to the program. anyway i was thinking of something like 

```
function getFilenameWithoutExtension(filename) {
        var index = filename.lastIndexOf(".");
        return index===-1 ?filename+".bat":filename.slice(0, index);
        
          /*mpettaw2: will return filename.bat if filename does not have an extension */
    }
```

just wanted to see if that was ok before i send it out....

**Comment by mansimarkaur** [comment] 2016-09-27 18:01
@mpettaw2 the getFilenameWithoutExtension function return filenames for directories as well and .bat won't be suitable extension for a directory. Also, this method is supposed to return only the filename after stripping the extension (if any), so adding .bat to a file without extension for returning as filename doesn't seem feasible.

**Comment by incorrectusername** [comment] 2016-10-05 04:34
Hello,
I'm new to Open Source. I would like to fix this issue . This is my first time.
Can someone help me get started?

**Comment by petetnt** [comment] 2016-10-05 06:10
Hi @incorrectusername!

That's great! See the article [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to get started with the Brackets codebase. If you have any questions, feel free to post them here! We also have a [Slack channel](https://brackets.slack.com) for day-to-day communication. (You can join by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register).

**Comment by haslam22** [comment] 2016-11-03 23:17
So, a little confused on this issue, by looking at #11560  it seems like the intended behaviour for extension-less files is:

- Show `Set as Default for <filename> Files` instead of `Set as Default for . Files` in the dropdown below
- Add the file name (or path?) mapping somewhere

Currently what happens is:

- User opens a file without an extension
- Selects a language and clicks `Set as Default for . Files`
- Preferences update by adding the `"" : language` mapping to the language.fileExtensions map
- This mapping is ignored by Brackets when calling `getLanguageForPath()`, but can be resolved by determining if there is no extension and checking the extensions map for the empty string

Unsure if we need to resolve the mapping being ignored, or if the behaviour needs to be similar to #11560

**Comment by AkshayMathur92** [comment] 2017-12-08 11:37
Why is this bug still open ?

**Closed** 2017-12-12 12:51 UTC
Labels: Starter bug
