### ISSUE TITLE
Brackets shows nothing.

### ISSUE THREAD

**Issue by AdithyaHarun** [adobe/brackets#11867] opened 2015-10-29 08:16 UTC
Excuse me, I want to continue my work on Brackets, but the app only shows menubar, blank sidebar, and blank workspace.
I try to close it, but nothing happen so I force-close it via Task Manager. After I reopen it, it returns to normal. Are there anything that I can do so this problem will not happen again?
Sorry for my bad english  :)

![image](https://cloud.githubusercontent.com/assets/7106825/10813091/4914e88e-7e57-11e5-95b7-50ce53e4ec7d.png)

**Comment by tallandroid** [comment] 2015-10-29 09:27
:100: Happened to me a lot of times. Brackets ends up being slow an unresponsive at times. I am assuming its the issue with chrome shell ?

**Comment by abose** [comment] 2015-10-29 10:46
can you try `debug>show developer tools` and comment the console messages here?

**Comment by danicholls** [comment] 2015-11-13 20:47
Same happens to me. I take it it's only helpful if we dump console here if it's when it opens blank, right?

**Comment by ficristo** [comment] 2016-08-17 16:22
Are you all still able to reproduce with the latest release? Event without extensions?

**Comment by ficristo** [comment] 2016-10-30 08:01
I close this since we didn't hear back from you.

**Closed by ficristo** 2016-10-30 08:01 UTC
Labels: Waiting for user

**Comment by danicholls** [comment] 2016-10-30 12:33
I stopped using Brackets in the meantime.
