### ISSUE TITLE
Unknown installation error extensionManager domain is undefined

### ISSUE THREAD

**Issue by iNovozhilov** [adobe/brackets#11805] opened 2015-10-12 08:16 UTC
/extensibility/Package.js:410 Unknown installation error extensionManager domain is undefined

win7 sprint 4 build 1.4.0-16380 (release 273804eb3)

**Comment by petetnt** [comment] 2015-10-12 16:08
Duplicate of #9723 I think. There are some things in that issue you could try out too :key:

**Closed** 2015-10-20 18:33 UTC
