### ISSUE TITLE
Mac: Title bar text is wrong color (too dark) when brackets-shell is built in newer Xcode

### ISSUE THREAD

**Issue by redmunds** [adobe/brackets#10446] opened 2015-01-22 15:35 UTC
Title bar text on Mac is now dark (in both Light and Dark Themes) as compared to Release 1.1 .

![dark-title-text](https://cloud.githubusercontent.com/assets/1197144/5858588/37d97f7e-a209-11e4-9ce6-ce0662a43f82.png)

**Comment by RaymondLim** [comment] 2015-01-22 17:12
I'm not seeing this on my 10.9. Might be only on Yosemite.

**Comment by redmunds** [comment] 2015-01-22 18:54
@RaymondLim Thanks for trying to repro. I can repro with a local dev build using `release-1.1` tag (in both brackets and brackets-shell), but I don't see it in an installed Release 1.1 build, so it does not seem to be a problem with Yosemite. I'll change to Medium Priority.

**Comment by nethip** [comment] 2015-02-03 06:10
@redmunds I am not able to repro this issue. I checked both on Mavericks and Yosemite. The screenshot above is the same one I keep getting on both the OSes(both dev and installed builds). I am guessing the title bar color would match to that of the project tree when the working set files bar is visible. 

![screen shot 2015-02-03 at 11 42 59 am](https://cloud.githubusercontent.com/assets/1577184/6015292/0e596170-ab99-11e4-9af7-53cbb4c64b0d.png)

I am assuming this is as designed. But if you think my understanding is wrong, could you please update a *before* and *after* screenshots with the working file set open.

**Comment by redmunds** [comment] 2015-02-03 17:52
Here is a screen shot of 1.1 with file in working set:

![release-1 1](https://cloud.githubusercontent.com/assets/1197144/6025829/50d71948-ab8a-11e4-8f8a-217686358eaf.png)

Here is a screen shot of 1.2 with file in working set:

![release-1 2](https://cloud.githubusercontent.com/assets/1197144/6025826/4ca53666-ab8a-11e4-89b6-e06fcd087e5b.png)

**Comment by redmunds** [comment] 2015-02-03 17:57
@nethip 

> I am assuming this is as designed.

No, this is not as designed.

I removed all extensions. I rebuilt bracket-shell with latest master branch. I deleted my brackets repo and re-cloned it. But, I'm still seeing it.

Does anyone else see this? If I'm the only one, then we can see if anyone in the community is seeing it after we post 1.2 Release Candidate builds.

**Comment by nethip** [comment] 2015-02-03 18:08
@redmunds Thanks for the screenshots. All the time I was referring to the *title bar* color even though the title of the bug says, text is what that is looking different. My bad. I will investigate further.

**Comment by JeffryBooher** [comment] 2015-02-03 23:08
@nethip looks like this change https://github.com/adobe/brackets-shell/commit/bfc2e1a458481485e4cd009110321836da6f763c

**Comment by redmunds** [comment] 2015-02-03 23:48
I just built release-1.1 locally and still see this problem. This might have something to do with the way we package the installed builds.

**Comment by JeffryBooher** [comment] 2015-02-03 23:57
I'm not seeing the problem with the current master (shell and brackets) on Mavericks

**Comment by nethip** [comment] 2015-02-05 09:08
@JeffryBooher thanks for pointing out the change. I will look into it.

Moving this to 1.3

**Comment by redmunds** [comment] 2015-02-05 15:35
@nethip I [tried building code before that change was made](https://github.com/adobe/brackets/issues/10446#issuecomment-72761916) and I still see the problem, so I don't think it's that change. It may be a Yosemite-only problem.

**Comment by nethip** [comment] 2015-02-05 15:59
@redmunds. I tried to repro this on Yosemite but no luck.:(. Maybe we should look at problem from a different perspective. anyways I will jump onto this bug immediately after 1.2 release.

**Comment by redmunds** [comment] 2015-02-05 17:42
@nethip On Yosemite, did you try an installed build or a cloned, local build? I'm not seeing it in 1.1 installed build, so it may be the combination of a cloned, local build on Yosemite.

**Comment by peterflynn** [comment] 2015-02-05 21:02
@nethip If this is only reproducible in Randy's local build (or even more generally, only reproducible in non-build-machine builds), I'd suggest the priority shouldn't be all that high since there's no user-facing problem.

**Comment by redmunds** [comment] 2015-02-11 17:39
Note that I do not see this problem in 1.2 Prerelease build.

**Comment by peterflynn** [comment] 2015-02-11 23:36
@redmunds I can sort-of repro with a local build on 10.9 (Mavericks):

![window titlebar](https://cloud.githubusercontent.com/assets/1197510/6158839/6529cc86-b203-11e4-821e-08bed9968294.png)

The text is darker than the official build, but not as dark as what you're seeing.  Maybe that's a Mavericks-Yoesmite diff.  (Note: both windows are inactive in the screenshot above; the titlebar text color stays the same when the window becomes active).

_But_ I'm building with Xcode 6.1.1 while [the official build instructions](https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell) say to use 4.x.  Could that explain the problem?  What version do you have?

**Comment by redmunds** [comment] 2015-02-12 00:34
@peterflynn I also have Xcode 6.1.1.

**Comment by nethip** [comment] 2015-04-08 06:51
I am still not able to repro this. Moving this to 1.4

**Comment by maxwellzdeamon** [comment] 2016-03-20 02:28
how do you get the title bar color to be dark?!?!  I came across this when googling "dark title bar mac"

**Comment by nethip** [comment] 2016-06-21 17:43
Closing this as the issue is fixed now.

**Closed by nethip** 2016-06-21 17:43 UTC
Labels: Mac only, medium priority, native shell

**Comment by nethip** [comment] 2016-06-21 18:02
I am putting in a little investigation notes for documentation sake.

The problem was that our build machine is using 10.9 SDK to build Brackets because of which the actual problem was getting pushed under the rug. Try building it 10.9+ SDKs, and the problem reappears.  The actual problem is that, we are pushing the `CustomTitleBarView` into `NSWindow`'s `NSThemeFrame`. According to Apple documentation, this is not supported and because of which we do see side effects like MACOS drawing the window title on top of our `CustomTitleBarView`. For now I have nuked the window title so that OS doesn't draw the black title string over ours. But this needs to be fixed going forward. 

If Brackets is launched from Terminal or Xcode, a warning`NSWindow warning: adding an unknown subview: <CustomTitlebarView: 0x60000012be00>. Break on NSLog to debug.
` is signalled by the OS with the following call stack.

```
	0   AppKit                              0x00007fffa0bcd7b7 -[NSThemeFrame addSubview:] + 107
	1   AppKit                              0x00007fffa0bcd4fc -[NSView addSubview:positioned:relativeTo:] + 211
	2   Brackets                            0x000000010002bd9d Brackets + 179613
	3   CoreFoundation                      0x00007fff9b38dbbc __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	4   CoreFoundation                      0x00007fff9b38db4f ___CFXRegistrationPost_block_invoke + 63
	5   CoreFoundation                      0x00007fff9b38dac7 _CFXRegistrationPost + 407
	6   CoreFoundation                      0x00007fff9b38d832 ___CFXNotificationPost_block_invoke + 50
	7   CoreFoundation                      0x00007fff9b34a5e2 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1922
	8   CoreFoundation                      0x00007fff9b349835 _CFXNotificationPost + 693
	9   Foundation                          0x00007fff959c917a -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	10  AppKit                              0x00007fffa0ceaf44 -[NSWindow becomeKeyWindow] + 1425
	11  AppKit                              0x00007fffa0cea971 _NXSendWindowNotification + 252
	12  AppKit                              0x00007fffa0cea274 -[NSWindow _changeKeyAndMainLimitedOK:] + 868
	13  AppKit                              0x00007fffa0db406f -[NSWindow _makeKeyRegardlessOfVisibility] + 98
	14  AppKit                              0x00007fffa0ced325 NSPerformVisuallyAtomicChange + 147
	15  AppKit                              0x00007fffa0db3fab -[NSWindow makeKeyAndOrderFront:] + 79
	16  Brackets                            0x000000010002cbe2 Brackets + 183266
	17  Foundation                          0x00007fff959f704e -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 1115
	18  Foundation                          0x00007fff959f6b75 -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 131
	19  Brackets                            0x000000010002de9a Brackets + 188058
	20  Brackets                            0x0000000100004334 Brackets + 17204

```
