### ISSUE TITLE
Files tree scroll bar almost impossible to see

### ISSUE THREAD

**Issue by kornfein** [adobe/brackets#12847] opened 2016-10-21 19:25 UTC
The left file tree scroll bar is very narrow and just slightly darker the background itself, This is in the brackets default (light) theme, the brackets default (dark) is a little better but i do not like the dark background in the editing area.  i tried a few other themes to no avail.
![brackets](https://cloud.githubusercontent.com/assets/5863663/19608972/690b18e2-97a2-11e6-9548-581609726478.png)

Either i would like the scroll bar to be wider or a more contrasting color.  Any configuration setting i can set to accomplish this? Otherwise i really like Brackets. See attached screen snapshot

**Comment by Denisov21** [comment] 2016-10-29 19:55
+1

**Comment by ficristo** [comment] 2016-11-02 19:28
I close this as a dupe of #12482

**Closed by ficristo** 2016-11-02 19:28 UTC
