### ISSUE TITLE
Installer associates extensions with Brackets without prompting user

### ISSUE THREAD

**Issue by hongkongdev** [adobe/brackets#14096] opened 2018-02-06 00:06 UTC
### Prerequisites

* [ ] Can you reproduce the problem with `Debug -> Reload Without Extensions`? **Not needed**
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?
* [X] Did you read the [Troubleshooting guide](https://github.com/adobe/brackets/wiki/Troubleshooting)?

### Description

When I did an upgrade to 1.12, the installer decided to associate files with Brackets that I didn't want associated with it. I wasn't prompted to associate any extensions.

### Steps to Reproduce

1. Have an existing installation of Brackets.
2. Download version 1.12 and perform an upgrade to that same directory.

**Expected behavior:** I expected to see a user interface to allow me to associate files with Brackets or not, or not have any files association mechanism with the installer at all.

**Actual behavior:** Several extensions, notably .SQL and .MD, were associated with Brackets. I didn't have anything associated with these file types for a specific reason.

### Versions

Windows 8.1 (I don't have my Brackets installation directory in the default directory).
Release 1.12 build 1.12.0-17621 (release d3b783b99) 
build timestamp: Fri Feb 02 2018 13:53:03 GMT+0000

**Comment by hongkongdev** [comment] 2018-02-06 00:13
.PHP is another extension that got undesirably associated with Brackets.

**Comment by ficristo** [comment] 2018-02-07 20:02
Duplicate of #9927

**Closed by ficristo** 2018-02-07 20:02 UTC
