### ISSUE TITLE
Full-screen display (F11 shortcut)

### ISSUE THREAD

**Issue by dincel** [adobe/brackets#12325] opened 2016-03-27 12:31 UTC
Ok the editor has a distraction free mode with shift+ctrl+2. But I'm still distracted with menu & tabs bar as well as other parts of the window. Why not just add F11 full-screen feature which you are left only with your workspace on the screen? Besides, I use a 13.3" ultrabook and I need every extra pixel of the screen for better handling the screen.

**Comment by petetnt** [comment] 2016-03-28 08:45
Duplicate of #11594. Should be possible with little fiddling of brackets-shell and updated CEF.

**Comment by abose** [comment] 2016-04-02 10:50
Closing duplicate

**Closed by abose** 2016-04-02 10:50 UTC
