### ISSUE TITLE
Undo/redo often stops working after save

### ISSUE THREAD

**Issue by idosius** [adobe/brackets#12090] opened 2016-01-17 16:24 UTC
Not sure when/why/how it reproduces, all I know is that suddenly it starts reproducing, especially for SCSS files. When it does it does start reproducing, then it only happens for a certain file and not other files. Restarting brackets makes it go away, for a short while, then it comes back.

**Comment by petetnt** [comment] 2016-01-17 17:18
See https://github.com/adobe/brackets/issues/11826 for more information

**Comment by ficristo** [comment] 2016-08-07 17:48
Closing as a duplicate of #11826

**Closed by ficristo** 2016-08-07 17:48 UTC
