### ISSUE TITLE
Crash on Mac Mavericks in traffic light code

### ISSUE THREAD

**Issue by njx** [adobe/brackets#7438] opened 2014-04-07 19:26 UTC
I just got this crash log while in the Save As (native) dialog:

https://gist.github.com/njx/10035385

It looks like the crash might have been related to the traffic lights.

**Comment by prksingh** [comment] 2015-02-06 14:24
I have not been able to reproduce this but looking at the crash log it appears like the memory for the NSImage instances for the trafficLightButtons are getting released before the updateButtonStates method. This is possible because the imageNamed API used for allocation returns an auto release pointer that could be cleaned up after the method if we don't retain it.

Ref: http://stackoverflow.com/questions/327082/exc-bad-access-signal-received 

I have added a fix that retains the memory for the NSImage instance variables. But can't confirm the fix since I could not reproduce this.

**Comment by nethip** [comment] 2015-02-16 08:47
Closing this as it is fixed now.

**Closed by nethip** 2015-02-16 08:47 UTC
Labels: fix in progress, Mac only, medium priority, native shell
