### ISSUE TITLE
Brackets node process dies after start

### ISSUE THREAD

**Issue by apla** [adobe/brackets#10276] opened 2014-12-24 22:37 UTC
I have such messages in log:

```
/thirdparty/react.js:4356 Download the React DevTools for a better development experience: http://fb.me/react-devtools
/LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87 NodeSocketTransport - start
extensions/default/DebugCommands/ErrorNotification.js:125 [node-error 1:32:14 AM] [Launcher] uncaught exception at top level, exiting. Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1135:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)extensions/default/DebugCommands/ErrorNotification.js:125 window.console.error
extensions/default/DebugCommands/NodeDebugUtils.js:114 [node-info 1:32:14 AM] [Server] stopping
/filesystem/FileSystem.js:941 File watchers went offline!
6/utils/NodeConnection.js:89 WebSocket connection to 'ws://localhost:48362/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
/filesystem/FileSystem.js:949 Watching disabled for /Users/apla/Library/Application Support/Brackets/extensions/user/
```

Brackets for Mac OS X,

Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Wed Dec 17 2014 12:50:55 GMT-0800

tried to remove all extensions, still same issue; brackets 1.0 works flawlessly

**Comment by apla** [comment] 2015-01-01 12:46
Fixed after reboot.

As you can see, there is no error context, no clue whats wrong

**Comment by peterflynn** [comment] 2015-01-05 10:24
@apla Sounds like it may be an issue with a firewall or network security app on your computer.  Sounds like the issue is resolved for you now though?

**Comment by prksingh** [comment] 2015-01-21 12:09
Closing for now. Please let us know if you see this again and we can open the bug again. Thanks.

**Closed** 2015-01-21 12:09 UTC
