### ISSUE TITLE
Errors when opening Brackets. Cannot open files.

### ISSUE THREAD

**Issue by remminator** [adobe/brackets#13346] opened 2017-04-30 16:48 UTC
I'm getting weird errors when opening Brackets. I can't edit any files, either. I tried deleting brackets.json and state.json to no avail.

Here's a screenshot of one of the errors I'm getting: http://i.imgur.com/6lLHpj6.png

**Comment by petetnt** [comment] 2017-05-01 17:42
Hi @remminator,

looks like the issue is with the [brackets-website-admin](https://github.com/Intronet/brackets-website-admin) extension. You can go to the location (`Users/YOUR_NAME/Application Support/Brackets/extensions/user`) and delete/move the extension by hand in there, after which Brackets should launch. 

(Funnily enough the part that does cause the issue is [from an extension I made](https://github.com/petetnt/brackets-persistent-history] that the `brackets-website-admin` extension uses 🤔, so this might be worth refiling in https://github.com/petetnt/brackets-persistent-history anyway 🤔)

**Comment by remminator** [comment] 2017-05-01 18:39
Thanks a bunch, Pete! That did it :)

**Comment by petetnt** [comment] 2017-05-01 18:42
Nice 👍 Closing as solved

**Closed by petetnt** 2017-05-01 18:42 UTC
