### ISSUE TITLE
Ctrl+z is not working after saving!!

### ISSUE THREAD

**Issue by Attrash-Islam** [adobe/brackets#12043] opened 2016-01-03 08:00 UTC
Hi, 
I have seen this issue before and you didn't resolved it.
It's not connected with any plugins, it deleting all the changes when loading with extension and without extension! and that could delete your entire code when you wrongly type "ctrl+a" and then overriding all the code accidentally! and when you try to undo that it's not working!

Your product is so awesome but please take care of that bug.

I'm using: Ubuntu 15.10

**Comment by ficristo** [comment] 2016-01-03 10:36
Dupe of https://github.com/adobe/brackets/issues/11826.
I cannot reproduce reliably so if you have any clear steps to reproduce let us know.

**Comment by abose** [comment] 2016-01-28 06:17
We are aware of this issue, but the fix and the actual problem is still illusive. Working on it.
Closing as duplicate.
Please post further comments on #11826

**Closed by abose** 2016-01-28 06:17 UTC

**Comment by devfelipereis** [comment] 2016-04-18 11:53
+1 but I cannot reproduce.

**Comment by ScottTPete** [comment] 2016-05-04 19:25
+1. Started when I got the git for brackets extension.

**Comment by sebasrealino** [comment] 2016-05-10 12:57
Same error here!

**Comment by Nezahual** [comment] 2016-06-10 07:17
Same here, it just happens to me in `.twig` files.

**Comment by scopolamin** [comment] 2016-06-20 08:02
https://github.com/adobe/brackets/issues/11826
