### ISSUE TITLE
Cannot undo after save

### ISSUE THREAD

**Issue by thany** [adobe/brackets#11846] opened 2015-10-22 13:45 UTC
I can't undo after just having saved the document. This worked fine in the previous version. No errors appear in the dev console when trying. The menu item for Undo is not greyed out.

This is Bracket 1.5 on Winows 7 x64.

**Comment by redmunds** [comment] 2015-10-22 14:25
Seems to work for me on Win 7 x64. How are you trying to undo? Maybe you're hitting problem where shortcut stops working. Does *Edit > Undo* work?

Otherwise, please provide more details about type of file, size of file, type of edit, etc.

**Comment by petetnt** [comment] 2015-10-22 17:16
Duplicate of #11826

**Comment by abose** [comment] 2015-10-23 08:49
Closing duplicate.

**Closed by abose** 2015-10-23 08:49 UTC
