### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by ColemanTO** [adobe/brackets#10790] opened 2015-03-24 20:31 UTC
It would be nice to have the standard context menu on right-click - cut, copy, paste, etc.

**Comment by peterflynn** [comment] 2015-03-24 21:42
Closing as a duplicate of this item on our feature backlog: [Clipboard Cut/Copy/Paste in Editor Context Menu](https://trello.com/c/ZriVEu50/935-clipboard-cut-copy-paste-in-editor-context-menu). Please upvote it there to help raise its priority.

**Comment by peterflynn** [comment] 2015-03-24 21:43
Unless there are menu items other than Cut/Copy/Paste that you feel are missing :-)  Please let us know more details if so.

**Closed by peterflynn** 2015-03-24 21:42 UTC

**Comment by ColemanTO** [comment] 2015-03-25 16:31
Sublime has a couple of other nice options under the right-click:

![image](https://cloud.githubusercontent.com/assets/2119454/6829611/856507f4-d2e2-11e4-85a4-b6efad81d89c.png)
