### ISSUE TITLE
libgcrypt11

### ISSUE THREAD

**Issue by piesha** [adobe/brackets#12503] opened 2016-06-10 18:39 UTC
I was really looking forward to using Brackets as I am learning JavaScript/CSS/HTML with Freecodecamp. But come on, the .deb file I spent 20 minutes downloading from where I live in Beijing doesn't even work. And this is a well documented issue, that has existed for over a year so why not add some explicit instructions from the downloads page and the FAQ on the site? 

Now I am using a third party repository/hack to get an older version working. What are we going to do about this and how do I get the newest version of the software working on Ubuntu?

Thanks in advance,

**Comment by ldez** [comment] 2016-06-11 11:30
Duplicate of #10255, #12380, #12282

**Comment by piesha** [comment] 2016-06-11 15:08
Duplicate of a bug that has existed for over a year and nobody (in the tickets you referenced) assigned to fix it. How will this come to be resolved if nobody is working on it?

**Comment by ldez** [comment] 2016-06-11 15:12
Not in open a duplicate issue.

**Comment by piesha** [comment] 2016-06-11 15:18
> Duplicate of #10255, #12380, #12282, adobe/brackets-shell#501

Is there another issue/ticket open besides these that shows progress? Is someone working on this somewhere behind the scenes?

**Comment by ldez** [comment] 2016-06-11 15:23
Please don't be aggressive.
Respect the rules: http://todogroup.org/opencodeofconduct/#Atom/opensource@github.com

You can see a PR here: https://github.com/adobe/brackets-shell/pull/501

The main issue is #10255.

An issue with no body assigned, does not mean that no work on it.

**Comment by ficristo** [comment] 2016-08-02 11:49
Closing as duplicate.

**Closed by ficristo** 2016-08-02 11:49 UTC
