### ISSUE TITLE
No native menu on Ubuntu w/ Unity

### ISSUE THREAD

**Issue by maciek134** [adobe/brackets#11501] opened 2015-07-28 22:16 UTC
It's probably intened, but many people, including me, don't like when software doesn't care about native UI look & feel. The menu on Unity should be on the top of the screen (like on OSX), not embedded in the window.
![screenshot at 00-09-16](https://cloud.githubusercontent.com/assets/1146309/8945333/c8d423e2-3586-11e5-9210-536895580d75.png)

Here is how it looks properly in Chrome:
![screenshot at 00-16-42](https://cloud.githubusercontent.com/assets/1146309/8945377/226a3f2c-3587-11e5-8c58-996e7da59d0e.png)

**Comment by mackenza** [comment] 2015-07-28 22:26
Brackets shell doesn't have native menus in any Linux window manager. It's not limited to Unity. It is a known thing and "as designed" in current Brackets

**Comment by iNovozhilov** [comment] 2015-09-25 23:58
before
![2015-09-26 02 41 59](https://cloud.githubusercontent.com/assets/3082812/10114481/cc0614de-63f9-11e5-88c0-b788ca171503.png)
after
![2015-09-26 02 41 21](https://cloud.githubusercontent.com/assets/3082812/10114487/f4ea0cde-63f9-11e5-8b23-e6783b567af1.png)
edit
![2015-09-26 02 40 45](https://cloud.githubusercontent.com/assets/3082812/10114497/17716f68-63fa-11e5-8016-7a615bded8ce.png)
code
```
#titlebar {
   padding: 0;
   font-size: 13px;
   height: 22px;
   background: #efefef;
}
#titlebar .nav {
   margin: 0;
}
#titlebar .nav li {
   line-height: 11px;
}
#titlebar .title-wrapper {
   display: none;
}
#titlebar .nav .dropdown-menu {
   top: 23px;
}
#titlebar .nav .dropdown .dropdown-toggle {
   padding: 4px 4px 5px 4px;
}
```
handmade forever!

**Comment by maciek134** [comment] 2015-09-26 10:36
@iNovozhilov well, sure, but that part is easy, now move it where it should be :D 
Looking at how this is still open I'm going to go the open-source way and try to do it myself, at least for Linux (don't have neither an OSX machine or experience with OSX UI).

**Comment by iNovozhilov** [comment] 2015-10-02 21:08
@maciek134 use it :)
https://github.com/iNovozhilov/brackets-linux-menu

**Comment by ficristo** [comment] 2016-11-03 19:10
I close this as a dupe of #7236

**Closed by ficristo** 2016-11-03 19:10 UTC
Labels: Linux only
