### ISSUE TITLE
Copy and/or paste broken in 1.2 on 64-bit Win8.21

### ISSUE THREAD

**Issue by fastinvsqrt** [adobe/brackets#10763] opened 2015-03-19 19:13 UTC
I'm sorry if this has been reported already, but I recently upgraded from 1.1 to 1.2 on a 64-bit Windows 8.1 and copy/paste functionality is now broken. I tried using Ctrl+C and Ctrl+V as well as going into the menu.

I did not have the time to check to see if content was actually copied to the clipboard when I pressed Ctrl+C, so I am not sure if it is copy or paste that is broken.

**Comment by prafulVaishnav** [comment] 2015-03-20 06:15
@fastinvsqrt  Can you please try this to make sure it is not caused by any extension :  Start by using Debug > Reload Without Extensions

**Comment by peterflynn** [comment] 2015-03-20 07:45
@fastinvsqrt Do you have "Webroot Identity Shield" installed?  There is a known bug in that product that blocks copy/paste for some Brackets users -- see #2531 / #6683.

**Comment by fastinvsqrt** [comment] 2015-03-20 12:10
@prafulVaishnav I can re-install 1.2 later and try.

@peterflynn I don't have Identity Shield, but I do have Webroot SecureAnywhere.

**Comment by peterflynn** [comment] 2015-03-20 18:22
@fastinvsqrt Webroot is almost certainly your problem then.  Can you try the fix described in https://github.com/adobe/brackets/issues/2531#issuecomment-23747772 or the settings workaround suggested in https://github.com/adobe/brackets/issues/2531#issuecomment-75397950?  If neither of those work, please contact Webroot support for a more permanent fix following these instructions: https://community.webroot.com/t5/Webroot-SecureAnywhere-Antivirus/Cut-Copy-or-Paste-Problems-Character-Entry-Issues-Scripting/ta-p/18396#.UhKP9pLVBsk

**Comment by fastinvsqrt** [comment] 2015-03-22 15:26
@peterflynn I'm sorry it has taken me so long to get back to you, but the solution you described in #2531 ([here](https://github.com/adobe/brackets/issues/2531#issuecomment-23747772)) worked. Thank you!

**Comment by prksingh** [comment] 2015-03-23 09:25
Closing the issue as fixed

**Closed by prksingh** 2015-03-23 09:25 UTC
