### ISSUE TITLE
CTRL+Z it won't work some times!!

### ISSUE THREAD

**Issue by BilalDja** [adobe/brackets#12141] opened 2016-01-22 21:01 UTC
Some times when I really need to undo some work, the **Ctrl+Z** it won't respond!

**Comment by Lemmmy** [comment] 2016-01-23 04:10
have you tried writing code first

**Comment by petetnt** [comment] 2016-01-23 07:36
Duplicate of https://github.com/adobe/brackets/issues/11826

**Comment by ankurloriya** [comment] 2016-01-24 19:41
I feel Ctrl+Z move scroll even code line on view port(not out of the view area).

**Comment by abose** [comment] 2016-01-27 08:21
closing duplicate.

**Closed by abose** 2016-01-27 08:21 UTC
