### ISSUE TITLE
Untitle-1 document (new documents), should allow you to select file type.

### ISSUE THREAD

**Issue by wyattbiker** [adobe/brackets#12257] opened 2016-03-01 15:14 UTC
I use Brackets to temporarily placing data such as JSON and XML to analyze.

I want to beautify it, but I cannot do it because the drop down is grayed out. Why do i have to save the file first? 

Thanks!

**Comment by petetnt** [comment] 2016-03-02 12:46
Hi @wyattbiker,

there's an card on Trello for this (https://trello.com/c/CNXuU4TY) but AFAIK it's not being worked on at the moment. If you would like to take a stab on implementing it the community can provide feedback and help for sure :+1:

**Comment by ficristo** [comment] 2016-11-24 19:10
Dupe of #11637

**Closed by ficristo** 2016-11-24 19:10 UTC
