### ISSUE TITLE
Multi-monitor setup breaking ability for Brackets to maximize

### ISSUE THREAD

**Issue by Auhmaan** [adobe/brackets#13636] opened 2017-08-24 10:32 UTC
### Keep in mind that...

... this bug happens on an environment where there's two monitors, **monitor A** with 1920 by 1080 and **monitor B** 1080 by 1920 ( basically two 1920x1080 monitors where the second is in portrait mode ).

### Description

When opening Brackets in **monitor A** and _maximizing_ it, it works at expected, Brackets fill the entire screen. If I grab the Brackets window and drag it to **monitor B** and maximize it there, it will fill the screen horizontally, but will only expand to the height of the **monitor A**, cutting the rest of the window that is below that height. 

If I try to resize the window's height, it works fine until I get to the point where the height of the window is bigger than the height of the **monitor A**. Other weird fact about the resized window is, although the bottom of the window isn't visible, if I find the border of the window, after releasing it I can still see the Windows OS cursor to change from the default pointer to the vertical resize one, allowing me to resize the window.

The same happens if I start on **Monitor B**, only this time is the width of the window that is cropped.

### Steps to Reproduce

1. Get two monitors with different resolutions. Open Brackets on one of them and maximize the window.
2. Close Brackets and reopen it.
3. Grab the window by the title bar ( this is the way I do, where the bug happens ) and drag it to the second monitor, releasing it on the **TOP** of the monitor ( so when released Windows maximizes the window, as if pressing the maximize button )
4. The bug should happen now. As I stated at the beggining, this seems to be an intermitent bug, so it might not work on the first try.

**Expected behavior:**
Brackets to fully occupy the second monitor.

**Actual behavior:**
Brackets maximizes on second monitor, but it's cropped by the height of the first monitor.

**Images**

_Despite in the images the icon of update being visible ( initially teste on 1.9 ), after the update the bug persisted._

![](http://imgur.com/zembML0.png)
![](http://imgur.com/KbsyqsK.png)
![](http://imgur.com/9GifvHE.png)
![](http://imgur.com/l13eNyR.png)

### Versions

Windows 10 Pro
Release 1.10 build 1.10.0-17483 (release 024bee940)

**Comment by Auhmaan** [comment] 2017-10-13 16:37
Any news on this bug?

**Comment by tfoote000** [comment] 2018-04-02 17:56
I also have this bug, Monitor setup:
![image](https://user-images.githubusercontent.com/38013852/38207883-74a5d4b6-366c-11e8-9507-5012eec7f681.png)
Monitor 2/3: 1920 x 1080
Monitor 1: 1080 x 1920

Windows 10 Pro
Brackets:
Release 1.12 build 1.12.0-17621 (release d3b783b99) 
build timestamp: Fri Feb 02 2018 13:53:03 GMT+0000

**Comment by alexvickers** [comment] 2018-04-25 19:55
This also happens if Monitor B is in landscape view.

**Comment by CharlesDesper** [comment] 2018-05-22 22:21
I am also having this issue with a 1440x2560 monitor in portrait mode. As the original poster, Auhmaan said the weird thing about this bug is the program is extending beyond what it shows as you can interact with everything that gets cuts off.  It seems to cut off wherever the maximum height would be if the monitor was in landscape mode. It also seems to be inconsistent. When I first start my computer the issue doesn't appear but after a while, the issue starts.

**Comment by sobisht** [comment] 2018-05-23 05:00
Duplicate of https://github.com/adobe/brackets/issues/13349.

Issue has been resolved with https://github.com/adobe/brackets-shell/pull/638

**Closed** 2018-05-23 05:00 UTC
