### ISSUE TITLE
Can i see live preview on my ipad ?

### ISSUE THREAD

**Issue by MickeyBadBad** [adobe/brackets#10289] opened 2014-12-29 16:52 UTC
I know there is two way to get this .
1,use something like Air Display .
2,do something like apache allow deny mechanism , and use browser in ipad .
i want to know , does there have option 2 ? if not , Could you guys make it ? ( it's will be a good function i think ~ )

**Comment by webRat** [comment] 2015-01-05 17:15
You can already do this now without any additional work? Your iPad has to be on the same lan as your machine using Brackets. When it browses to (localhost):(port)/file, you'll browse to (ip address of machine running backets):(port)/file You have to keep live preview running on the machine running backets at all times or the connection will break?

**Comment by ILYG** [comment] 2015-01-10 14:33
the problem is the port start from Brackets is only allowed by localhost , i can't find how to change it to allowed all ip requests .

**Comment by webRat** [comment] 2015-01-10 14:46
No, your machine has an internal ip.

Assuming you're on a mac, go to Apple->System Preference->Network->Look at your wifi connction and it should say, "Wi-Fi is connected to {{ Network name }} and has the IP address {{ Something like 192.168.1.x. }}"

Then go to http://192.168.1.x/path/to/your/files on your ipad.

**Comment by webRat** [comment] 2015-01-10 14:48
Nevermind, I see what you mean now. If you're not familiar with setting up servers and such, perhaps CodeKit is the way to go for you.

**Comment by ILYG** [comment] 2015-01-12 08:35
I just had a pad , not Mac @-@ . and i think the setting up things i'm good at it . can you tell me what can i do specificly , please ?

**Comment by redmunds** [comment] 2015-01-27 23:27
@busykai Is this a possibility for Live Preview MultiBrowser? If not, then feel free to close it.

**Comment by busykai** [comment] 2015-01-28 18:45
@redmunds yeah, actually, i have a patch to enable remote connectivity to live preview (as an option). i will submit a PR to start the discussion. it will have its implications though such as security, need for manual launch etc.

**Comment by busykai** [comment] 2015-01-31 18:57
@redmunds, @ILYG there's a functional implementation for *multi-browser LivePreview only* in `kai/ld-remote-connectivity`.

**Comment by JKAussieSkater** [comment] 2016-02-04 00:14
Bump!

**Closed** 2017-03-22 06:18 UTC
Labels: F Live Preview, F Live Preview MultiBrowser, no priority
