### ISSUE TITLE
File Naming Bug (more info in comments)

### ISSUE THREAD

**Issue by ElegantScripting** [adobe/brackets#10618] opened 2015-02-18 01:10 UTC
This is a core brackets bug, and doesn't correlate with extensions nor RAM nor OS.

I'm having this issue on both my Mac OS 10.10.2 laptop and my Windows 7 desktop on the latest version of Brackets, with or without extensions enabled (I have tested both).

Here's a visual example of the bug:
![feb 17 2015 19 38](https://cloud.githubusercontent.com/assets/5307412/6240490/41a55d64-b6dd-11e4-8b3b-faf63cba550e.gif)

The bug occurs when a character key is pressed, but has not been released before the enter / return key is pressed. Try literally holding down a character key while creating or renaming a file and pressing enter while the first key is still held down; it will produce the same result.

For extremely fast-typers like myself, you can see how this may be a problem, as part of our fast-typing is owed to a self-formed habit of pushing down other keys while our fingers have still not released the previously typed keys. Although this may only be for a few milliseconds, the computer (as always) is receptive to everything.

I would assume this could be fixed by storing each character on keyDown within a string variable and then submitting that variable to the file creation method upon keyUp of the return key. Although I may be speaking out of context (I'm not sure how the internals of Brackets are designed and haven't had the time to read through them), theoretically (at least in my head) it could work.

Nevertheless, I have faith that this will get fixed soon - although it may not be priority, it looks like an easy fix (and kind of a fun one).

Thanks.

**Comment by peterflynn** [comment] 2015-02-18 08:21
Sounds like a duplicate of #10531 / #10048.  Thanks for the info about the Enter key overlapping with the last-typed letter -- I'll leave a note in the original bugs to see if that matches others' experience.

**Comment by prksingh** [comment] 2015-05-27 10:00
Should be fixed with #10648

**Closed by prksingh** 2015-05-27 10:00 UTC
Labels: F Project Management
