### ISSUE TITLE
Search and Replace with Escaped characters

### ISSUE THREAD

**Issue by adamkoncz** [adobe/brackets#10679] opened 2015-03-03 14:05 UTC
Search and Replace doesn't work with escaped characters like new line (\n) or horizontal tab (\t) etc.

**Comment by peterflynn** [comment] 2015-03-03 22:47
Closing as a duplicate of this backlog item: [Find/Replace: Allow matching across lines (\n or multiline regex)](https://trello.com/c/yho8jb7y/1082-find-replace-allow-matching-across-lines-n-or-multiline-regex).  Please upvote that link to help raise its priority!  (There are also some workarounds listed there that you can use in the meantime).

To match on `\t` you can just use the existing regex mode though (toggle the ".*" button in the search bar).

**Closed by peterflynn** 2015-03-03 22:47 UTC
