### ISSUE TITLE
Portable/Standalone edition for all platform

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#13071] opened 2017-01-29 03:49 UTC
I am wishing for portable edition for all platform just plug and play without need of installation/.exe file

**Comment by ficristo** [comment] 2017-01-29 15:52
Dupe of #12835

**Closed by ficristo** 2017-01-29 15:52 UTC

**Comment by MandarSant** [comment] 2017-01-30 04:07
@ficristo it is not duplicate the .#12835 is issue

**Comment by ficristo** [comment] 2017-01-31 19:01
The underlying issue is the same: the lack of a portable build.
