### ISSUE TITLE
Disable blur when switching panes

### ISSUE THREAD

**Issue by demisx** [adobe/brackets#10491] opened 2015-01-30 01:55 UTC
I often compare two files in a vertical split (side by side). Currently, non-active pane gets greyed out slightly on blur. Is it possible to disable that? I want active and non-active panes to stay at 100%.

**Comment by peterflynn** [comment] 2015-01-30 02:37
Duplicate of #9785, which should be fixed soon.  In the meantime, you can use the "Restore Pane" extension as a workaround.

**Closed by peterflynn** 2015-01-30 02:37 UTC

**Comment by demisx** [comment] 2015-01-30 15:52
Thank you. `Restore Pane` extension did it. Just gotta remember uninstall it when this fix lands in a release.
