### ISSUE TITLE
Can't use brackets because of this strange menu bar bug 

### ISSUE THREAD

**Issue by surajmandalcell** [adobe/brackets#13738] opened 2017-09-27 04:16 UTC
I did some research and found this to be a troublesome issue as it means there's something wrong with my systems text encoding but just to double check it i wanted to file a bug to see if its my OS (ubuntu 17.10 daily builds) or is it brackets on its own or conflicting with some other program.

**A picture says a thousand words so here's the accurate representation of what the problem is**

![screenshot from 2017-09-19 23-00-09](https://user-images.githubusercontent.com/11650177/30895481-2f8f68c0-a368-11e7-875a-03c2b38b643a.png)

![screenshot from 2017-09-27 09-43-17](https://user-images.githubusercontent.com/11650177/30895514-532f6244-a368-11e7-80e8-a859579b1a17.png)

![screenshot from 2017-09-27 09-43-11](https://user-images.githubusercontent.com/11650177/30895520-59b468f8-a368-11e7-9909-7911a5e58c6a.png)

![screenshot from 2017-09-27 09-43-14](https://user-images.githubusercontent.com/11650177/30895518-56663f8c-a368-11e7-8142-ddfc3a9dc7ea.png)

## Please fix

**Comment by narayani28** [comment] 2017-09-27 09:42
@surajmandalcell - Brackets works fine on Ubuntu 16.04.3 LTS and we have verified the working on the LTS with no issues. Kindly switch to 16.04.3 LTS for working with Brackets.

**Comment by mmmmmmbeer** [comment] 2017-09-27 14:06
Experiencing the same issue here on Fedora 26. I suspect an invalid character set or language somewhere in the config, but haven't located anything yet.

**Comment by hnaparst** [comment] 2017-09-27 15:10
Same problem on Gentoo

**Comment by ficristo** [comment] 2017-09-27 17:43
See also https://github.com/adobe/brackets/issues/13731

**Comment by kuboosoft** [comment] 2017-09-28 02:10
The error persists! full log... Using Fedora 26...

```
[makerpm@localhost brackets]$ ./Brackets
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 0000008d813e
#0 0x7ff5dabba7db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7ff5d7d993b0 <unknown>
#2 0x7ff5ddbd2db3 sandbox::CrashSIGSYS_Handler()
#3 0x7ff5ddbd19fb sandbox::Trap::SigSys()
#4 0x7ff5d7d993b0 <unknown>
#5 0x7ff5d79f21db getrandom
#6 0x7ff5d6e79b05 <unknown>
#7 0x7ff5d6e7b743 XML_ParseBuffer
#8 0x7ff5c210e6fd <unknown>
#9 0x7ff5c215069c <unknown>
#10 0x7ff5c210bbc7 <unknown>
#11 0x7ff5c3d8c52e <unknown>
#12 0x7ff5c3d5bcc9 <unknown>
#13 0x7ff5c3d8d2f8 <unknown>
#14 0x7ff5db44f6b1 gfx::GLContextGLX::Initialize()
#15 0x7ff5db43de67 gfx::GLContext::CreateGLContext()
#16 0x7ff5db84f95a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7ff5db84f33a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7ff5db84eb63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7ff5db840a48 IPC::MessageRouter::RouteMessage()
#20 0x7ff5db84c163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7ff5db84c0e2 gpu::GpuChannel::HandleMessage()
#22 0x7ff5db84cbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7ff5dabbb9ec base::debug::TaskAnnotator::RunTask()
#24 0x7ff5dabd5355 base::MessageLoop::RunTask()
#25 0x7ff5dabd5678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7ff5dabd583b base::MessageLoop::DoWork()
#27 0x7ff5dabb0cfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7ff5d88a6247 g_main_context_dispatch
#29 0x7ff5d88a65e8 <unknown>
#30 0x7ff5d88a667c g_main_context_iteration
#31 0x7ff5dabb0bd6 base::MessagePumpGlib::Run()
#32 0x7ff5dabec030 base::RunLoop::Run()
#33 0x7ff5dabd4b7a base::MessageLoop::Run()
#34 0x7ff5dd469b9d content::GpuMain()
#35 0x7ff5ddc9b257 content::ContentMainRunnerImpl::Run()
#36 0x7ff5ddc99d00 content::ContentMain()
#37 0x7ff5daac0b03 CefExecuteProcess()
#38 0x7ff5daa64ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7ff5d79d650a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007ff5de6b77d9 r14: 00000000000d813e r15: 00007fff90e849e0
  di: 0000000000000002  si: 00007ff5de6b77d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 00000000000d8000  cx: 00000000008d813e  sp: 00007fff90e849d0
  ip: 00007ff5ddbd2db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 00000000008d813e
[end of stack trace]
[0927/200314:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
[0927/200314:ERROR:gpu_channel_host.cc(228)] Failed to send GpuChannelMsg_CreateCommandBuffer.
[0927/200314:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 00000080813e
#0 0x7f61adbab7db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7f61aad8a3b0 <unknown>
#2 0x7f61b0bc3db3 sandbox::CrashSIGSYS_Handler()
#3 0x7f61b0bc29fb sandbox::Trap::SigSys()
#4 0x7f61aad8a3b0 <unknown>
#5 0x7f61aa9e31db getrandom
#6 0x7f61a9e6ab05 <unknown>
#7 0x7f61a9e6c743 XML_ParseBuffer
#8 0x7f61950ff6fd <unknown>
#9 0x7f619514169c <unknown>
#10 0x7f61950fcbc7 <unknown>
#11 0x7f6196d7d52e <unknown>
#12 0x7f6196d4ccc9 <unknown>
#13 0x7f6196d7e2f8 <unknown>
#14 0x7f61ae4406b1 gfx::GLContextGLX::Initialize()
#15 0x7f61ae42ee67 gfx::GLContext::CreateGLContext()
#16 0x7f61ae84095a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7f61ae84033a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7f61ae83fb63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7f61ae831a48 IPC::MessageRouter::RouteMessage()
#20 0x7f61ae83d163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7f61ae83d0e2 gpu::GpuChannel::HandleMessage()
#22 0x7f61ae83dbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7f61adbac9ec base::debug::TaskAnnotator::RunTask()
#24 0x7f61adbc6355 base::MessageLoop::RunTask()
#25 0x7f61adbc6678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7f61adbc683b base::MessageLoop::DoWork()
#27 0x7f61adba1cfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7f61ab897247 g_main_context_dispatch
#29 0x7f61ab8975e8 <unknown>
#30 0x7f61ab89767c g_main_context_iteration
#31 0x7f61adba1bd6 base::MessagePumpGlib::Run()
#32 0x7f61adbdd030 base::RunLoop::Run()
#33 0x7f61adbc5b7a base::MessageLoop::Run()
#34 0x7f61b045ab9d content::GpuMain()
#35 0x7f61b0c8c257 content::ContentMainRunnerImpl::Run()
#36 0x7f61b0c8ad00 content::ContentMain()
#37 0x7f61adab1b03 CefExecuteProcess()
#38 0x7f61ada55ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7f61aa9c750a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007f61b16a87d9 r14: 000000000000813e r15: 00007ffea8d71920
  di: 0000000000000002  si: 00007f61b16a87d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 0000000000008000  cx: 000000000080813e  sp: 00007ffea8d71910
  ip: 00007f61b0bc3db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000080813e
[end of stack trace]
[0927/200315:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
../../sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0318
Received signal 11 SEGV_ACCERR 00000082813e
#0 0x7f14613d97db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#1 0x7f145e5b83b0 <unknown>
#2 0x7f14643f1db3 sandbox::CrashSIGSYS_Handler()
#3 0x7f14643f09fb sandbox::Trap::SigSys()
#4 0x7f145e5b83b0 <unknown>
#5 0x7f145e2111db getrandom
#6 0x7f145d698b05 <unknown>
#7 0x7f145d69a743 XML_ParseBuffer
#8 0x7f144892d6fd <unknown>
#9 0x7f144896f69c <unknown>
#10 0x7f144892abc7 <unknown>
#11 0x7f144a5ab52e <unknown>
#12 0x7f144a57acc9 <unknown>
#13 0x7f144a5ac2f8 <unknown>
#14 0x7f1461c6e6b1 gfx::GLContextGLX::Initialize()
#15 0x7f1461c5ce67 gfx::GLContext::CreateGLContext()
#16 0x7f146206e95a gpu::GpuCommandBufferStub::OnInitialize()
#17 0x7f146206e33a _ZN3IPC8MessageTI35GpuCommandBufferMsg_Initialize_MetaSt5tupleIJN4base14FileDescriptorEEES2_IJbN3gpu12CapabilitiesEEEE18DispatchDelayReplyINS6_20GpuCommandBufferStubEvMSB_FvS4_PNS_7MessageEEEEbPKSC_PT_PT0_T1_
#18 0x7f146206db63 gpu::GpuCommandBufferStub::OnMessageReceived()
#19 0x7f146205fa48 IPC::MessageRouter::RouteMessage()
#20 0x7f146206b163 gpu::GpuChannel::HandleMessageHelper()
#21 0x7f146206b0e2 gpu::GpuChannel::HandleMessage()
#22 0x7f146206bbb3 _ZN4base8internal7InvokerINS_13IndexSequenceIJLm0ELm1EEEENS0_9BindStateINS0_15RunnableAdapterIMN3gpu10GpuChannelEFvRK13scoped_refptrINS6_22GpuChannelMessageQueueEEEEEFvPS7_SC_EJNS_7WeakPtrIS7_EESC_EEENS0_12InvokeHelperILb1EvSF_EEFvvEE3RunEPNS0_13BindStateBaseE
#23 0x7f14613da9ec base::debug::TaskAnnotator::RunTask()
#24 0x7f14613f4355 base::MessageLoop::RunTask()
#25 0x7f14613f4678 base::MessageLoop::DeferOrRunPendingTask()
#26 0x7f14613f483b base::MessageLoop::DoWork()
#27 0x7f14613cfcfa base::(anonymous namespace)::WorkSourceDispatch()
#28 0x7f145f0c5247 g_main_context_dispatch
#29 0x7f145f0c55e8 <unknown>
#30 0x7f145f0c567c g_main_context_iteration
#31 0x7f14613cfbd6 base::MessagePumpGlib::Run()
#32 0x7f146140b030 base::RunLoop::Run()
#33 0x7f14613f3b7a base::MessageLoop::Run()
#34 0x7f1463c88b9d content::GpuMain()
#35 0x7f14644ba257 content::ContentMainRunnerImpl::Run()
#36 0x7f14644b8d00 content::ContentMain()
#37 0x7f14612dfb03 CefExecuteProcess()
#38 0x7f1461283ba7 cef_execute_process
#39 0x0000004925c2 CefExecuteProcess()
#40 0x0000004212dd client::(anonymous namespace)::RunMain()
#41 0x000000421c07 main
#42 0x7f145e1f550a __libc_start_main
#43 0x00000040c849 <unknown>
  r8: 0000000000000000  r9: 0000000000000000 r10: 0000000000000000 r11: 0000000000000246
 r12: 0000000000000000 r13: 00007f1464ed67d9 r14: 000000000002813e r15: 00007ffe83e82120
  di: 0000000000000002  si: 00007f1464ed67d8  bp: 000000000000013e  bx: 0000000000000000
  dx: 0000000000000001  ax: 0000000000028000  cx: 000000000082813e  sp: 00007ffe83e82110
  ip: 00007f14643f1db3 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000082813e
[end of stack trace]
[0927/200315:ERROR:command_buffer_proxy_impl.cc(194)] Could not send GpuCommandBufferMsg_Initialize.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(199)] CommandBufferProxy::Initialize failed.
[0927/200315:ERROR:webgraphicscontext3d_command_buffer_impl.cc(218)] Failed to initialize command buffer.
getrlimit(RLIMIT_NOFILE) failed
```

**Comment by saurabh95** [comment] 2017-09-28 06:19
You can try to reinstall brackets using command `sudo dpkg -i <PATH_OF_DEB_FILE>`, it will list the dependencies which failed(there would probably be 1 or 2). You can then install those dependencies, and then launching Brackets should work fine.

**Comment by surajmandalcell** [comment] 2017-09-28 09:05
@saurabh95 i did reinstall, i complete uninstalled brackets and reinstalled the most recent version but still persists.

**Comment by narayani28** [comment] 2017-09-29 08:18
@mmmmmmbeer , @hnaparst , @kuboosoft - thanks for reporting this issue. In the current 1.11 release, we have started supporting Ubuntu(verified for version 16.04.3 LTS) and Debian(verified for version 9.1.0). In the future releases, we will add support and address the issues for other flavors of Linux.

**Comment by surajmandalcell** [comment] 2017-09-29 09:50
@narayani28 i cant just switch operating system just for the sake of 1 text editor, no thanks please comment when the issue is fixed.

**Comment by narayani28** [comment] 2017-09-29 10:33
@surajmandalcell - we will keep the community updated when the issue is fixed.

**Comment by Romane-T** [comment] 2017-09-30 02:43
As per the first post with the images. Seeing as I do use the menu a bit, this makes using this latest version problematic. Reverting till fixed.
Debian Testing, fully up to date.
Previous version of Brackets works just fine.
Have purged Brackets from my system, deleted every reference could find in a search of the file system, then re-installed. No change.
Re-downloaded the .deb file, re-installed .deb, no change. Install messages the same as with install after purge (except for over-writing bit):
> root@romane:/home/romane# dpkg -i /home/romane/downloads/Brackets.Release.1.11.64-bit.deb 
> (Reading database ... 197808 files and directories currently installed.)
> Preparing to unpack .../Brackets.Release.1.11.64-bit.deb ...
> Unpacking brackets (1.11.0-17524) over (1.11.0-17524) ...
> Setting up brackets (1.11.0-17524) ...
> xdg-icon-resource: size argument must be numeric
> Try 'xdg-icon-resource --help' for more information.
> Processing triggers for hicolor-icon-theme (0.17-1) ...
> 
Have tried changing fonts via the preferences file. Unknown what font Brackets is using in the editor, as the system I tried (about 6 or so) no change to the font in the editor. Previous version was fine.
Just guessing, looks like Brackets is not recognising system fonts, but what font **is** it recognising/using?
As per issue #13731, looked for libudev0 - not available in repositories.

**Comment by gacsnic** [comment] 2017-09-30 17:15
the libjavascriptcoregtk-4.0-18 package
is being retained in debian just like ubuntu, I see it has to do with javascript and gtk, does brackets depend on that package?

**Comment by sjrzc** [comment] 2017-09-30 20:27
Still same problem on **Ubuntu 17.10** even if I use `sudo dpkg -i <deb-package>` and there is no dependencies problem.
![brackets_ubuntu_17_10](https://user-images.githubusercontent.com/5620520/31049186-7ff44b36-a5f3-11e7-9933-b539f8694d15.png)

**Comment by nethip** [comment] 2017-10-01 09:44
Sorry for the inconvenience caused because of this bug. Our initial testing was restricted to 14 and 16 LTS versions. We will try to debug this issue on Ubuntu 17. I will update this thread once we have a solution.

**Comment by sjrzc** [comment] 2017-10-02 03:39
Thank You very much @nethip, I'll be wait to can use this great editor in this Ubuntu version.

**Comment by blendsoft** [comment] 2017-10-02 06:48
This bug appear in Debian testing too.

**Comment by abhih** [comment] 2017-10-04 11:58
I am using brackets on Kali linux with updated version and this issue is present still. I tried re-installing but the issue persists as of today i.e Oct 4,2017.

**Comment by tiago4171** [comment] 2017-10-04 13:47
Same here at Opensuse Tumbleweed

**Comment by kiroma** [comment] 2017-10-05 14:53
Same here with Kubuntu 17.10.

**Comment by Jeymz** [comment] 2017-10-12 00:05
Ubuntu Variant, POP OS having the same issue.

**Comment by Filthy-Commie** [comment] 2017-10-15 16:55
Same issue in Pop!_OS
![brackets-issue](https://user-images.githubusercontent.com/32339182/31587032-abd7b960-b19f-11e7-963b-620d9e0a55ad.png)

**Comment by surajmandalcell** [comment] 2017-10-16 07:57
@Filthy-Commie is it just me or the characters(rectangle-ish ones) on your screenshot are different than mine?

**Comment by darekmeco** [comment] 2017-10-16 08:02
Any progress on this ?

**Comment by Filthy-Commie** [comment] 2017-10-16 12:27
@surajmandalcell Does Brackets use the system font maybe?

**Comment by surajmandalcell** [comment] 2017-10-16 20:08
@Filthy-Commie maybe brackets is asking system for different font from language pack not installed currently. Could be some typo in the font name for the menu bar. No idea i dont have much time to investigate sorry.

**Comment by bici-zizi** [comment] 2017-10-17 09:28
Lighttable (another electron based text editor) has a similar issue:
https://github.com/LightTable/LightTable/issues/2343
It seems that they have already figured out the root cause.

**Comment by kiroma** [comment] 2017-10-17 12:39
I digged around and it seems to be a bug in either Chromium or GTK2.

**Comment by surajmandalcell** [comment] 2017-10-17 13:59
@bici-zizi accordint your cause its a chromium problem. @kiroma yes chromium i think it is

**Comment by kiroma** [comment] 2017-10-17 16:41
Unless I don't know how to use LD_PRELOAD properly, it's a bug in Chromium.

**Comment by TimothyJAsher** [comment] 2017-10-20 00:57
Any update on a fix yet? Ubuntu 17.10 is out of Beta as of today Brackets is still having this issue. Sad that no one from the Adobe team seems to care about it. I'll continue using Atom as I can't depend on a hit or miss team that doesn't value users suggestions / problems for their product.

**Comment by gacsnic** [comment] 2017-10-20 01:30
las librerias, libwebkit2gtk-4.0-37  version 2.18.1-1 and libjavascriptcoregtk-4.0-18 version 2.18.1-1  corrigen la falla del menu de brackets en debian sid

**Comment by gacsnic** [comment] 2017-10-20 03:40
failure persists after update

**Comment by Ramboush** [comment] 2017-10-24 12:01
Oh man, guess I will have to look for an alternative to Brackets, same problem here

**Comment by Romane-T** [comment] 2017-10-24 22:34
First, I am not a developer, merely another user. Just to put my 
comments into perspective.

There are a couple of alternatives (Atom, Code come to mind), but my 
personal experience is that they don't quite come up to scratch in small 
but, to me, quite irritating ways.

Easy solution - downgrade till this issue is fixed.

Just a personal opinion.

Romane

**Comment by narayani28** [comment] 2017-10-25 03:14
We are looking into this issue and will provide an update soon. We understand the seriousness of the issue and sorry for the inconvenience. 
- Adobe Brackets team

**Comment by bici-zizi** [comment] 2017-10-25 08:40
Thanks narayani28 for the feedback!

**Comment by FabioMojo** [comment] 2017-10-26 17:23
Same problem with ubuntu 17.10 and gnome 3.26.1 ...
I guess I'll have to downgrade too. Brackets is the only software causing such problem on my system right now. Hope there will be a fix soon !

**Comment by PanadeEdu** [comment] 2017-10-29 08:43
I confirm this issue as well with Ubuntu 17.10.

**Comment by itachikesh** [comment] 2017-10-31 05:31
Same issue in latest kali distro, please fix it asap. I love brackets

**Comment by kiroma** [comment] 2017-11-01 21:08
Thanks to @chsjr1996 we now know which package is responsible for the issue, I've pinpointed the commit to this: [https://git.gnome.org/browse/pango/commit/?id=906509e22bf617d97a71f41d335d7a0dec344187](https://git.gnome.org/browse/pango/commit/?id=906509e22bf617d97a71f41d335d7a0dec344187)
Which is slightly worrying for me, since it removes a deprecated way of displaying glyphs.
The PR made by @linxon works around the issue rather than resolving it by downloading an older version of libpangoft.

**Comment by mmmmmmbeer** [comment] 2017-11-02 18:12
Thanks to @chsjr1996's detective work, I was able to implement a similar workaround on Fedora 27. Since I also had the problem on F26 a few weeks back, I grabbed the F25 pango from rpmfind (pango-1.40.3-1.fc25.x86_64.rpm), extracted libpang* to /opt/brackets/, and success!

I imagine a similar approach would work for those on other distros experiencing this issue - try finding the pango libraries for your distro prior to the problematic commit identified by @kiroma, and extract to /opt/brackets/. Certainly worth a shot!

**Comment by pauledd** [comment] 2017-11-02 18:35
thanks @mmmmmmbeer , on gentoo I was able now to run brackets 1.11 from @hnaparst overlay by downgrading pango to 1.40.3. Now need to copy anything.

**Comment by MoonbiteAgency** [comment] 2017-11-07 06:25
In debian based dists, you can get libpango and libpangoft2 from stable ant put libs from them in /opt/brackets
https://packages.debian.org/search?keywords=libpango&searchon=names&suite=stable&section=all

```
#/opt/brackets$ ldd ./Brackets | grep pango
	libpangocairo-1.0.so.0 => /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0 (0x00007fad8727f000)
	libpango-1.0.so.0 => /opt/brackets/./libpango-1.0.so.0 (0x00007fad87033000)
	libpangoft2-1.0.so.0 => /opt/brackets/./libpangoft2-1.0.so.0 (0x00007fad83e5d000)

```

**Comment by Romane-T** [comment] 2017-11-07 10:54
My sincere appreciation. This worked for me (Buster). Running 1.11 *with 
menu's* at last.

**Comment by surajmandalcell** [comment] 2017-11-07 21:06
can they update the actual package now please, adobe

**Comment by kiroma** [comment] 2017-11-07 21:46
We're waiting for 1.12 to go live, it will contain the workaround, don't worry.

**Comment by TimothyJAsher** [comment] 2017-11-07 22:08
For anyone running Ubuntu 17.10 latest, I extracted the 4 files needed and zipped them up to make it easy for others. Just extract them and place them into your    ```/opt/brackets```    directory. I had 1.10 installed and placed the files in then upgraded and it works 100% menus and all. Thank's to all who helped solve this mystery!

[Extracted Libpango downloads for Ubuntu 17.10](https://www.dropbox.com/s/lvf8jrpnn6p7y45/Brackets%20Lipango%20Menu%20Fix.tar.xz?dl=0&m=)

**Comment by nethip** [comment] 2017-11-14 09:22
This is now fixed. The problem was with the version of CEF that we are using for the shell. We will update the S3 bucket with the updated CEF binary.

**Comment by kiroma** [comment] 2017-11-14 17:07
There's been a merged PR which worked around the bug by installing older version of libpango, will it be reverted?

**Comment by nethip** [comment] 2017-11-17 05:29
@kiroma I am not sure if we had any PR that targets reverting libpango to older version. AFAIK, it was just the workaround suggested by one of our community members.

**Comment by kiroma** [comment] 2017-11-17 10:22
Oh, I'm sorry, I misunderstood one of the notesade by github, I didn't know you could reference an issue from another repository.

**Comment by Handwrit** [comment] 2017-12-01 06:54
This is stupid. Why isn't there a 1.111 release, to fix this bug? It's a severe issue! It means it doesn't even work on Ubuntu.

**Comment by RustyRaptor** [comment] 2017-12-01 20:29
Ok, the fix above fixed the issue. Bless you, guys. Saved my life.

**Comment by DevPre** [comment] 2017-12-01 22:18
Thanks for the fix above. Managed to make it work on Fedora 27.

**Comment by nethip** [comment] 2017-12-08 09:25
Sorry for the inconvenience. 

Update on the Linux build: We are targeting Linux patch for  2 critical bugs w.r.t IME and font corruption.

1) IME: This was really challenging as IME was not implemented in CEF, so we had to patch lot of code from Chromium. We somehow got this fixed and now testing it extensively.
2) Font Corruption: This is fixed now. 

By next week we are planning to do a Linux refresh (if we don't find any more blockers in our testing).

**Comment by Romane-T** [comment] 2017-12-08 09:56
Good morning Prashanth

Thank you for the update. It is very much appreciated.

With warm greetings

Romane

**Comment by warrior-of-light** [comment] 2017-12-15 04:24
Same issue persists for Debian buster/sid also.

**Comment by kiroma** [comment] 2017-12-15 09:33
A 1.12 prerelease for Linux is now live and it addresses this bug.

**Comment by nethip** [comment] 2017-12-15 11:10
Thanks for update the thread @kiroma. Please try out the pre-release build and give us the feedback!

**Comment by nethip** [comment] 2017-12-15 11:13
We have uploaded a pre-release build (Linux 64 only) to address this issue. Please try the build and let us know your feedback. You can download the build from https://github.com/adobe/brackets/releases/tag/release-1.12-prerelease.

**Comment by nethip** [comment] 2017-12-21 08:40
We now have updated the installers for Linux 32 and 64 bit. Please download the same from http://brackets.io. Thanks!

**Closed by nethip** 2017-12-21 08:40 UTC
Labels: Linux only
