### ISSUE TITLE
Fix visual indentation on word-wrapped rows

### ISSUE THREAD

**Issue by Reedyn** [adobe/brackets#6071] opened 2013-11-21 13:05 UTC
**Indentation isn't visually correct in the editor when using word-wrap.**

How it is currently
![](http://img.gustavlindqvist.se/20131121130223224.jpeg)

How it should be *(example from Notepad++)*
![](http://img.gustavlindqvist.se/20131121130303481.jpeg)

Tested on Windows 8, using **sprint 33 experimental build 0.33.0-10188 (On branch sprint-33-hotfix,sprint-33-hotfix b4c74d953)**

**Comment by OKNoah** [comment] 2015-01-29 10:33
This is definitely a much-needed feature in Brackets.

**Comment by peterflynn** [comment] 2015-01-30 00:59
Closing since it turns out this is a duplicate of an item that's already tracked on our feature backlog: [Word Wrap - Indentation](https://trello.com/c/8kLCZrsO/974-word-wrap-indentation).

@Reedyn and others above who've requested this -- please upvote that backlog item to raise its priority.  Also check out the extension linked above (https://github.com/scriptin/brackets-indent-softwraps) and see if it works well for you in the meantime.  I'll add that link to the backlog item too, and ping the extension's author about adding it to the official extension registry (it doesn't appear to be uploaded there yet).

**Closed by peterflynn** 2015-01-30 00:59 UTC
Labels: move to backlog
