### ISSUE TITLE
bad performance with code folding

### ISSUE THREAD

**Issue by didiraja** [adobe/brackets#12444] opened 2016-05-22 21:17 UTC
I use Brackets release 1.11 on my personal computer with Win7 x64. When I updated to get new features, the versions 1.15 e 1.16 turns out with a problematic delay while typing. This part, I know that is normal for some users.

So I downgraded back to 1.11. But, code folding is an important feature, so, I installed the plugin (the same that was posteriorly incorporated to official release). After that, the release that was so nice on my computer went bad.

This is more a suggest than an issue report: Maybe is not just it, but, maybe the problem is with the code folding plugin.

**Comment by ficristo** [comment] 2016-06-13 10:20
You could try to tweak the preferences for `code-folding`:
https://github.com/adobe/brackets/wiki/How-to-Use-Brackets#list-of-supported-preferences
For example you could try changing `code-folding​.saveFoldStates` to `false` and see if Brackets does any better (of course loosing the ability to save the code folding state).

Other thing: is it slow for every file, or only if there are a lot of code folding markers?

/cc @thehogfather the original author of the plugin, maybe he has some ideas.

**Comment by thehogfather** [comment] 2016-06-13 22:20
most of the time I would say if you've traced performance issues down to code folding, it might be because of the preference to saveFold states. Saving and reloading fold states can be expensive on large files (particularly if one has collapsed all fold regions in a large file).

I would suggest trying @ficristo's suggestion of disabling the `saveFoldStates` preference. That might make some difference.

**Comment by lkcampbell** [comment] 2017-04-04 21:06
@thehogfather, I'm having this problem as well, so I tried setting `code-folding.saveFoldStates` to `false` and I ran into issue #13264 that I just filed.

**Comment by lkcampbell** [comment] 2017-04-07 01:12
@didiraja if you are running a development build of Brackets, @thehogfather just fixed the problem with `saveFoldStates`. Update your build and try setting it to `false` now and see how it works.

If not, should be fixed in next release.

As for me, it fixes everything.

@thehogfather I have a solid repro of the code folding performance problem, I will file the bug this weekend. I don't really need the fix given that you gave a great workaround, but it would b nice to solve it once and for all, agreed?

**Comment by thehogfather** [comment] 2017-04-07 06:23
@lkcampbell agreed.

**Comment by lkcampbell** [comment] 2017-04-07 13:23
@thehogfather filed the new performance issue #13282.

**Comment by lkcampbell** [comment] 2017-04-26 00:29
@didiraja, there is a second performance fix for cold folding, which will be available for version 1.10.

Since no steps were provided to reproduce this issue, I am going to assume that either using the workaround of setting `code-folding.saveFoldStates` to `false`, and/or the new performance fix, will fix your performance problems. I am closing this issue as fixed.

If this is not the case, and you can provide some steps to reproduce your issue, free feel to reopen this issue so we can investigate it further.

**Closed by lkcampbell** 2017-04-26 00:29 UTC
Labels: F Code Folding
