### ISSUE TITLE
Problem with saving html files

### ISSUE THREAD

**Issue by marek8623** [adobe/brackets#12756] opened 2016-09-06 07:47 UTC
Hi everyone,

I have problem with saving html files. If I want to save a file I need to click on another file on the left side and then brackets will save the opened file.

Thank you for your response.

**Comment by ficristo** [comment] 2016-09-06 18:04
Can you reproduce with `Debug \ Reload Without Extensions`?
If so, could you give us the exact steps to reproduce?
For example are you trying to save an existing file or one created with `Ctrl+N`?

**Comment by ficristo** [comment] 2016-12-03 15:50
Closing since there was no answer.
If you still have problems, please, open a new issue.

**Closed by ficristo** 2016-12-03 15:50 UTC
Labels: Waiting for user
