### ISSUE TITLE
Keyboards Shortcuts only active on first open window

### ISSUE THREAD

**Issue by RoryPicko** [adobe/brackets#10968] opened 2015-04-22 09:15 UTC
If you open a new brackets window, you cannot use any keyboard shortcuts within the newly opened window, even CTRL+(C+V+X) etc... but they still work on the initial window.

I love brackets and think it's by for the best IDE IO have tried but the inability to have a smooth workflow when working within 2 folders is frustrating!

**Comment by peterflynn** [comment] 2015-04-22 23:37
This is a duplicate of #8135 -- one of several important reasons to avoid using this unofficial testing feature.  See notes in the original bug for details.

For now, your best option is to you the Recent Projects dropdown to quickly switch between project folders.  (Or open the parent folder of the two folders you're using, if possible).

**Closed by peterflynn** 2015-04-22 23:37 UTC
