### ISSUE TITLE
CSS: background-blend-mode highlights as incorrect property

### ISSUE THREAD

**Issue by torvalamo** [adobe/brackets#11683] opened 2015-09-10 13:27 UTC
Does for some reason not show as a valid css property, despite being in the config file (added last year as far as I could tell) and the code hinting list both for property and allowed values to it.

Other 3-part properties (such as `column-rule-color`) highlight just fine, so it's not a parsing issue at least, but `background-blend-mode` just doesn't get the acceptance he desires. #foreveralone

**Comment by ficristo** [comment] 2015-09-10 18:50
I tried with a empty test.css file and a .foo class.
Brackets highlights the `background-blend-mode` itself correctly and show the code hinting for the allowed values which aren't highlighted apart the values `normal` and `overlay`.
If I change the language to SCSS or LESS Brackets highlights the name itself correctly but do not shows the code hint for the values.
This was on master.

**Comment by torvalamo** [comment] 2015-09-10 18:59
Release 1.4 build 1.4.0-16380 (release 273804eb3) 
build timestamp: Mon Jul 27 2015 07:23:52 GMT+0100

**Comment by ficristo** [comment] 2015-12-26 19:45
I tried adding a `foo` property to CSSProperties.json with one value: `bar`.
The property were in the autocomplete but not the value.
Maybe the underline problem is the same?

/cc @MarcelGerber @sprintr in the hope they know more :smile:.

**Comment by sprintr** [comment] 2015-12-26 20:31
@ficristo It has to be defined in the codemirror's css mode. I'll put up a PR up there in a while. Should be in Brackets 1.7.

**Comment by sprintr** [comment] 2015-12-26 21:17
@ficristo @torvalamo The upstream PR is https://github.com/codemirror/CodeMirror/pull/3740

**Comment by ficristo** [comment] 2015-12-27 08:36
@sprintr Thank you for looking into it!

**Comment by sprintr** [comment] 2015-12-28 14:07
@ficristo @torvalamo The fix for this has landed in CodeMirror.

**Comment by abose** [comment] 2016-02-01 03:06
Tracking to verify on CM update.

**Comment by ficristo** [comment] 2016-05-03 13:46
Now that CodeMirror update has landed it is fixed. (I could not reproduce the problem of syntax highlighting on plain CSS, however on LESS, SCSS now the code hints come up correctly)
@abose @MarcelGerber can we close this?

**Comment by MarcelGerber** [comment] 2016-05-03 16:55
Thanks for the heads up!
Closing.

**Closed by MarcelGerber** 2016-05-03 16:55 UTC
Labels: fixed but not closed, tracking
