### ISSUE TITLE
Installer doesn't satisfy dependencies

### ISSUE THREAD

**Issue by javiersanchezmza** [adobe/brackets#12294] opened 2016-03-12 03:13 UTC
Hello: I am on kubuntu 15.10 64 bits. I tried brackets 1.6 and 1.5, with and without extract. Reults are always the same, I get an error that it doesn't satisfy dependencies and thus I can't install it. Trying from the repo, I see Brackets but it won't "find it" when you choose to install it.

Any clues?

**Comment by petetnt** [comment] 2016-03-12 20:18
Most like related to https://github.com/adobe/brackets/issues/10255

**Comment by javiersanchezmza** [comment] 2016-03-15 15:01
Probably, but that is not something good, since that has been there for a year or more, probably. I didn't pay attention to the dates but I did notice that people keeps reporting it once and again and I don't see any clear intention of fixing it. It concerns me a lot because I really wanted to try brackets out.

**Comment by ficristo** [comment] 2016-08-07 17:57
Closing as duplicate of https://github.com/adobe/brackets/issues/10255

**Closed by ficristo** 2016-08-07 17:57 UTC
