### ISSUE TITLE
Text continues underneath right sidebar

### ISSUE THREAD

**Issue by Orcinuss** [adobe/brackets#12890] opened 2016-11-10 04:04 UTC
### Description
When 'Word Wrap' is NOT enabled and the line is very long, the text will continue below the right hand sidebar (the now that holds the live preview and extension manager buttons). Horizontal scroll does not scroll all the way and a few characters are cut off as I believe they are underneath the right sidebar.

### Steps to Reproduce
1. Turn off Word Wrap
2. Write long line of code (ex. array of strings)

**Expected behavior:**
Horizontal scroll should scroll to the end of the line and no text should be underneath/hidden by GUI elements.

**Actual behavior:**
Text is underneath right sidebar and horizontal scroll does not scroll all the way to the right.
<img width="217" alt="brackets no wrap error" src="https://cloud.githubusercontent.com/assets/7836002/20164223/afd19d90-a6b7-11e6-869c-841d8fe65325.png">

### Versions
Mac OS Sierra - 10.12.1
Brackets - Release 1.7 build 1.7.0-16898 (release b0a363b71)

**Comment by Orcinuss** [comment] 2016-11-11 06:23
Still broken as of version: Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4)

**Comment by ficristo** [comment] 2016-11-16 19:21
It seems a dupe of https://github.com/adobe/brackets/issues/12797
Can you try to create a new file with only that line of code and see if you can still reproduce?
Can you also try to reproduce on https://codemirror.net/ ?

**Comment by Orcinuss** [comment] 2017-01-12 00:24
@ficristo This issue seems to have been fixed. No issue in a new file or on https://codemirror.net/. No issue in original file either.

**Comment by ficristo** [comment] 2017-01-15 18:21
Merging this on with #12797

**Closed by ficristo** 2017-01-15 18:21 UTC
Labels: Waiting for user
