### ISSUE TITLE
Error when upload an extension 

### ISSUE THREAD

**Issue by rrandom** [adobe/brackets#11943] opened 2015-11-21 04:02 UTC
error message: `An error occurred, but unfortunately I don't know how to say this nicely: EACCES, mkdir '/home/aboutweb/tmp/bracketsPackage_1151020-12803-zpz3p5'`
I think I have the valid package.json and main.js. Any ideas?

**Comment by petetnt** [comment] 2015-11-21 11:43
Duplicate of #11932, there seems to be an fix coming

**Comment by abose** [comment] 2015-11-22 04:24
closing duplicate

**Closed by abose** 2015-11-22 04:24 UTC
