### ISSUE TITLE
Color highlighting comressed javascript

### ISSUE THREAD

**Issue by svenvNL** [adobe/brackets#10509] opened 2015-02-02 16:22 UTC
I was writting an script wich removes comments, enters and reduces the extra spaces to one space. When I opend the file, color highlighting stoped somewere in the middle.
![screen](https://cloud.githubusercontent.com/assets/6967046/6003955/d66326dc-aaff-11e4-8f35-e45ec2e68788.png)

My code is vallid following jslint. When i use an beautify extension, highlighting comes back for the whole file.

I am running windows 7 home primium with Brackets 1.1

**Comment by peterflynn** [comment] 2015-02-02 22:50
This is a duplicate of #9007, though that was closed.  This is a performance-based limitation of CodeMirror when lines are more than 10,000 characters long.

**Comment by svenvNL** [comment] 2015-02-03 15:14
@peterflynn 
Thank you for your quick repley. I saw on the codemirror site that we can disable the 10,000 characters limitation and set it to infinnety. Maybe we can make an otion in the brackets.json file so that people with an high end computer can set the limitation to another value???

Sven

**Comment by MarcelGerber** [comment] 2015-02-03 15:59
@svenvNL Notice though that Brackets isn't meant to edit minified files and it can cause strange problems.
It's usually better (both for you and the editor) to edit the development version of the file and then minimize it into the production file. You can do that using a grunt task, for example.

**Comment by peterflynn** [comment] 2015-02-03 21:41
It's probably risky to make the character limit configurable -- usually things like that don't speed up with better hardware as much as you might expect, and then it still feels like a bug.  You could experiment with it by [editing the source locally](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets#quick-start), though.

The best solution is to just fix the issue: make CodeMirror actually highlight long lines fully (just like it highlights long documents), which requires breaking the line processing (highlighting, layout, etc.) into sub-segments.  The CodeMirror maintainer, Marijn, has said this is complex enough that he's not going to do it unless someone specifically funds the effort.  It's a big-ticket item -- hence the 'move to backlog' label.

**Comment by svenvNL** [comment] 2015-02-04 14:27
@peterflynn, @MarcelGerber thank you for your repley, as I read your answer, we can't make it work in Brackets directly, so I'm going to close this issue.

**Closed** 2015-02-04 14:27 UTC
Labels: codemirror, move to backlog
