### ISSUE TITLE
High-DPI text rendering

### ISSUE THREAD

**Issue by NickDarvey** [adobe/brackets#10476] opened 2015-01-27 22:16 UTC
I have a Surface Pro 3 which has a 216dpi screen (set as primary) and an external monitor at 92dpi (secondary).
I'm not sure if the attached screenshot does this justice, but the text rendering on the high-DPI screen looks very poor (not crisp, blurry). Most apps look great across both screens and some have the same issue on my secondary monitor, but Brackets is the only one that has the issue on my primary monitor (and looks fine on the secondary).

![dpi](https://cloud.githubusercontent.com/assets/6076697/5928219/1f86aa58-a6c5-11e4-9956-91834775840b.jpg)
_Primary monitor on left, secondary monitor on right._

**Comment by peterflynn** [comment] 2015-01-27 23:01
Closing as a duplicate of #10178

**Closed by peterflynn** 2015-01-27 23:01 UTC

**Comment by NickDarvey** [comment] 2015-01-27 23:11
@peterflynn - sorry!

**Comment by peterflynn** [comment] 2015-01-27 23:55
No worries!
