### ISSUE TITLE
Feature Request: Option to disable warnings when projects aren't found.

### ISSUE THREAD

**Issue by MrSpecific** [adobe/brackets#12227] opened 2016-02-17 21:43 UTC
I love Brackets, and use it constantly. I also use Transmit FTP to mount my sites as local disks. This works great, but when I switch between projects (and unmount those mounted discs), Brackets always pops up an error dialog telling me that it can't find the project any more. That's probably fine for people using local files only, but it's annoying for users like myself who work on remote files. If we could just disable those warnings, or even had them more subtle, and not have to close them every time, that would be great!

**Comment by abose** [comment] 2016-02-22 06:58
Alerting the user that the project path doesn't exist on disk/ cannot be located looks like a valid use case to me. If we suppress these messages, then unsuspecting users will not be able to get what went wrong. 
If you like to alter the behavor, goto `src/widgets/Dialog.js` in the brackets source and modify the `showModalDialog` part or do a more targeted change.
Closing as expected behavior/ edge case.

**Closed by abose** 2016-02-22 06:58 UTC
