### ISSUE TITLE
Problems with Brackets while coding with jsx

### ISSUE THREAD

**Issue by HienNguyen711** [adobe/brackets#13058] opened 2017-01-22 18:01 UTC
I am using Brackets 1.7 on Window 7 and everything seems to be ok when I start a jsx file. I am coding and then it suddenly ran into this problem. It showed nothing but actually there was code there, I cannot type anything.

![2](https://cloud.githubusercontent.com/assets/18014965/22184589/4ad564de-e0dd-11e6-9b81-87318570a856.PNG)

The code disappeared without informing any thing when I open jsx file
![1](https://cloud.githubusercontent.com/assets/18014965/22184603/93a0000c-e0dd-11e6-9df4-13bd94f3f783.PNG)

But then I open other file, it was like this

Please help, if someone can fix this problem.

Thank you so much.

**Comment by swmitra** [comment] 2017-01-23 06:09
@HienNguyen711 can you please check if you can find any console errors and paste them here? This looks like a problem with the editor container. The editor is not destroyed properly.  Also please let us know the list of extensions what you are using.

**Comment by HienNguyen711** [comment] 2017-01-23 13:24
@swmitra 
Here is the list of extensions: 
https://paste.ubuntu.com/23851873/
About console errors, there are so many errors, sorry I do not know how to get the right format for you to easy to look.
https://paste.ubuntu.com/23851894/
thank you so much for help!

**Comment by swmitra** [comment] 2017-01-24 03:20
@HienNguyen711 Thanks for sharing the logs.  To me it looks like one of the extensions have created a container which has misplaced editor container. I suggest you do the following - Reload brackets without extensions and see if you can reproduce the problem. If you are unable to then it's probably a problem caused by some extension and in order to pin down that extension, disable the extensions what you think could manipulate the DOM. Do this until you can narrow down to a single extension.

**Comment by HienNguyen711** [comment] 2017-01-24 14:55
@swmitra : Hi, reload without extensions seems to work. So, what should I do next? Should I try to find the extensions that could manipulate the DOM? And what is a better way you can suggest to find the exact extensions that cause this ?

**Comment by swmitra** [comment] 2017-01-24 15:22
One surprising thing,  why react_jsx is listed twice.  That might be a concern.

**Comment by ficristo** [comment] 2017-04-01 17:02
Closing as it seems a problem with the extensions.

**Closed by ficristo** 2017-04-01 17:02 UTC
Labels: Waiting for user
