### ISSUE TITLE
Writing CoffeeScript into a .js file hangs the editor

### ISSUE THREAD

**Issue by ile** [adobe/brackets#11159] opened 2015-05-24 03:02 UTC
It really does, at least here on Windows 7/64bit and Release 1.3 build 1.3.0-16022. Have to use the task manager to kill the processes.

It may be because of linting.

**Comment by busykai** [comment] 2015-05-24 04:08
@ile, could you try selecting *Debug -> Reload without extensions* and see if it reproduces?

**Comment by MarcelGerber** [comment] 2015-05-24 10:41
It would also help if you could share your CoffeeScript source with us. In case you can't, can you perhaps try reducing your code to a specific pattern that causes Brackets to crash, or just try to make it crash with some openly available code.

**Comment by ile** [comment] 2015-05-27 19:52
Sorry for the delay, I was editing a bunch of files and I didn't want to lose the "editing history".

This code seems to do what I reported:

```coffeescript
class X
	moi: -> 'terve'
```
.. and then saving as test.js for example.

Of course writing CoffeeScript into a .js file doesn't make much sense, it was a mistake originally.

Reloading without extensions didn't help.

**Comment by MarcelGerber** [comment] 2015-05-27 20:31
I can repro the issue, too, with extensions loaded at least.
For me, it seems to be caused by the JSHint extension (cc @cfjedimaster)

**Comment by cfjedimaster** [comment] 2015-05-27 21:31
My code is very much just a wrapper to the JSHint lib. If you can recreate it on jshint.com, then it would definitely be the library.

**Comment by MarcelGerber** [comment] 2015-05-29 16:10
You are right. I can indeed repro this in a locally installed version of jshint. It simply never finishes.
Will report it with them.

**Comment by MarcelGerber** [comment] 2015-05-29 16:19
Filed as jshint/jshint#2421.

Closing this as extension problem anyways. Hopefully it'll get fixed soon.

**Closed by MarcelGerber** 2015-05-29 16:19 UTC
Labels: extension problem, Waiting for user
