### ISSUE TITLE
Brackets Hotkey for 2-windows on Windows

### ISSUE THREAD

**Issue by IDrakon** [adobe/brackets#11176] opened 2015-05-28 07:05 UTC
*Brackets 1.3.0-16022 (win)

Периодически перестают работать все горячие клавиши в Brackets под ОС Windows если одновременно открыто 2 окна Brackets и в них выполняют перезагрузку по клавише F5 одновременно.

**Comment by JeffryBooher** [comment] 2015-06-08 17:43
From google translate: Periodically stop working all hotkeys in Brackets under Windows if both open 2 windows Brackets and resets them by pressing F5 at the same time.

**Comment by JeffryBooher** [comment] 2015-06-08 17:49
@IDrakon thanks for filing.  I assume you are doing this with "Debug > New Brackets Window" which is a known issue and a duplicate of #8135. Having multiple Brackets windows open at one time is an experimental feature.  

Since you are running on Windows you could just launch a second instance of Brackets.  We don't restrict the number of concurrent instances that can run at once but, unfortunately, the architecture isn't designed to handle multiple windows in the same process.

**Closed by JeffryBooher** 2015-06-08 17:49 UTC
