### ISSUE TITLE
Brackets takes over Ubuntu

### ISSUE THREAD

**Issue by mchogan** [adobe/brackets#10361] opened 2015-01-12 22:21 UTC
![brackets-error-ubuntu](https://cloud.githubusercontent.com/assets/610349/5711136/fb299126-9a5c-11e4-83d3-5f408343c421.png)

## Issue
The attached screenshot illustrates the issue. When Brackets is open, it remains in the foreground even after another application has been selected (in the screenshot, I've selected Chromium). This makes Brackets unusable on Linux. I also use Brackets on Mac OS X and cannot reproduce the issue there.

## Steps to reproduce
1. Open Brackets.
2. Open another application.
3. Brackets will remain in the foreground, obstructing other applications and the GUI.

## Configuration
Brackets Release 1.1 experimental build 1.1.0-15558 (release ea908cae5)
Ubuntu 14.04.1 LTS (trusty)

**Comment by peterflynn** [comment] 2015-01-12 23:04
@mchogan are you running inside a VirtualBox VM?

**Comment by mchogan** [comment] 2015-01-13 00:52
Yes.


On Jan 12, 2015, at 3:07 PM, Peter Flynn <notifications@github.com> wrote:

@mchogan <https://github.com/mchogan> are you running inside a VirtualBox
VM?

—
Reply to this email directly or view it on GitHub
<https://github.com/adobe/brackets/issues/10361#issuecomment-69664931>.

**Comment by Mark-Simulacrum** [comment] 2015-01-13 00:58
Have never had any issues of with Brackets not being put into the background. Have used Brackets on Brackets 14.04 and 14.10 64bit, (non VirtualBox VM). @mchogan Is your Ubuntu 64bit or 32bit?

**Comment by peterflynn** [comment] 2015-01-13 01:45
@mchogan Thanks for clarifying -- that means this issue is a duplicate of #6145 though, so I'll close this copy.

**Closed by peterflynn** 2015-01-13 01:45 UTC

**Comment by peterflynn** [comment] 2015-01-13 01:52
Note that we think this may be fixed soon though -- comments in https://github.com/adobe/brackets/issues/6427#issuecomment-65735828 indicate that newer versions of CEF do not cause the problem, and we're trying to get a newer version working on Linux (our Mac and Win builds have already upgraded).  If you know anyone you could help, please point them here: https://groups.google.com/forum/#!topic/brackets-dev/QkYuQuCsqdY.

**Comment by mchogan** [comment] 2015-01-13 03:22
Thank you for the follow up. Looking forward to the fix.

I've really enjoyed Brackets over the past year. The fact I can use it on Windows, Mac, and Ubuntu has been very helpful on boarding team members in a bring your own device environment.

**Comment by peterflynn** [comment] 2015-01-13 09:16
Cool, glad to hear it!
