### ISSUE TITLE
Working set refreshed when selecting working set item

### ISSUE THREAD

**Issue by mseiler025** [adobe/brackets#11978] opened 2015-12-06 10:28 UTC
I am using Brackets 1.5 on Windows 10, but I think this affects all versions.

When user clicks/selects an item in the working set, the working set is refreshed.  I don't think that the working set should be refreshed in this case.

I believe this is happening because of line 779 (in the function ```drop()```) in WorkingSetView.js.  The line is ```postDropCleanup();``` but I think the line should be ```postDropCleanup(true);```

The working set is also refreshed when user closes/middle clicks an item in the working set.  I think this is caused by line 770 in WorkingSetView.js.

**Comment by abose** [comment] 2015-12-07 11:40
We refresh it by design. Does it cause any problems when the working set is refreshed?

**Comment by mseiler025** [comment] 2015-12-07 20:38
@abose It is only causing a small issue for me but I didn't think the working set needs to be refreshed every time you click on/select another item.

The problem for me is that I am working on an extension that uses WorkingSetView addIconProvider().  This works fine except every time another item is clicked on/selected there is a small visual glitch/delay when the icon is redrawn.  You may not be able to notice it on a faster computer but on mine you can.  The extension uses uses a NodeDomain exec() within the icon provider callback which I know is causing a delay but I'm not sure how to do it differently since I need information that I can only get from a NodeDomain (a file's mode).

As for the working set being refreshed when you close/middle click on an item, that is not my main concern but I noticed that also so I thought I would mention it.

**Comment by mseiler025** [comment] 2015-12-07 21:42
I think I may have found a solution for my problem, working on it now, will report back.

**Comment by abose** [comment] 2015-12-08 10:15
Closing as designed.

**Closed by abose** 2015-12-08 10:15 UTC
Labels: Waiting for user
