### ISSUE TITLE
Allow selection of file type, for new untitled files.

### ISSUE THREAD

**Issue by wyattbiker** [adobe/brackets#12451] opened 2016-05-24 12:38 UTC
I don't know why the file type selection is disabled for new untitled files (see attached). So many times I paste in xml or json in to a new empty file, and want to just beautify it without saving it first. Why do I have to first save it if I plan to discard it. Can it be fixed?
![disabledfiletype](https://cloud.githubusercontent.com/assets/930478/15503991/c4493db2-218a-11e6-9184-1b3bf95157da.png)

**Comment by petetnt** [comment] 2016-05-25 07:52
There's a long running Trello card for this here: https://trello.com/c/CNXuU4TY/1369-switch-language-type-of-untitled-documents

**Comment by ficristo** [comment] 2016-11-24 19:10
Dupe of #11637

**Closed by ficristo** 2016-11-24 19:10 UTC
