### ISSUE TITLE
Mode-Aware Styles in Dreamweaver Integration

### ISSUE THREAD

**Issue by WebSpectrum** [adobe/brackets#12883] opened 2016-11-08 20:44 UTC
I'm trying to get mode-aware styles working in Dreamweaver, in Brackets I just add "addModeClass": true to json and some example css like below to color PHP blocks

 .cm-m-css.clike {
    color: #6c9ef8;
}

However this doesn't work in Dreamweaver, just need to clarify if it's possible and how is it done in an embedded brackets? How does the CSS differ? ..... Thank you

**Comment by ficristo** [comment] 2017-01-02 07:49
Dupe of #13013
Usually I close the recent one but in this case maybe you have more luck to receive an answer in the recent one.

**Closed by ficristo** 2017-01-02 07:49 UTC
Labels: needs Adobe action
