### ISSUE TITLE
Tab key not working

### ISSUE THREAD

**Issue by deafninja** [adobe/brackets#10568] opened 2015-02-11 03:51 UTC
Environment:
- iMac OS X Yosemite
- Brackets Release 1.1 build 1.1.0-15558 (release ea908cae5)

When in a file (HTML, CSS or JS), I try using the tab key to create a tab space for code indentation however nothing happens.  The tab does nothing that the cursor stays where it is.  I opened textedit and tried within there and my tab key works as it should.  However in Brackets, it is not!

**Comment by peterflynn** [comment] 2015-02-11 09:16
Do you have any extensions installed?  Try _Debug > Reload Without Extensions_ to make sure that's not the cause.

**Comment by amatzen** [comment] 2015-02-11 22:44
If you have Bootstrap Snippets (by edc) or another plugins that has an "Update" button in Brackets you can't click. Then reinstall the plugin, you will still have the snippets and the Tab key works again!

- Tell me if it works ;)

**Comment by peterflynn** [comment] 2015-02-11 22:46
@amatzen If you're experiencing issues where the Update button in Extension Manager can't be clicked, could you please file a new bug about that? We'd want to investigate that issue too.

**Comment by deafninja** [comment] 2015-02-12 03:32
That is what did it.  

First did the Debug > Reload Without Extensions and the tabbing worked.
Then revert back to the Debug > Reload With Extensions and the tabbing stopped working.  
Went into Extension Manager > installed and the following Extension showed a disabled "Update" button
    "Brackets Snippets (by edc) Edward Chu
Removed the extension and tabbed worked
Reinstalled extension and now tabbing is working WITH the extension installed.

Thank you both for suggestions and troubleshooting the fix

**Comment by peterflynn** [comment] 2015-02-12 09:33
@amatzen @deafninja If you see the disabled Update button again, could you hover over it and see what the tooltip says?  Also try closing Extension Manager, then select _Debug > Show Developer Tools_ and check the Console tab for errors.  If you're able to gather any of that info, please file a new bug so we can investigate.

Closing this one since the original problem with the Tab key is resolved, however.

**Closed by peterflynn** 2015-02-12 09:33 UTC
Labels: extension problem
