### ISSUE TITLE
Black window title with latest brackets-shell

### ISSUE THREAD

**Issue by FezVrasta** [adobe/brackets#11770] opened 2015-10-03 11:22 UTC
I have compiled the latest bracket-shell release (https://github.com/adobe/brackets-shell/commit/1dec5811bf295f0e668f04e2359e22d87f723513) on my OS X El Capitan.
I've linked to it the files of Brackets 1.6 dev.

The window title is black but it should be white:

![image](https://cloud.githubusercontent.com/assets/5382443/10262646/c99aab96-69d1-11e5-981e-a7bab41f622b.png)

**Comment by ficristo** [comment] 2016-08-17 16:17
@nethip I think this is fixed with the latest release

**Comment by ficristo** [comment] 2016-11-03 17:30
I close this since I cannot reproduce.

**Closed by ficristo** 2016-11-03 17:30 UTC
Labels: Mac only
