### ISSUE TITLE
extension manage window isn't draggable?

### ISSUE THREAD

**Issue by linuxjd** [adobe/brackets#10741] opened 2015-03-14 08:54 UTC
In the latest brackets, I cannot drag the extension manage.When the brackets is not  maximized,I cannot see all the manage window and the close button in the lower right.

**Comment by prksingh** [comment] 2015-03-16 06:15
Do you mean, you can't drag the extension manager window. I am not sure if we could drag this in earlier versions even. I just tried a really old version of brackets (V0.38 on Mac mavericks) and could not drag the extension manager window.

Also the close button issue not being visible, is that a duplicate of bug #10728 ?

**Comment by peterflynn** [comment] 2015-03-16 06:28
@linuxjd How big is the window size you normally use for Brackets?  If your window is at least 760x513, you should be able to see all of the Extension Manager dialog...

**Comment by Equinox** [comment] 2015-05-05 10:17
I think adding something like [this](https://github.com/dnbard/brackets-draggable-modals) extension into Brackets by default (like you guys did with the code folding) would be a good idea. It'd fix issues like this one and the one @prksingh linked.

**Comment by ryanstewart** [comment] 2015-05-05 10:45
I'm going to go ahead and close this because it's not something we're planning on changing. Since the extension is there to make them draggable, that seems like a good workaround.

I *think* the rendering issues are something that we'll be fixing in an update so hopefully that will alleviate the need to drag.

**Closed by ryanstewart** 2015-05-05 10:45 UTC
