### ISSUE TITLE
Brackets 1.9, can't configure my theme font

### ISSUE THREAD

**Issue by AgamlaRage** [adobe/brackets#13232] opened 2017-03-27 09:16 UTC
Brackets 1.9, Windows 10

I have to setup my font-family again, each time I quit Brackets.

Here the related part of my **AppData/Roaming/Brackets/brackets.json**, that is valid json.

>     "fonts.fontSize": "15px",
>     "fonts.fontFamily": "Liberation Sans",

My theme configuration is the same as my configuration in Brackets 1.8.
i did the normal update, running **Brackets.Release.1.9.msi**
It should works ...

**Comment by clementi** [comment] 2017-03-27 15:35
This appears to be the same as #13221

**Comment by AgamlaRage** [comment] 2017-03-27 17:55
Oh yes, sorry for duplicate :(

**Comment by ficristo** [comment] 2017-03-27 18:11
Closing as a dupe of https://github.com/adobe/brackets/issues/13221

**Closed by ficristo** 2017-03-27 18:11 UTC
