### ISSUE TITLE
Brackets 1.7 Git plugin do not work

### ISSUE THREAD

**Issue by saobangpro2991** [adobe/brackets#12519] opened 2016-06-14 02:43 UTC
I has upgrade from 1.6 to 1.7 but Git plugin can not work (don`t show brand and icon in right navigation not work)

**Comment by petetnt** [comment] 2016-06-14 07:48
Hi @saobangpro2991,

check out https://github.com/zaggino/brackets-git/issues/1300 in the `brackets-git` repository for future updates on when the issue is fixed

**Comment by nethip** [comment] 2016-06-14 11:28
@saobangpro2991 We are currently looking at it. Sorry for the inconvenience. We should be able to fix this and refresh the build in a day or two.

**Comment by nethip** [comment] 2016-06-17 10:24
There was an issue with 1.7 Linux 64 builds. It was to do with brackets unable to connect to Node. We have now fixed the problem and refreshed the builds. Could you download the Linux 1.7 builds again from brackets.io and check?

**Comment by ficristo** [comment] 2016-08-02 10:38
@saobangpro2991 if you are still experiencing issues with `brackets-git` is better to open first an issue on the extension repository.

**Closed by ficristo** 2016-08-02 10:38 UTC
