### ISSUE TITLE
"New File" should create item at top level when invoked from context menu on project tree background

### ISSUE THREAD

**Issue by njx** [adobe/brackets#10355] opened 2015-01-12 16:52 UTC
1. Open a project with multiple subfolders
2. Open a file in one of the subfolders
3. Right-click on the background of the project tree (below the last item) and choose New File

Result: The file is created in the same folder as the currently open file. It should instead be created at the top level (otherwise there's no way to create a file at the top level, since you can't select the root folder).

**Comment by redmunds** [comment] 2015-01-12 17:20
I agree with this issue, but as a workaround you can create a file/folder at the top level by right-clicking on a top-level file (which does *not* change selection to that file).

**Comment by peterflynn** [comment] 2015-01-12 20:37
This is a duplicate of #9341

**Closed** 2015-01-12 20:37 UTC
