### ISSUE TITLE
Cannot run Brackets grunt build with sprint-release-39

### ISSUE THREAD

**Issue by bundgaard** [adobe/brackets#7944] opened 2014-05-27 09:22 UTC
(11:18:53)$ sudo grunt
Running "jshint:all" (jshint) task

> > 320 files lint free.

Running "jasmine:src" (jasmine) task
Testing jasmine specs via phantom

> > Error: Script error
> > http://requirejs.org/docs/errors.html#scripterror at
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > .grunt/grunt-contrib-jasmine/require.js:14 z
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > Error: Script error
> > http://requirejs.org/docs/errors.html#scripterror at
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > .grunt/grunt-contrib-jasmine/require.js:14 z
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > Error: Script error
> > http://requirejs.org/docs/errors.html#scripterror at
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > .grunt/grunt-contrib-jasmine/require.js:14 z
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > Error: Load timeout for modules: text!config.json_unnormalized2,text!language/languages.json_unnormalized3,text!htmlContent/dialog-template.html_unnormalized4,i18n!nls/strings_unnormalized5,i18n!nls/urls_unnormalized6,i18n!nls/strings-app_unnormalized7,text!base-config/keyboard.json_unnormalized8
> > http://requirejs.org/docs/errors.html#timeout at
> > .grunt/grunt-contrib-jasmine/require.js:31 
> > .grunt/grunt-contrib-jasmine/require.js:14 z
> > .grunt/grunt-contrib-jasmine/require.js:16 w
> > .grunt/grunt-contrib-jasmine/require.js:16 

Warning: PhantomJS timed out, possibly due to an unfinished async spec. Use --force to continue.

Aborted due to warnings.

I will try and look into it, but for now I want to know if more has the same experience with the latest sprint source code

**Comment by ficristo** [comment] 2016-11-02 18:57
It seems a dupe of https://github.com/adobe/brackets/issues/12228 which I close since I waasn't able to reproduce.
@bundgaard @mackenza are you still able to reproduce?

**Comment by bundgaard** [comment] 2016-11-03 09:45
Hello,

I will look into this in the coming days, sitting pretty tight with work,
so I have no opportunity to test it at the moment, but I will return with
more information


Thanks

David

2016-11-02 19:58 GMT+01:00 ficristo <notifications@github.com>:

**Comment by mackenza** [comment] 2016-11-03 12:09
might as well close this. it's 2 1/2 years old

**Comment by ficristo** [comment] 2016-11-03 17:32
IMO it is wrong to close an issue only because is old.

**Comment by ficristo** [comment] 2017-02-03 19:26
I have not been able to reproduce the error.

**Closed by ficristo** 2017-02-03 19:26 UTC
Labels: low priority, Waiting for user
