### ISSUE TITLE
Please correct the error when installing in Ubuntu

### ISSUE THREAD

**Issue by AlexParovozoff** [adobe/brackets#13340] opened 2017-04-26 19:24 UTC
### Description

Please correct the error when installing in Ubuntu 17.4, dependency on libgcrypt11. Ubuntu has the libgcrypt20 package installed.

**Comment by petetnt** [comment] 2017-04-26 20:26
Hi @AlexParovozoff!

Various workarounds for this issue has been listed in https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide#libcrypt11-missing-dependency-in-ubuntu

Closing as duplicate of https://github.com/adobe/brackets/issues/10255

**Closed by petetnt** 2017-04-26 20:26 UTC

**Comment by mgraves9803** [comment] 2017-05-04 04:21
you can also go here: https://fourthfruit.github.io/fixes/
