### ISSUE TITLE
Files not updating automatically

### ISSUE THREAD

**Issue by aaronmohr** [adobe/brackets#13336] opened 2017-04-24 17:34 UTC
My files don't seem to be updated automatically in Brackets anymore. Whenever I externally add a new file into my code's root folder (images, JS libraries, etc.) I have to restart Brackets before I can access them within the program. Whereas before they would be immediately accessible within Brackets.

I'm currently running version 1.9.0 on Sierra, this issue only started since I updated to the most recent build.

**Comment by ficristo** [comment] 2017-04-26 18:13
What is the name of your project? Does it contains chars like `(` or `*` for example?

**Comment by ficristo** [comment] 2017-07-05 18:18
Closing as a dupe of https://github.com/adobe/brackets/issues/12864

**Closed by ficristo** 2017-07-05 18:18 UTC
Labels: Waiting for user
