### ISSUE TITLE
Squares in Brackets Navbar

### ISSUE THREAD

**Issue by Untakeablecode** [adobe/brackets#13798] opened 2017-10-27 02:48 UTC
After Updating from Ubuntu 16.04 to Ubuntu 17.10, I opened up Brackets in the shiny new OS and the navbar changed to "◻️".
![screenshot from 2017-10-26 22-31-10](https://user-images.githubusercontent.com/22330628/32085662-8446212c-ba9e-11e7-853c-d073aebd058e.png)

I tried to reinstalling Brackets but that did nothing and deleted temp files (I think there was no point in doing that tho).

Maybe it's an OS issue... I don't really know. 
Anyway, thanks for the help!

**Comment by kiroma** [comment] 2017-10-27 06:42
Dupe of #13738.

**Comment by ficristo** [comment] 2017-11-09 19:38
Duplicate of #13738

**Closed by ficristo** 2017-11-09 19:38 UTC
