### ISSUE TITLE
[IQE]: Quick open box and drop down results are not in sync with each other when the Brackets window is resized

### ISSUE THREAD

**Issue by rawat11** [adobe/brackets#10981] opened 2015-04-23 09:02 UTC
Steps To Reproduce 

1. Launch Brackets
2. Open any file
3. Select Quick open from the Navigate menu
4. type any character in the quick open box
5. Resize the brackets window

Result : Quick open box and drop down results are not in sync with each other when brackets is resized.

ENV : Win 7 Eng OS, FR OS
Build : Build: Brackets 1.3.0-16017

![ui-1](https://cloud.githubusercontent.com/assets/10069885/7293805/955950d0-e9c5-11e4-87bc-0137b9c91bb9.png)

![ui-2](https://cloud.githubusercontent.com/assets/10069885/7293809/9bb44fc0-e9c5-11e4-80f8-a1e417fb5285.png)

**Comment by peterflynn** [comment] 2015-04-23 09:08
Closing as a duplicate of #1157 (which in turn was closed & moved to the feature backlog)

**Closed by peterflynn** 2015-04-23 09:08 UTC
Labels: IQE
