### ISSUE TITLE
cannot hide information inside some tags

### ISSUE THREAD

**Issue by gerald2799** [adobe/brackets#13165] opened 2017-03-09 14:53 UTC
with tags like `<div>`, `<body>` etc there is a small arrow in the right, so you can hide the information inside of it. but it doesnt work with tags like `<script>` or `<style>`. is it a problem or it should work in a such way?

**Comment by ficristo** [comment] 2017-03-13 19:06
Which arrow and where? Code editor, live preview, something else?
Could you add a small screenshot showing the issue?

**Comment by gerald2799** [comment] 2017-03-13 19:17
sorry, my bad english.
i was talking about this triangle near tags, which help you with hiding information inside of tags. you can see one near "<head>", but not near "<style>".
![image](https://cloud.githubusercontent.com/assets/24938726/23871215/17554de6-0832-11e7-9e5f-3cf6330fd3a6.png)

**Comment by ficristo** [comment] 2017-03-13 19:29
Ah, that arrow! Yeah, I can reproduce in Brackets but not in the codemirror code folding demo at http://codemirror.net/demo/folding.html

/cc @thehogfather

**Comment by thehogfather** [comment] 2017-03-14 07:14
did a quick check and the reason for this appears to be that the handlebars fold (which is now registered for the htmlmixed mode) does not correctly parse xml tags. I will look into addressing this.

**Comment by thehogfather** [comment] 2017-03-18 00:42
After a bit more investigation, it turns out the `htmlmixed` mode in code mirror returns the inner mode starting from the opening html tag. This means when you query the mode at the line that says `<style>` or `<script>` you get `css` or `javascript` instead of `xml`.

As a result, the correct fold range finder is not loaded for the line. [An issue/question](https://github.com/codemirror/CodeMirror/issues/4651) has been raised on CodeMirror to track this.

**Comment by thehogfather** [comment] 2017-03-20 18:44
The issue turned out to be a missing parameter to the `CodeMirror.Pos` constructor in a number of places. PR #13198 should address this.

**Comment by ficristo** [comment] 2017-04-09 12:53
Closed by #13198

**Closed by ficristo** 2017-04-09 12:53 UTC
Labels: F Code Folding
