### ISSUE TITLE
Split view memory

### ISSUE THREAD

**Issue by nickfmc** [adobe/brackets#10802] opened 2015-03-29 04:52 UTC
if you code in split view 90% of the time, the other 10% when you need more space it would be nice to be able to turn it off, work for a bit and turn it back on without it loosing all your open files you had organized by top and bottom or left and right.  Currently you have to move the middle position to get more space and keep your spilt view files open.  it makes for nasty UX

**Comment by redmunds** [comment] 2015-03-29 15:30
Yes, this would be nice. Closing this as a duplicate of #9575.

**Closed by redmunds** 2015-03-29 15:30 UTC
