### ISSUE TITLE
Undo Stops Working

### ISSUE THREAD

**Issue by designcise** [adobe/brackets#11967] opened 2015-12-01 23:27 UTC
I haven't been able to exactly pinpoint why this happens, but it seems to be happening right after when I do a "find in files" search. I'm using Release 1.5 build 1.5.0-16538

**Comment by petetnt** [comment] 2015-12-02 07:37
The issue is being tracked here: #11826

`Find in Files` does sound like a potential culprit

**Comment by abose** [comment] 2015-12-02 17:21
Closing duplicate.

**Closed by abose** 2015-12-02 17:21 UTC
