### ISSUE TITLE
Bad font rendering makes text hard to read

### ISSUE THREAD

**Issue by arrbie** [adobe/brackets#11013] opened 2015-04-28 17:28 UTC
Text rendering in Brackets is of very low quality and subpar other text editors. Eyes become tired and you need to increase the text size to compensate for the low readability. To me this is a deal-breaker.

The effect is quite independent of choice of font, and is especially true for the default font 'SourceCodePro-Medium', but also for 'Menlo-Regular' (pics below).

It's as if Brackets weren't even using the Mac's built-in font rendering API:s for text areas. Adobe, are you fiddling on your own with the text rendering algorithms here? I know you are masters of graphics – especially typography – but I think you should trust Apple on this one, and you get it for free. This is NOT a matter of differences in aesthetic opinions. Just follow the system defaults like all other Mac applications do and we'll all be happy. (Already pointed out by drewhamlett at GitHub back in 2013)

See comparison of screen dumps from Brackets (top pic) vs Smultron (bottom pic) running on the same machine. This font is "Menlo-Regular" 11pts (or "px" as Brackets says). Pay attention to the letters in the word "supplied". Every single letter (except the "i", which is actually too thin) is much more unclear, smudged out, and of varying thickness on the Brackets version.

![brackets](https://cloud.githubusercontent.com/assets/9554571/7375715/c5994246-edda-11e4-883d-d806ab5a35d8.png)
![smultron](https://cloud.githubusercontent.com/assets/9554571/7375716/c5b934ca-edda-11e4-9cd0-b30b1eab7597.png)

This problem is true not only for the actual text area, but also for all other text inside the Brackets windows, ie sidebar, window title, modal dialogs etc.

Brackets version: Release 1.3 build 1.3.0-16022
OS: Mac OS X 10.10.3
Hardware: MacBook Air 13" (1440-900 px)
Extensions: None (fresh factory install)

**Comment by brunnopleffken** [comment] 2015-05-04 02:52
I believe Brackets uses grayscale anti-aliasing instead of subpixel for some reason (performance, maybe)... I agree with you, it's really bad and I use a "CSS injection" extension and do some workarround to solve it.

This is my workarround to get subpixel rendering back:

```css
* {
    -webkit-backface-visibility: visible !important;
    backface-visibility: visible !important;
}
.CodeMirror {
	-webkit-font-smoothing: subpixel-antialiased !important;
}
```

**Comment by arrbie** [comment] 2015-05-04 10:26
@brunnopleffken: Yes, thank brunnopleffken. I also try to easen up on the worst pain by applying similar rendering patches. I've also experimented a little with 98% alpha on the text colors, eg rgba(0, 136, 0, 0.98). It helps a little, but it's still VERY FUZZY compared to normal Mac standards and other text editors.

During the last week I've spoken to five different developers using Macs, and every single one of themhad been ditching Brackets for the same reasons: terribly fuzzy text rendering. One guy said something like: "If the Brackets developers can't even prioritize text quality in their text editor, then I don't entrust them with anything else either. Everything else come second.". And I kind of agree, it's a shame and they will loose a lot of Mac users in this way.

Brackets
![brackets menlo regular 11](https://cloud.githubusercontent.com/assets/9554571/7452000/fc287da0-f257-11e4-993c-176f3bdd684a.png)

BBEdit (same color codes as Brackets' above)
![bbedit menlo regular 11](https://cloud.githubusercontent.com/assets/9554571/7452002/0dbf7bc2-f258-11e4-9095-bcb074cd09c4.png)

Smultron
![smultron menlo regular 11](https://cloud.githubusercontent.com/assets/9554571/7452006/18bbb2a2-f258-11e4-963f-c3707216fc6b.png)

**Comment by nethip** [comment] 2015-05-04 11:00
@arrbie I have marked this for 1.4 and we need to figure how to disable sub-pixel rendering on Mac.

**Comment by arrbie** [comment] 2015-05-04 11:08
@nethip, thanks for taking this seriously. However, I think you are quite on the wrong track. This is definately not a matter of "disable sub-pixel rendering on Mac". Actually, you seem to have misunderstood completely nethip. Please, read carefully all fixes that have been attempted above – without reaching satisfactory results.

You need to get hold of someone that really uses a Mac as their primary tool and ask for their assistance. It's simply not enough for you to just test a little on a Mac, since clearly you lack the ability to see the real nature of the problem here. The product should never have been released in this state otherwise.

**Comment by ryanstewart** [comment] 2015-05-04 11:19
Is this just an issue on non-retina Macs? I'm on a 15" Mac Book Pro and I'm not seeing any obvious text issues. 

I definitely notice the differences in the screenshots above. I just don't see those differences on my own machine.

**Comment by nethip** [comment] 2015-05-04 12:19
@ryanstewart @arrbie I think this is a problem on all Macs. And it is much worse on non-retina displays. We have being tracking multiple issues with fonts on MAC (https://github.com/adobe/brackets/issues/4640, https://github.com/adobe/brackets/issues/10083,  https://github.com/adobe/brackets/issues/2791) for quite some time. And I think actually CEF 2171 made it look a lot worse. 

@arrbie I take back what I said about disabling sub-pixel rendering. What I meant was to tweak this attribute to get the desired rendering. And by the way we don't use any custom rendering/layouting (i.e use `Core Text` or `NSText*` rendering) on Mac. We use the rendering provided by CEF itself and we completely rely on the CSS to tweak the text rendering on all platforms that we support(Mac/Win/Linux). It is just tweaking CSS to get the desired result.

As mentioned in https://github.com/adobe/brackets/issues/10083#issuecomment-66513265, Atom seemed to have fixed some of these issues (to do with kerning and leading) by using one of the blink settings, which we cannot use inside Brackets as we are based out of CEF. It would be great if you can open a PR with your suggestions and we could collaborate on this. We will make sure this PR would indeed be picked up for this release. Please take a note that we have integrated CEF 2171 and the rendering looks a little different to that of the older versions(<=1.0) and that the solution should work for retina(or HiDpi) as well as non-retina displays as attempts were made earlier which was kind of mutually exclusive kind of result.

**Comment by nethip** [comment] 2015-05-04 12:27
Also take a look at https://github.com/adobe/brackets/issues/10083#issuecomment-65554516 for @peterflynn comment on the same.

**Comment by arrbie** [comment] 2015-05-04 13:48
CEF is crap for the Brackets product. I wish Brackets had used the built-in web rendering API:s of each OS (platform) instead.

**Comment by arrbie** [comment] 2015-05-04 16:09
Regarding #10083 and @peterflynn's comments:
I think he might be onto something here. I also have noticed strange horizontal shiftings related to the font size. Fractional width is definately part of this problem. However, as I pointed out in a new comment in #10083, there must be more to it than this since the geometric size of the rendered text is actually correct now (used to be too narrow).

**Comment by nethip** [comment] 2015-05-04 17:16
From my previous experience we had problems with fractional widths attributed to AA, only if the AA algorithms are implemented by the renderer rather than by the system, like the text engine used in `Photoshop`, and `Fireworks`(Check Anti aliased text in these products and you will see jaggered edges, which I have been fighting for ages to figure out how to solve this AA problem as we had to implement the sub pixel rendering by ourselves). 

System does an awesome job of using sub pixel rendering along with AA to smoothen the curves in a brilliant way(looks good on LCD and LEDs). So I don't think there is any problem with the fractional widths. The downside of this is that same character may have different rendering, as it is bound to happen with fractional widths, but that is still fine.

 I am not sure if chrome uses any line breaking algorithm by themselves. Mac provides `CTLine` and `CTFrame` which do a great job in calculating string widths and rendering them good as well. I need to look at chromium's source and figure out what is happening there. I am not sure if they are using any offscreen rendering for particular cases.

While modernising the text engines in other Adobe products (Dreamweaver to be more specific), I found that AA works fine even for font size less than 11pts. The biggest problem with AA is to do with the way scaling is implemented to smoothen the curves and this becomes worse with ligatures and auto kerning (especially on Mac), if not implemented fine or a badly written font. So here is what we need to do

* Disable ligatures
* Use `-webkit-font-smoothing: subpixel-antialiased;` refer to this article http://www.intridea.com/blog/2014/5/8/better-font-smoothing-in-chrome-on-mac-os-x. 
* If the above does not work we need to see if there is any other CSS property, like drop shadow, which is creating a pixelated look.
* Also we could have a media query to enable or disable AA based on screen resolution and pixel density. This we could give it a try.
* Also we need the check if chrome is defaulting to offscreen rendering in certain cases(may be because of some CSS attributes)

**Comment by nethip** [comment] 2015-05-04 17:19
* There is another thing I want to add. If there is a scale factor applied to the entire text, it is going to effect the entire text rendering. So another point to look out would be to see if any scale factor is getting applied.

**Comment by arrbie** [comment] 2015-05-04 18:03
Already tried the follow to no satisfaction:
• disabling ligatures
• changing all varieties of font-smooting (incl AA off)
• drop shadow nullification
• font scaling factors (+/- 0.5 px in steps of 0.01 px)

**Comment by ryanstewart** [comment] 2015-05-04 18:24
@arrbie if you're feeling brave, would you mind seeing if [this experimental branch of Brackets](https://github.com/zaggino/brackets-electron) running on Electron is better?

Here's a side by side comparison on my machine (Black title bar is Brackets normal, grey is with Electron)
![main_css__getting_started__ _brackets_and_main_css__getting_started__ _brackets_and_slack](https://cloud.githubusercontent.com/assets/45450/7459361/e0ae5386-f2b8-11e4-8f34-199d6c6b7bc3.png)

**Comment by brunnopleffken** [comment] 2015-05-04 18:47
I can't see differences between Brackets-Shell and Electron at all... I believe the main point here is that Brackets doesn't use sub-pixel anti-aliasing for text, it uses greyscale, leading it into fuzzy fonts (basically, the same issue that IE10 and Office 2013 faced in Windows 8 a few years ago) on non-Retina/non-High-DPI displays, lowering the effective resolution...

Enabling sub-pixel rendering will also improve ligatures and font kerning, because it'll use three pixels instead of just one with a single color. On Macs it's even worse, because it doesn't use the "aligned-to-grid" rendering like Windows does.

![thesansmono_office_features_cleartype](https://cloud.githubusercontent.com/assets/3427344/7459731/71252dc6-f274-11e4-93b6-9fadaa3b131c.gif)

**Comment by nethip** [comment] 2015-05-04 18:51
@brunnopleffken Did you do this comparison on a retina display. If yes it is hard to figure that differences because of high pixel density. May be we might want to compare this on a non retina display. 

And you many be right about enabling sub pixel rendering support. Did you get a chance to experiment with `-webkit-font-smoothing: subpixel-antialiased;`. Does that make the rendering a little better.

**Comment by nethip** [comment] 2015-05-04 18:55
@ryanstewart I am not able to distinguish between both the screenshots just by looking at them. I will have to probably do an XOR in Fireworks to figure out the little differences.

**Comment by arrbie** [comment] 2015-05-04 19:23
@ryanstewart, nope, I can't see any difference in rendering quality between your two images of Brackets normal and Electron above. Both look good to me.

I will try to install the experimental branch on my MacBook Air 13" (non-retina) and get back to you with results. Now, where do I find the compiled version of this?

**Comment by MarcelGerber** [comment] 2015-05-04 19:28
@arrbie There's no compiled version available, but it's more or less easy to set up:
1. `git clone https://github.com/zaggino/brackets-electron`
2. `cd brackets-electron`
3. `git submodule update --init`
4. `npm install`
5. `npm start` to run

Notice you won't have your usual extensions and themes installed as it's more or less a separate install.

Even if you don't see a difference/improvement immediately, please keep it installed as it's easily configurable and thus, you could test some different configurations.

**Comment by nethip** [comment] 2015-05-04 19:31
@brunnopleffken I just saw from your above comment that you have already tried `-webkit-font-smoothing: subpixel-antialiased;`. Let us then compare then screenshots with this setting on. I will do this first thing tomorrow.

**Comment by arrbie** [comment] 2015-05-04 19:37
@MarcelGerber, what's <i>npm</i>?

**Comment by nethip** [comment] 2015-05-04 19:40
@arrbie `npm` is a node package manager. Install `node` and this would get installed along with it

**Comment by arrbie** [comment] 2015-05-04 19:41
Sorry, don't do NodeJS yet. Will have to pass on this one.

**Comment by MarcelGerber** [comment] 2015-05-04 19:42
Oh, ok. It's the Node package manager.
So, Node is a command line tool that lets you run JavaScript locally on your computer (with access to files and so on), and npm is a tool that lets you install modules (similar to `pip` for Python, `gem` for Ruby, etc.).

Just saw your answer: You don't really have to have any Node skills for this, just install Node and you're ready. But it's of course also fine to not install it :)

**Comment by arrbie** [comment] 2015-05-04 19:48
@MarcelGerber, yeah, I know about NodeJS. Just not ready to go there yet. Any way to install Brackets Electron w/o node?

**Comment by nethip** [comment] 2015-05-04 21:23
Actually we were deliberate in disabling sub pixel AA. See this https://github.com/adobe/brackets/issues/4640#issuecomment-28142044

After looking at our issues base, I found that the only possible solution for time being is to write an extension or a theme which would either enable/disable sub pixel-anitaliasing. Also we could have more options in this extension to either completely disable AA or just disable sub pixel AA. That way we could give more flexibility to the users. This have been disabled to fix some issues with the animations. If those animation issues indeed come back after enabling back sub pixel AA, then we should be disabling animations in the code view as well, in this extension.

**Comment by arrbie** [comment] 2015-05-04 21:59
Here we go again. This animation reason for fiddling with the AA has been discarded in numerous discussion comments. It seems nobody has reported proof of such a connection, but rather the opposite. So we have to conclude that it's simply a myth.

Also – and more importantly – we are not talking about simply switching on or off the subpixel-antialiasing. This has already been tested (in extensions and themes, see the 9-bullet list above), and is <b>not</b> enough to solve the fuzzy text rendering issue. I haven't seen a single CSS command that does that, independently of where it's put.

Since this discussion is clearly going in loops, I suggest we give up and close it unsolved(!)

**Comment by brunnopleffken** [comment] 2015-05-04 22:10
There has been some change on Brackets-Shell or something since Brackets v. 1.0? I tested this CSS (using ```-webkit-font-smoothing``` and ```-webkit-backface-visibility``` on my friend's iMac and it seems not to work anymore... I used to do this workaround before I started using MacBook Retina, and yes, I checked with Digital Color Meter: there was sub-pixel anti-aliasing using CSS... ;)

By the way, I never see an animation issue with the anti-aliasing enabled... All I see is a better readability on dark backgrounds on OS X, nothing else! So, I see no reason to disable it...

And by the way #2: Brackets uses Chromium, it's more like a browser, so I don't know if it's possible to use Mac's native font rendering APIs on it (which is great on Sublime and TextMate), as it is defined by Chromium itself.

**Comment by nethip** [comment] 2015-05-05 04:04
I had mentioned in my comment above the actual reason why we have turned this off with the older build of CEF. Now I also mentioned that **if** and **only if** we see any degradation at all only then we need to worry about disabling animations, though it has been ruled out in multiple comments. 

@brunnopleffken The difference between 1.0 and 1.1 is that we have upgraded to CEF 2171 in 1.1. If I understand it correctly, you are saying enabling sub pixel anti aliasing is not fixing the fuzzy text issue in the latest build(1.3)? And about the animation issue, I think it was more to with performance but that was way back when Brackets was using a older build of CEF.

I understand it could get quite frustrating to see nothing working but hey, you can think this is to be a good learning experience. And as I mentioned above we will be tracking this for 1.4 especially when we are hearing this from multiple users.

**Comment by arrbie** [comment] 2015-05-05 13:49
Consider <b>switching</b> from CEF <b>to PhoneGap</b> on the Mac distribution of Brackets – if you think that userbase is of value to Adobe. It will make the product behave <i>natively</i>, and make it much <i>leaner</i> (you could save ~75MB of the total 114MB). It would also start up faster.

The should require only minor work, and I don't see any reason this product should make hard-coded dependencies on CEF functions anyway.

**Comment by arrbie** [comment] 2015-05-16 15:34
Still, nearly 3 weeks after the problem was reported here, there isn't even an issue report entered on bitbucket.org/chromiumembedded/cef/

Since this bug has been reported as a Brackets deal-breaker by various Mac users, I can only conclude that the Brackets team don't care about this community anymore.
:-(

**Comment by bobrocke** [comment] 2015-05-17 22:41
I've been using Atom for a while on Macs and spent a minute going back to Brackets to see what's new. What's old is that fonts still render very poorly in Brackets and just fine in Atom. It's a deal breaker for me - back to Atom (and TextMate).

**Comment by arrbie** [comment] 2015-05-18 08:17
@bobrocke: Yup, I hear you.
This weekend our team took the decision to leave Brackets alltogether. We have been quite patient waiting for a fix to this blurry text for some time now. But we can't force people at Adobe. If they don't want us, we won't beg. Now, I will have to tell people about <b>Brackets – the text editor that doesn't do text</b>.

**Comment by nethip** [comment] 2015-05-18 12:11
@arrbie @bobrocke Sorry that you are facing these rendering issues while using Brackets. As I have mentioned above we are pretty serious about solving this issue and that we are tracking this for 1.4. We in fact bring this up everyday in our daily stand ups. The problem is that CEF does not offer any straight forward way to control sub pixel rendering from CEF side and hence we need to have different work arounds to fix this issue by tweaking CSS. Atom uses chromium, which gives more options in controlling sub pixel rendering.

While we figure out the best way to solve the problem, could you execute these statements in the developer console and let us know if this fixes the problem. 

Choose `Debug->Show Developer Tools`, and click on the console tab. Then execute the following statements one by one.

```
$(document.body).css("-webkit-backface-visibility", "visible")
$(document.body).css("-webkit-font-smoothing", "subpixel-antialiased")
```

After doing this please change the font from `SourceCodePro-Medium` to `SourceCodePro-Regular`, by accessing *View->Themes...* menu.

We have not logged any bug with chromium as there are already issues with  respect to sub pixel rendering that have been reported on the chromium bug. It is going to take some time resolving the issue as we need to figure out what is the best possible way to solve this. So please bear with us on this. Thanks for understanding!

**Comment by nethip** [comment] 2015-05-18 12:49
Here is the link to the chromium bug where there is lot of discussion on the same blurry text issue in CEF.

https://code.google.com/p/chromium/issues/detail?id=152304

**Comment by arrbie** [comment] 2015-05-18 22:02
@nethip Thanks, your fix actually did the trick. All text suddenly went crisp and clear. But it does <b>not</b> seem to stay that way after restarting Brackets. Is there a simple way to make it "stick"?

**Comment by bobrocke** [comment] 2015-05-18 22:12
@nethip That worked for me, too. After the second command, the text everywhere in the interface looks **much* better. I assume that change will make it into v1.4 so that it will "stick?"

**Comment by ryanstewart** [comment] 2015-05-18 22:15
@arrbie I'll talk to @nethip but this may be something we want to roll an intermediate build on to test performance and how it works on Windows as well. 

So short answer: no easy way to make it stick at the moment short of editing the Brackets source code yourself, but hopefully it will be permanent as of 1.4 and we'll also have a test build for people to try where it's permanent.

**Comment by arrbie** [comment] 2015-05-18 22:27
@ryanstewart Allright, good enough for me.

**Comment by bobrocke** [comment] 2015-05-18 22:37
@ryanstewart Is it an easy fix to the source? I may want to patch mine until the official build is out.

**Comment by ryanstewart** [comment] 2015-05-18 23:23
@bobrocke I *think* (not tested yet) that you'd have to edit this file - https://github.com/adobe/brackets/blob/master/src/styles/brackets.less and then make sure those .less files got recompiled into CSS. And you can see where we've already set those properties so they're easy to find. 

There are some instructions here - https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets - on how to build things from source. Let me know if that helps!

**Comment by zaggino** [comment] 2015-05-18 23:43
Just tested this on my Mac

If you're running Brackets from source according to this guide https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets

Only thing you need to change is this line: https://github.com/adobe/brackets/blob/master/src/styles/brackets.less#L58
to `subpixel-antialiased`

**Comment by ryanstewart** [comment] 2015-05-18 23:48
@zaggino to the rescue!

**Comment by zaggino** [comment] 2015-05-19 00:12
Also guys, let us know if you'll see any ill side-effects with this setting, the current value was set in https://github.com/adobe/brackets/pull/2665 to fix
> typically the line numbers, but sometimes the whole code editor flicker lighter on the Mac

**Comment by arrbie** [comment] 2015-05-19 09:38
This is what I did to fix the existing Brackets app so that the text crispness stays there, without recompiling or running from source:

Closed the Brackets application.
In Finder, Show Package Contents of Brackets and go to folder  Contents / www / styles

Edited brackets.min.css like this…
<pre>• Changed the 4th occurance of “-webkit-font-smoothing:auto” => “-webkit-font-smoothing:subpixel-antialiased”
• Changed the only occurance of “-webkit-backface-visibility:hidden” => “-webkit-backface-visibility:visible”</pre>

Edited brackets.min.css.map (don't know if this was really needed, but just in case) like this…
<pre>• Changed the 4th occurance of “-webkit-font-smoothing: antialiased” => “--webkit-font-smoothing: subpixel-antialiased”
• Changed the all occurances of “-webkit-backface-visibility: hidden” => “-webkit-backface-visibility: visible”</pre>

Saved both files.
Reopened Brackets.
Was happy.

**Comment by nethip** [comment] 2015-05-19 19:50
@arrbie Yeah that should work too :smile: 

@arrbie @bobrocke For convenience sake I have kind of packed both the above commands as an extension. This extension also takes care of enabling sub pixel rendering only for retina displays. 

Here is the link to the extension https://www.dropbox.com/s/yu6dqt5qm079r3r/EnableSubPixelRendering.zip?dl=0

You could install it by dragging and dropping the `zip` file onto the extension manager dialog. Let me know if you face any problems with that.

**Comment by bobrocke** [comment] 2015-05-19 19:53
@arrbie Cool. Thanks! I give that a try.

**Comment by tschundeee** [comment] 2015-07-03 08:26
Came here because font rendering in brackets is different from all other editors (sublime, choc, textmate etc.). @nethip thx your package solves this in a convenient way.

**Closed** 2015-07-10 18:37 UTC
Labels: Mac only, medium priority

**Comment by mithat** [comment] 2015-08-23 16:59
This isn't a Mac only problem. Awful font rendering also affects Linux. I used nethip's extension but commented out 
```js
if (brackets.platform === "mac" && window.devicePixelRatio < 2) {
```
and the matching closing brace to unconditionally apply subpixel rendering. I then switched the typeface to 'DejaVu Sans Mono'.

Interface text still looks blotchy, but code windows are now usable.

**Comment by nethip** [comment] 2015-08-26 11:08
@mithat Thanks for porting my extension. Right now changes relevant to subpixel antialiasing are in the master. Please have a look at [this](https://github.com/adobe/brackets/blob/c008571f455d2f5ac1a8ff63fbb0dd6c642acb41/src/view/ViewCommandHandlers.js#L540) to include the changes for linux as well.

**Comment by mithat** [comment] 2015-08-26 19:15
@nethip I'm happy to test but right now I don't have a lot of time to dig into the code. Can I create a feature request for this? I suspect someone who knows the codebase and who knows how you filter for linux could make the change in about 10 minutes.
