### ISSUE TITLE
[javascript] Brackets gets confused by `${new.target}`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [adobe/brackets#11905] opened 2015-11-10 17:39 UTC
```js
class A {
  constructor() {
    console.log(`${new.target}`);
  }
}
```

  1. I can collapse neither `class A {` nor `constructor() {`
  2. All the code after `new.target}` is highlighted as a string
  3. If you delete the last \` and rewrite it, Brackets will append another \` (e.g. console.log(\`${new.target}\`\`);)

**Comment by petetnt** [comment] 2015-11-11 06:55
`new` is [a reserved keyword in EcmaScript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Reserved_keywords_as_of_ECMAScript_6) which breaks the parser when used in such way. If you change `new` to something else, it works as intended

```
class A {
  constructor() {
    console.log(`${newThing.target}`);
  }
}
```

**Comment by nicolo-ribaudo** [comment] 2015-11-11 07:05
`new.target` is valid JsvaScript.

**Comment by petetnt** [comment] 2015-11-11 07:20
@nicolo-ribaudo oh that's neat :open_mouth: [new.target REF](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target), didn't know that. You learn something new everyday! :cool: 

 You can work around it by assigning it as variable, but it would be neat if you could report this to https://github.com/codemirror/CodeMirror/issues as it is a CodeMirror issue

**Comment by nicolo-ribaudo** [comment] 2015-11-11 07:32
@petetnt Thank you, I can't reproduce this issue in the online CodeMirror demo, I think this can be fixed updating CodeMirror.

**Comment by petetnt** [comment] 2015-11-11 07:41
@nicolo-ribaudo Yup, it was implemented mere 22 days ago at https://github.com/codemirror/CodeMirror/commit/457468315e8175befd7464d55f4c5eeabf76186e 

ping @MarcelGerber

**Closed** 2016-04-04 01:10 UTC
