### ISSUE TITLE
Not able to change the language to english

### ISSUE THREAD

**Issue by imrahul81** [adobe/brackets#13815] opened 2017-11-06 17:27 UTC
I installed Brackets 1.11 build 1.11.0-17524 (release 86b5e2d4e)  and the language was some gibberish.
I tried changing the language from debug menu as pointed out by others but no luck.
OS  - Ubuntu 17.10 
![screenshot from 2017-11-06 22-55-57](https://user-images.githubusercontent.com/23965016/32454608-ba47f818-c345-11e7-968a-fa9fa6f9e84d.png)
Please help!

**Comment by kiroma** [comment] 2017-11-06 18:53
Known issue at #13738, please look at #13731 for resolution.
In essence, to solve it please install libpangoft2-1.0-0 >= 1.40.5 or unpack the libs from the package to path of Brackets installation.

**Comment by imrahul81** [comment] 2017-11-06 19:46
Installing the package isn't helping. Its already a new version.
Even the threads #13738 and #13731 couldn't help.
![screenshot from 2017-11-07 01-14-10](https://user-images.githubusercontent.com/23965016/32460579-41e68c68-c359-11e7-81ea-7038623fcd29.png)

**Comment by kiroma** [comment] 2017-11-06 20:14
Whoops, typo.
What I meant is you need to downgrade the package to be at least version 1.40.5 or older, because the newer versions remove a function which CEF uses for rendering the menus.

**Comment by imrahul81** [comment] 2017-11-06 20:44
Well!
Sorry to bother.
But how do I downgrade the libpangoft2-1.0.1 (1.40.12-1) to earlier version.
OS- Ubuntu 17.10

**Comment by kiroma** [comment] 2017-11-06 21:00
Ubuntu unfortunately deletes old versions of packages from its repositories, so you'll need to either find an old package, wait for brackets 1.12 where a workaround is going to be implemented, or compile from source.
If you choose to compile from source, run the following commands:
```
sudo apt-get install build-essential git
sudo apt-get build-dep libpangoft2-1.0-0
git clone git://git.gnome.org/pango
cd pango
./configure --prefix=<PATH_TO_BRACKETS (i.e. /opt/brackets/)>
make
make install
```
Last step may require using sudo.

**Comment by ficristo** [comment] 2017-11-09 19:37
Duplicate of #13738

**Closed by ficristo** 2017-11-09 19:37 UTC

**Comment by mf9940** [comment] 2019-08-29 01:45
So I was messing around with my Brackets settings and changed my lang from English to Italian, any idea how to switch it back?
