### ISSUE TITLE
Error opening files in split view

### ISSUE THREAD

**Issue by DariusNorv** [adobe/brackets#12196] opened 2016-02-05 14:15 UTC
When I'm using split view with some kind of files in different tabs for a long time it's becomes glitchy with files.
For example: I have 3 files 1.css 2.css 3.css in two tabs. When I select 1.css from tab it select 1.css, brackets shows right filename and path in top of panel but I see in code content of 2.css. And if I save this file it saves content of 2.css to 1.css. Restarting brackets with cmd+R doesn't help. Only close brackets full and open again
Brackets sprint 6 build 1.6.0-16680 (release 3df0ac6fa) 
Mac OS X 10.11.3

**Comment by petetnt** [comment] 2016-02-05 17:54
Duplicate of / related to https://github.com/adobe/brackets/issues/12162

**Comment by DariusNorv** [comment] 2016-02-05 17:58
@petetnt, thanks

**Comment by abose** [comment] 2016-02-25 09:11
A build refresh is scheduled by his week or next for 1.6 and after that the new installers posted will contain this fix.
Closing as fixed.

**Closed by abose** 2016-02-25 09:11 UTC
