### ISSUE TITLE
Closing brackets

### ISSUE THREAD

**Issue by DrPandemic** [adobe/brackets#10493] opened 2015-01-30 02:23 UTC
Hi,
To close brackets application I need to click twice on the close button. Nothing seems to happen after the first click. I'm running on Arch Linux, using Cinnamon as Desktop Manager and my bracket version is : Release 1.1 experimental build 1.1.0-0. 
Maybe the problem comes from Cinnamon, but it is the first app that react like this.

**Comment by peterflynn** [comment] 2015-01-30 02:35
Duplicate of #4611

**Closed by peterflynn** 2015-01-30 02:35 UTC
