### ISSUE TITLE
Brackets freezing all the time

### ISSUE THREAD

**Issue by ninichang** [adobe/brackets#14556] opened 2018-10-05 17:13 UTC
My Brackets app is constantly freezing recently no matter whether I am editing a big or small file. I tried reinstalling the app several times, I tried retarting my mac, and I also tried deleting the cache files and jason files, but none of them seem to work. When I used brackets several months ago it was totally fine, but these days it suddenly becomes very hard to control.

When it freezes, I simply cannot type anything, and I just have to wait until it becomes normal again. This is happening very often, does anyone know why? I can still see the screen and the code I am working on tho, I just cannot edit or type in anything into the file.

Thank you.

**Comment by navch** [comment] 2018-10-08 06:08
Hi @ninichang 
Please check out this issue https://github.com/adobe/brackets/issues/14515
I guess you could find a solution for this in comments.

Closing this as this looks duplicate of issue 14515.
Feel free to reopen if you have any concern.

**Closed by navch** 2018-10-08 06:08 UTC
