### ISSUE TITLE
Brackets can't be closed when full screen

### ISSUE THREAD

**Issue by kartikm** [adobe/brackets#10287] opened 2014-12-28 16:06 UTC
OS: Debian GNU/Linux, Sid/Unstable.
Brackets version: 1.1.0-15558

Steps to reproduce:
1. Open Brackets.
2. Full screen it.
3. Click on close button.
4. It won't close.
5. Unmaximize the Brackets.
6. Click on close button.
7. Brackets will close!

**Comment by peterflynn** [comment] 2015-01-03 01:36
Closing as a duplicate of #4611

**Closed by peterflynn** 2015-01-03 01:36 UTC
