### ISSUE TITLE
extend search to allow for "full word search"

### ISSUE THREAD

**Issue by tobibeer** [adobe/brackets#11776] opened 2015-10-05 05:04 UTC
provide a toggle next to the search input that allows to trigger search mode where the text is only matched considering both word boundaries, e.g `\bterm\b`...

So, `find` only matches...

* `this will find a`
* `click the "find" button`
* possibly also `find-123`, not sure

but not any of...

* `the finder does`
* `der Erfinder der modernen`

Alternatively — or in addition — provide a toggle that offers a concise overview of the most common regex elements via popup to scroll through... next to the regexp button.

**Comment by abose** [comment] 2015-10-06 11:10
Wouldn't a well crafted regex `find` all these texts?

**Comment by tobibeer** [comment] 2015-10-06 13:20
Yes, it would. It's just that not everyone is literate in that and finding a word rather than a match anywhere within a word is a very common desire.

**Comment by ficristo** [comment] 2016-08-17 16:30
Closing as a dupe of #11621

**Closed by ficristo** 2016-08-17 16:30 UTC
Labels: Enhancement, needs review
