### ISSUE TITLE
Right side bar 

### ISSUE THREAD

**Issue by danicoolpak17** [adobe/brackets#12646] opened 2016-08-03 18:27 UTC
Hey All, 
My Right Side Bar in extension dissappears as the brackets load and open. The bar which has Live Preview and Extension buttons on it. 
Any help. 

In the bottom in status bar it shows 11 errors. 

Thanks
Dani

**Comment by petetnt** [comment] 2016-08-04 07:20
Hi @danicoolpak17,

can you check that the `No Distractions` mode is not enabled in `View -> No Distractions`.

If it isn't, could you paste the errors here? You can see the errors by double clicking the errors-counter in the status bar (Console tab)

**Comment by danicoolpak17** [comment] 2016-08-06 21:55
Hey @petetnt 

I did all that but nothing worked , and some of the extensions where causing problems. As I uninstalled them and restarted the Brackets it showing now and updated it as well. 

now it is showing less errors here are the left ones. 

ErrorNotification.js:125 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUpwindow.console.error @ ErrorNotification.js:125

ErrorNotification.js:125 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDownwindow.console.error @ ErrorNotification.js:125

thirdparty.min.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

ErrorNotification.js:125 Cannot assign Ctrl-Shift-Up to io.emmet.increment_number_by_1. It is already assigned to edit.lineUpwindow.console.error @ ErrorNotification.js:125
ErrorNotification.js:125 Cannot assign Ctrl-Shift-Down to io.emmet.decrement_number_by_1. It is already assigned to edit.lineDownwindow.console.error @ ErrorNotification.js:125
thirdparty.min.js:13 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

**Comment by petetnt** [comment] 2016-08-06 22:34
So the problem is now fixed? :+1:  If you are able to tell which extension was causing the problems, it might be useful to report it to the extensions repository.

Those errors are soft errors due to multiple extensions/core trying to bind the same shortcuts which you can ignore.

Closing this as solved, feel free to reopen if the problem still occurs.

**Closed by petetnt** 2016-08-06 22:34 UTC
Labels: Waiting for user

**Comment by danicoolpak17** [comment] 2016-08-07 20:15
Yes, indeed i switched to console and saw it by myself , and managed to removed the extensions which were giving me errors. once i read them I understood that there should be no issue in app itself. 
now i am trying to find solution for shortcuts and how to assign them. 
Thanks @petetnt
