### ISSUE TITLE
Can't install Bracket on linux

### ISSUE THREAD

**Issue by RoteMinecraftIL** [adobe/brackets#12758] opened 2016-09-06 15:52 UTC
I downloaded the Brackets v1.7 64bit .deb to my Kubuntu 16.04.1 64bit pc, when typing `sudo dpkg --install Brackets.Release.1.7.64-bit.deb` on the admin account I get [this](https://gist.github.com/RoteMinecraftIL/33069153c73cfb6c79876a028d1d287c) crash log. HELP ME!

**Comment by NathanJPlummer** [comment] 2016-09-06 17:29
There's a couple fixes for this.

First, this [this page here](http://www.webupd8.org/2015/04/fix-missing-libgcrypt11-causing-spotify.html) has a solution, which basically explains where to get the old libcrypt.  The two libcrypts can work side by side.

You can also install brackets [from this PPA](https://launchpad.net/~webupd8team/+archive/ubuntu/brackets) which will handle this issue automatically.

To install from ppa in terminal type the following commands:

1. sudo add-apt-repository ppa:webupd8team/brackets
      - If asked to install key say "yes"
2. sudo apt-get update
3. sudo apt-get install

**Comment by ficristo** [comment] 2016-09-06 17:49
@NathanJPlummer thank you for answering.
This is a dupe of #10255 or #12380.
Especially for Linux users I suggest to try https://github.com/zaggino/brackets-electron/
Some context: https://github.com/adobe/brackets/issues/10255#issuecomment-243854796

**Closed by ficristo** 2016-09-06 17:49 UTC
