### ISSUE TITLE
Extract For Brackets Error — Creative Cloud Sign In Error

### ISSUE THREAD

**Issue by cwjensen** [adobe/brackets#13598] opened 2017-08-05 14:33 UTC
Hello, 

Brackets has the following issue in the attachment. 
![screen shot 2017-08-05 at 10 26 02 am](https://user-images.githubusercontent.com/30752635/28996210-6ca70b14-79c9-11e7-8b97-cc3528a11469.png)

**Comment by petetnt** [comment] 2017-08-07 13:14
Sorry @cwjensen,

the Extract for Brackets service has been discontinued for Brackets since 1.6. For more information, see http://blog.brackets.io/2016/04/14/update-about-extract-for-brackets-preview/?lang=en.

The extract feature is available in Dreamweaver CC, which is now based on Brackets if that helps.

Sorry again.

(Duplicate of https://github.com/adobe/brackets/issues/13341)

**Closed by petetnt** 2017-08-07 13:14 UTC
