### ISSUE TITLE
After you save the file, ctrl + z not be rolled back

### ISSUE THREAD

**Issue by yuwenlong** [adobe/brackets#11899] opened 2015-11-06 16:35 UTC
After you save the file, ctrl + z not be rolled back

**Comment by petetnt** [comment] 2015-11-06 16:42
Duplicate of #11826

**Comment by yuwenlong** [comment] 2015-11-06 16:45
The next version can fix?

**Comment by petetnt** [comment] 2015-11-06 16:46
Hopefully yes! If you have some steps that one can use to reproduce this to find out the root cause, do report them at #11826, no-one has found a bullet proof way to repro the issue yet.

**Closed** 2015-11-06 16:48 UTC
