### ISSUE TITLE
Feature Request (Terminal/CMD)

### ISSUE THREAD

**Issue by MandarSant** [adobe/brackets#12911] opened 2016-11-14 16:57 UTC
add Terminal/Cmd.exe to the brackets which will open within editor not seprate window [like this packge in atom](https://atom.io/packages/platformio-ide-terminal) or by default in editor like [VSCode](https://code.visualstudio.com/docs/editor/integrated-terminal)

**Comment by ficristo** [comment] 2016-11-14 18:27
Dupe of #12454

**Closed by ficristo** 2016-11-14 18:27 UTC
