### ISSUE TITLE
bug in ubuntu and kali...

### ISSUE THREAD

**Issue by giorga8** [adobe/brackets#12290] opened 2016-03-10 21:43 UTC
Hello, i found something non-comfortable, i think it is bug. when i click minimize button and it's minimized, after this i can't click on code ... 
![image](https://cloud.githubusercontent.com/assets/3426993/13685594/381a77c2-e722-11e5-9063-cf52b1eb15b9.png) it is stucked...

**Comment by ecwebservices** [comment] 2016-03-17 20:11
What is your Ubuntu version?

**Comment by giorga8** [comment] 2016-03-18 10:53
Ubuntu 15.10

**Comment by ecwebservices** [comment] 2016-03-18 14:30
I'll take a look on this. I have a 15.04 and 15.10 to test on so I'll check both just incase.

**Comment by giorga8** [comment] 2016-03-19 11:13
okey, thank you very much ^_^ I look forward to receiving your reply.

**Comment by giorga8** [comment] 2016-03-23 13:16
@ecwebservices  did u check it?

**Comment by ficristo** [comment] 2016-08-17 07:19
@giorga8 can you try `Debug \ Reload without extensions` and see if you can still reproduce?

**Comment by giorga8** [comment] 2016-08-20 00:01
okay i will try tomorrow

**Comment by ficristo** [comment] 2016-10-30 08:02
It seems to me an extension problem. I close this since we didn't hear back from you.

**Closed by ficristo** 2016-10-30 08:02 UTC
Labels: Waiting for user
