### ISSUE TITLE
View several live preview in Brackets

### ISSUE THREAD

**Issue by msmaxsoft** [adobe/brackets#10798] opened 2015-03-27 05:34 UTC
Hi there
I am using the new version Brackets
The problem I have with it
Always live preview two or more displays
And should always be made to feel refreshed
I searched the forum for my problem, but could not find
How can I solve my problem?

**Comment by redmunds** [comment] 2015-03-27 14:54
@msmaxsoft This is now possible using MultiBrowser Live Preview introduced in Brackets 1.2.

1. Use *File > Enable Experimental Live Preview* to turn it on
2. Live Preview will start in your default browser
3. For now, you'll need to copy url from default browser to other browsers (but we hope to make that easier in the future).

Is that what you were looking for?

**Comment by msmaxsoft** [comment] 2015-03-27 19:17
No no
My point is that when I use the live preview in Chrome
When changing the part repeated twice and must be constantly refreshed
Like the picture below

http://gemupload.ir/images/8mdwm4ejh71fcia4orj.png

**Comment by redmunds** [comment] 2015-03-27 19:24
I believe this is a duplicate of #10634.

**Comment by msmaxsoft** [comment] 2015-03-27 19:28
tnk's

**Closed** 2015-03-27 19:28 UTC
