### ISSUE TITLE
Ability to set default highlighting for extension-less files.

### ISSUE THREAD

**Issue by nextgenthemes** [adobe/brackets#10753] opened 2015-03-17 06:32 UTC
Because of this https://github.com/adobe/brackets/pull/10141 and playing around I just got too the unfortunate fact that we can not set a default highlighting for extension-less files.

Steps to reproduce:
1. Open a text/bash/any file without a extension
2. Select a highlighting language
3. At this point the top of the menu becomes available and says "Set as Default for .-Files" (I guessed the wording because my brackets is German)

Expected:
4. Make the grey "(default)" text actually move to what was selected.
5. Open a new extension-less file and have it highlighted with the previous "as default" selected highlighting language.

**Comment by prksingh** [comment] 2015-03-18 06:22
This makes sense to me. Adding to backlog for prioritization.

**Comment by ryanstewart** [comment] 2015-03-24 07:43
We don't do this with any extensions (we do it per file). So basically it looks like we need to bring this card back - https://trello.com/c/fH2JF9S6/338-101-user-selected-language-syntax-mode-per-file-extension-2

I'll move this from the icebox to the backlog and close the issue.

**Closed** 2015-03-24 07:44 UTC

**Comment by nextgenthemes** [comment] 2015-03-26 23:55
@ryanstewart From what I am getting of what you are saying, claiming you do this per file and not per extension is wrong.

Its set via file extension. I can change the default highlighting language for `.php` files, open another `.php` file, change the project and still get it highlighted with that selected default. The issue here is that you do not do this with files that have no extension but showing the option. (with with a `.` in there that does not exist).

I imagine that would be a very trivial code change to make this happen.

I have some feeling one of us got something wrong.

**Comment by nextgenthemes** [comment] 2015-03-27 00:00
Nevermind, now I am confused because its not working even I just tought I did it.

**Comment by MarcelGerber** [comment] 2015-03-29 18:00
@ryanstewart I'm sorry, but actually, languages can already be set per file extension using the Language Chooser.
![image](https://cloud.githubusercontent.com/assets/2641501/6886893/0b75f132-d64e-11e4-9963-7031f901da7b.png)

As soon as you click `Set as default for .less files`, the selected mode is always going to be used when opening a .less file.

**Comment by nextgenthemes** [comment] 2015-03-29 18:10
@ryanstewart @ryanstewart 
The thing is I already made comments about him being wrong, then deleting them because I was testing it and it seems this actually not works as you expect it from the menu. Its not even working per file. I set a php file to HTML highlighting then switched project and back and its displayed with php highlighting.

**Comment by MarcelGerber** [comment] 2015-03-29 18:59
It definitely works fine for me.
I changed a .less file to C highlighting, switched projects, restarted Brackets, and it's still highlighted as C.

**Comment by prksingh** [comment] 2015-04-01 12:05
Switching Less files highlighting to C does appear to work as mentioned. But I can reproduce the issue for extensionless files. This is what I did (windows):

Created a new file and saved it with no extension.
Switched mode from dropdown to Javascript and set it as default (Drop down still erroneously shows 'Text' as default)
Refresh brackets and the file opens as text

This aside however, I understood the original bug to also be about not having to explicitly *set as default* for a file with unknown mode -- So whatever mode is chosen for an unknown file becomes the mode by default.

**Comment by meeksdoteric** [comment] 2016-01-13 21:11
Hello everyone. I'm having an issue with this and was wondering if anyone knew the status or a workaround.

Steps to reproduce
1. Open .bash_profile in Brackets
2. Select language: Bash
3. Select "Set as Default for . Files"
4. Close Brackets
5. Re-open .bash_profile

The default language for . Files has not been retained🤔

**Comment by sprintr** [comment] 2016-01-13 21:17
@meeksdoteric I have been [fixed it](https://github.com/adobe/brackets/pull/11560), I haven't been free for a while to write some unit tests for it. It should come in 1.7.

**Comment by nextgenthemes** [comment] 2016-01-14 08:05
Easy fix I did a while ago: Switch do Atom, awesome editor.

**Comment by meeksdoteric** [comment] 2016-01-14 08:30
@nextgenthemes well that's funny, I just deleted Atom today in favor of Brackets ;)
