### ISSUE TITLE
under Ubuntu cannot open files with double click

### ISSUE THREAD

**Issue by NikosEfthias** [adobe/brackets#12009] opened 2015-12-16 11:44 UTC
```Release 1.5 experimental build 1.5.0-16538 (release cf9cf4698) 
build timestamp: Tue Oct 13 2015 12:00:44 GMT+0000```
when i double click or say open with brackets for a file it wont open just brackets opens with latest opened file in it. I must open file within brackets

**Comment by ldez** [comment] 2015-12-20 15:44
duplicate of #11921

**Closed** 2016-09-11 21:49 UTC
