### ISSUE TITLE
right click issue?

### ISSUE THREAD

**Issue by prbabayee** [adobe/brackets#12358] opened 2016-04-11 17:24 UTC
special thanks for the great work you have done and for the highly admirable effort on the project!
I wanted to suggest to add a few options to right click menu when the cursor is located on a selected text.
these options like copy,cut and paste can come really handy and can make Bracket more user-friendly.
 Thanks, again !

**Comment by petetnt** [comment] 2016-04-11 18:24
Hi @prbabayee,

there's an extension called [brackets-additional-right-click-menu](additional-right-https://github.com/caphodel/) that adds copying, pasting and other additional shortcuts to the right click menu. You can find it via File -> Extension Manager, typing "additional-right-click-menu" and selecting Install!

**Comment by ficristo** [comment] 2016-08-07 17:59
Closing as a duplicate of https://github.com/adobe/brackets/issues/12063

**Closed by ficristo** 2016-08-07 17:59 UTC
