### ISSUE TITLE
Read/Write .zip/.epub archives

### ISSUE THREAD

**Issue by shorshe** [adobe/brackets#10433] opened 2015-01-22 11:58 UTC
It would be great, if brackets could read/write a zip container directly. (Extension?)

**Comment by peterflynn** [comment] 2015-01-27 22:22
Seems like something that might be a better fit for a Brackets extension rather than a core feature.  Labeling as an extension idea -- this could be done via custom viewers, similar to [this comment](https://github.com/adobe/brackets/issues/10449#issuecomment-71740452).

**Comment by mackenza** [comment] 2015-04-03 17:58
@shorshe what is the use case you are looking at here?  i.e. if I click on a zip file in the project tree, are you expecting a file listing in the editor window? Something else? If the user clicks on the file in the file listing, are you expecting the extension to unzip the file (where?) and open an editor for it?

Also, by "write" do you mean adding new files to an archive? I think this might be a bit of feature creep as I am not sure I see the value in turning Brackets into an archive manager.  The initial read and then extract per file makes sense to me but not the writing of new files to an archive.

The reason I ask is I am considering whether this is a project I could take on.

**Comment by shorshe** [comment] 2015-04-03 18:28
In short:
Treat a zip/epup file transparently like a folder. 

I'm doing ePub related work everyday  this would spend up the turnaround times a lot. I'd greatly appreciate any developments in this direction!

**Comment by mackenza** [comment] 2015-04-03 19:35
I am not sure I would want to mess with the project tree. It seems like it's above my pay grade ;)

I will take a look at some options and perhaps suggest some workflow here for comment.

**Comment by shorshe** [comment] 2015-04-16 09:13
I'd make an argument against the feature creep. Brackets should not be an achieve manager,true. 
But treating an archive as just an other kind of folder would be different, in my opinion.
Other Texteditors do this too.

**Comment by prksingh** [comment] 2015-05-27 10:34
The issue is already marked 'extension idea'. I will close this from the list of active issues though, since this is unlikely to become a core feature.

**Closed by prksingh** 2015-05-27 10:34 UTC
Labels: Extension Idea
