### ISSUE TITLE
"Ctrl + Space" should move to the next entry when the code hint menu popped up.

### ISSUE THREAD

**Issue by metalbrick** [adobe/brackets#8142] opened 2014-06-17 09:34 UTC
Otherwise the shortcut is kind of useless.

**Comment by bmax** [comment] 2016-02-27 08:43
Hello,

I am new to OSS and thought this would be a fair bug to start. I hope it is still good to look into even though it is 2 years old. 

I think I have the basic idea of how to do this but I am stuck on 
` CodeHintList.prototype._keydownHook = function (event) {` function in CodeHintList.js, the problem is that event isn't picking up both commands ctrl+space, it's only picking up ctrl OR space. 

running `console.log(event); ` in the beginning of the _keydownHook function only shows keycode 17 (ctrl) or keycode 32 (space). Any help?

**Comment by redmunds** [comment] 2016-02-28 17:18
@bmax As mentioned in this [previous comment](https://github.com/adobe/brackets/issues/8142#issuecomment-49467533), on the event for the space char also verify that the ctrl key is down something like: `event.ctrlKey && (event.keyCode == KeyEvent.DOM_VK_SPACE)`

**Comment by petetnt** [comment] 2016-08-26 07:24
Fixed in #12251 / 	63962ce

**Closed by petetnt** 2016-08-26 07:24 UTC
Labels: low priority, starter bug
