### ISSUE TITLE
Awful font rendering in 1.1

### ISSUE THREAD

**Issue by dmxt** [adobe/brackets#10398] opened 2015-01-17 02:32 UTC
**Operating System:** Windows 8 Pro x64
**Font Rendering Engine:** [MacType](https://code.google.com/p/mactype/)

Brackets 1.0 with MacType font rendering looks beautiful.  When I updated to Brackets 1.1, the new version managed to block MacType custom font rendering resulting in a horrible font rendering. Perhaps Brackets 1.1 decides to force GPU to render fonts (awful!) or forces @font-face for some reason? 

See images for example:

Brackets 1.0
![2015-01-16_18-23-06](https://cloud.githubusercontent.com/assets/3248782/5787278/2cf357de-9dad-11e4-9604-e6fc614c286a.png)

Brackets 1.1 
![2015-01-16_18-20-37](https://cloud.githubusercontent.com/assets/3248782/5787281/338baa38-9dad-11e4-9d2a-fb5231049ec3.png)

It's this bad that I have to revert the update back to 1.0 and will stay on 1.0 forever until it's solved!

**Comment by svenvNL** [comment] 2015-02-01 10:37
I tink It has to do with brackets-shell. Google has changed font rendering in chrome some time ago. Brackets-shell uses Chrome embedded framework, so that's the problem I think.

**Comment by ralder** [comment] 2015-03-19 13:08
You need to run Brackets.exe with flag --disable-direct-write (you may add it in field target in properties of shortcut Brackets)

**Comment by dmxt** [comment] 2015-03-20 02:07
The flag `--disable-direct-write` solved the problem. Hopefully it will be configurable through the config.

Thanks.

**Comment by prksingh** [comment] 2015-03-20 10:57
Thanks @ralder for the solution. Closing as a duplicate of #10698

**Closed by prksingh** 2015-03-20 10:57 UTC

**Comment by dmxt** [comment] 2015-03-21 18:11
Please reopen this issue. The flagging solution is quick hack fix at best, because it doesn't work well in other situation such as:

* You only can add flag to shortcut file.
* I cannot start Brackets with flag through right-click context menu, because it starts with original .exe without flag.
* FileZilla doesn't work properly with flag argument when I try to edit more than one file through FileZilla, it just doesn't open second file.

I'm rolling back to Brackets 1.0 because of this. I hope that it will be possible to add directwrite option to the config.

**Comment by dmxt** [comment] 2015-03-21 18:16
@prksingh Reopen the issue, please.

**Comment by prksingh** [comment] 2015-03-22 01:48
@dmxt I had closed this issue because it appeared to be a duplicate of issue #10698

Are you saying that this issue is different from 10698? Otherwise we can continue to track it there

**Comment by dmxt** [comment] 2015-03-23 01:02
@prksingh My issue is older than his, it doesn't make sense to close an issue if someone else make a repetitive post? I'm not complaining, it just doesn't make sense... but if you think it's right thing to do, then that's fine, I have nothing against it.

**Comment by prksingh** [comment] 2015-03-23 09:22
I saw that your issue was older but the 10698 had more discussion and information on it.

**Comment by dmxt** [comment] 2015-04-15 11:08
@prksingh The issue you chose to keep open is later closed by @ralder with a reason to continue the issue on this very thread which is long closed.

In result the font rendering problem is still not properly solved and I'm truly offended on how @ralder handled this.

---

To keep in topic: The solution to this issue is to add directwrite option to the config, instead of using flag parameters because it's not well supported with other programs.

**Comment by prksingh** [comment] 2015-04-15 16:34
Sorry for any offence. The other issue is still open (though unresolved), I have added a 'needs review' tag so the team can look at it and add a priority to the issue

**Comment by nethip** [comment] 2015-04-16 06:22
@dmxt While we figure out how to solve this issue, did you try passing the parameter `--disable-direct-write` to Brackets shortcut. In order to do that, you could add the parameters to the `Target` edit box, present in the shortcut's *Properties* dialog. So the Target edit box would look something like

`"C:\Program Files (x86)\Brackets\Brackets.exe" --disable-direct-write`

Can you try this and let me know if this works fine?

**Comment by dmxt** [comment] 2015-04-21 13:27
@nethip 
Yes, as mentioned above, the parameter `--disable-direct-write` solves the very issue. However, passing the parameter isn't an option for me because it causes miscellaneous problems with third party program interaction, for an example:

* FileZilla doesn't open multiply files properly with the argument, instead of opening as tab, it opens as new window which disrupts my work flow. 
* Opening the file via context menu doesn't open with the argument, instead it opens the default .exe file without arguments.

I would list more problems, but I immediately downgraded to Brackets 1.0 so I'm not on Brackets >1.1 long enough to find other problems.

As mentioned above, I suggested making direct-write configurable through the config file and we can declare the entire issue solved.

Thanks.

**Comment by nethip** [comment] 2015-05-04 10:41
@dmxt The problem in making Brackets configurable for this workflow is the fact that, this needs to be handled at the `brackets-shell` (The thin wrapper which encloses the editor) side of things and we do not have any infrastructure as of now to to make `brackets-shell` configurable. As of now we just have `Brackets` side of things configurable, through `.brackets.json` but not `brackets-shell`. 

In 1.3, we have added command line support to Brackets, meaning Brackets can be open from command line by optionally passing file names as arguments. In order to do this, we have created a command script present inside `<INSTALLDIR>/command` folder. This is essentially the script.

`start Brackets.exe $*`

You could tweak this to pass `--disable-direct-write` along with the other parameters. That way whenever Brackets is invoked from command line using `brackets <filename/folder name>`, `--disable-direct-write` is automagically passed to Brackets.

Also about the "Open With Brackets" option(which is now added in 1.3), could you tweak this registry entry.

`HKCR\*\Shell\Brackets\Command` to have this additional option.

Note: Be sure to handle this carefully as this involves tweaking the registry.

You mentioned about other issues with 1.2/1.3. Could you describe what sorts of problems you are running into using 1.2/1.3?.
