### ISSUE TITLE
Cannot Use Ctrl+V Shortcut for Paste Function in New Brackets Window

### ISSUE THREAD

**Issue by x0rsw1tch** [adobe/brackets#10974] opened 2015-04-22 20:07 UTC
Steps to Recreation:
1. Open Brackets.
2. Use Debug Menu > Select "New Brackets Window"
3. Inside text editor, Try to paste something in plain-text using Ctrl+V

What Happens:
- Clipboard contents are not pasted into editor.
- No error messages are displayed in console.

Did This Work in a Previous Version:
- Unknown

Brackets Version:
Release 1.2 build 1.2.0-15697 (release 8f82e2a97) 

OS:
Windows 8.1 Pro w/ Media Center (x64)

Occurs Without Extensions loaded:
Yes

Workarounds:
- Use Shift+Insert
- Use Edit Menu > Paste

UPDATE:
This seems to occur with several shortcuts (tested with F5, Shift+F5), not just Ctrl+V. Did not test with others.

**Comment by peterflynn** [comment] 2015-04-22 23:32
This is a duplicate of #8135.  Virtually all shortcuts will be broken in the second window, which is one of several important reasons to avoid using this unofficial testing feature -- see notes in the original bug for details.

**Closed by peterflynn** 2015-04-22 23:32 UTC
