### ISSUE TITLE
Add AutoFormatter please

### ISSUE THREAD

**Issue by mo-Oka** [adobe/brackets#12948] opened 2016-11-27 15:57 UTC
Please, add a feature which allows to format code to standard by one click.

Like such code:

```
    <body>
        <h1>Посещения по городам</h1>
<table>
<tr><td>Город</td><td>Посещения</td><td>Страниц</td><td>Время</td></tr>
<tr><td>СПб</td><td>199</td><td>18,02</td><td>00:13:45</td></tr>
<tr><td>Москва</td><td>69</td><td>1,48</td><td>00:00:44</td></tr>
<tr><td>Киев</td><td>5</td><td>13,43</td><td>00:18:07</td></tr>
</table>
    </body>
```

Should be:

```
   <body>
      <h1>Посещения по городам</h1>
      <table>
         <tr>
            <td>Город</td>
            <td>Посещения</td>
            <td>Страниц</td>
            <td>Время</td>
         </tr>
         <tr>
            <td>СПб</td>
            <td>199</td>
            <td>18,02</td>
            <td>00:13:45</td>
         </tr>
         <tr>
            <td>Москва</td>
            <td>69</td>
            <td>1,48</td>
            <td>00:00:44</td>
         </tr>
         <tr>
            <td>Киев</td>
            <td>5</td>
            <td>13,43</td>
            <td>00:18:07</td>
         </tr>
      </table>
   </body>
```

Thanks!

**Comment by haslam22** [comment] 2016-11-27 19:14
You can use an extension to do this, something like [Beautify](https://github.com/brackets-beautify/brackets-beautify) will produce the desired output.

**Comment by ficristo** [comment] 2016-11-28 18:47
Dupe of #11031

**Closed by ficristo** 2016-11-28 18:47 UTC
Labels: Extension Available
