### ISSUE TITLE
Can't type ' and " in Ubuntu 14.04 with International Keyboard

### ISSUE THREAD

**Issue by Fragalli** [adobe/brackets#10633] opened 2015-02-19 13:54 UTC
Hi, i can't type quote marks on Brackets, i'm using Ubuntu 14.04 and the newest version of brackets
I installed some plugins, don't know if they interfere....

My plugins: Beautify, Brackets File Icons, Brackets Git, Brackets OutLine List, Code Folding, CSSLint, Indent Guides, Minimap, Monokai Dark Soda, Paste and Indent, QuickDocsJS, White Space Sanitizer.

This bug is known ???
Sry for my bad english

Greetings

**Comment by redmunds** [comment] 2015-02-19 15:55
@Fragalli Use *Debug > Reload Without Extensions* to quickly determine if it's caused by an extension.

**Comment by Fragalli** [comment] 2015-02-19 16:13
@redmunds the error persists

**Comment by redmunds** [comment] 2015-02-19 16:24
Which language is your keyboard? What's the key combination?

**Comment by Fragalli** [comment] 2015-02-19 16:41
i'm brazillian, but my keyboard is US International, like this: http://www.adrenaline.com.br/files/upload/noticias/2013/08/kerber/08_g1511_03.jpg

doesn't work when typing ' or SHIFT + "

**Comment by peterflynn** [comment] 2015-02-19 22:47
@Fragalli Are you unable to type `'` and `"` just in the editor area, or is this also a problem in places like the Find bar?

If you go to this page - http://www.asquare.net/javascript/tests/KeyCode.html - and type `'` (without Shift), what do you see?

**Comment by peterflynn** [comment] 2015-02-19 22:47
CC @RaymondLim to see if this sounds familiar at all

**Comment by RaymondLim** [comment] 2015-02-19 23:46
@Fragalli You're posting an image showing your physical keyboard. But you may be actually using the Brazilian keyboard layout as shown in this [wiki page](http://en.wikipedia.org/wiki/Portuguese_keyboard_layout). If so, then the key you're pressing for `'` and `"` is actually a dead key and won't input anything into the editor by pressing it alone. The actual key for  `'` and `"` is the one to the left of the numeric key 1 on the top row.

**Comment by Fragalli** [comment] 2015-02-20 17:32
@peterflynn í see '0' in the onKeyUp column

**Comment by peterflynn** [comment] 2015-02-20 19:16
@Fragalli So based on your test, it sounds like typing `'` or `"` without Alt also doesn't work in your web browser -- is that correct?  (If it's sending a keycode of 0, I can't imagine that it would work).  Does it work correctly in other apps?

**Comment by RaymondLim** [comment] 2015-02-22 01:51
@Fragalli So you're actually using US international keyboard layout. The behavior you're seeing is the correct behavior. See http://dry.sailingissues.com/us-international-keyboard-layout.html for dead keys in red that require to hold down a modifier key.

You can close this since it is the correct behavior with US international keyboard layout and nothing can be done in Brackets to change this behavior.

**Comment by Fragalli** [comment] 2015-02-22 14:39
so, the alt + ' is the correct behavior ??? LOL
only happens in brackets guys

**Comment by RaymondLim** [comment] 2015-02-22 17:16
@Fragalli I don't have Linux to verify your claim that it only happens in Brackets, but I did test on Mac and Windows 7 with US international keyboard layout. On Mac the layout is called "U.S. International - PC". And it behaves the same way in all browsers. 

Alternately, you can type `'+Space`to insert the quote on these platforms or simple type the quote character twice since it is used as a dead key for typing accented character like á by hitting `'+a`.

Are you sure you're not hitting the quote character twice in other application? That'll be strange if you get the quote on a single hit in other applications on Linux.

**Comment by Fragalli** [comment] 2015-02-23 16:59
yeah, i hit ' + space to insert the quote alone, or ' + a to insert á, but this behavior dont happens in brackets

btw, you know why alt + ' works ?

**Comment by RaymondLim** [comment] 2015-02-23 20:49
@Fragalli `Alt + '` works because it is one of the altGr shortcuts defined for US international keyboard layout.

I tried to log into my Ubuntu 11.1 32bit VM and both `'+space` and `'+a` are working fine for me in Brackets 1.1 release (ea908cae5). Not sure why they're not working for you.

@nethip Can you try on to reproduce the issue @Fragalli is still experiencing?

**Comment by Fragalli** [comment] 2015-02-24 12:48
hmmm, i understood... ok

btw, my ubuntu is 14.04 64bits, and i use the version 1.2 Pre Release - Linux

**Comment by peterflynn** [comment] 2015-02-25 08:52
@Fragalli Does the stable 1.1 build behave any differently for you?

**Comment by ghominejad** [comment] 2015-02-25 12:46
I have the same problem even after removing all the extensions. i hadn't any problem before.
I'm using ubuntu 14.04 - 64bits and i have installed it from :
`https://github.com/adobe/brackets/releases/download/linux-cef-2171/Brackets.Release.1.2.64-bit.deb`

**Comment by nethip** [comment] 2015-02-26 08:26
@ghominejad  Are you saying "Ctrl + C" is not working? Because what @Fragalli is reporting is to do with `'` and `"`. Can you confirm? 

@ghominejad @Fragalli  It would be really valuable for us if you can tell us if the behavior(s) you are observing is happening with Brackets 1.1 as well.

**Comment by ghominejad** [comment] 2015-02-26 08:56
I couldn't type anything in brackets 1.2!, i tested it without any extension but no matter...
I had to uninstall it and install v1.1 and everything is normal in v.1.1 but with a little slow.

**Comment by nethip** [comment] 2015-02-27 11:19
@ghominejad Thanks for trying out Brackets 1.2! I am not able to repro this behavior with Brackets 1.2 on my Ubuntu VM. I may be missing something. Can you try reloading brackets without extensions?. To do that choose *Debug->Reload Without Extensions* menu. And also please post any messages you are seeing in the console of developer tools. 

About Brackets 1.1 being slow,  let us know if after reloading brackets without extensions, you are still seeing Brackets 1.1 to be slow.

**Comment by ghominejad** [comment] 2015-02-27 11:44
I tried it without any extensions and the keyboard didn't work at all.
Please let me to try v1.2 again at the later time.
but v1.1 (reloaded without extensions) console errors  :
```
Download the React DevTools for a better development experience: http://fb.me/react-devtools /thirdparty/react.js:4356
Brackets reloaded with extensions disabled /document/DocumentCommandHandlers.js:1656
NodeSocketTransport - start /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:87
Exception in 'activeEditorChange' listener on 
Object {_eventHandlers: Object, on: function, off: function, one: function, trigger: function…}
 TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at eval (/view/MainViewManager.js:1057:29) /utils/EventDispatcher.js:224
Assertion failed: /utils/EventDispatcher.js:225
Exception in 'activeEditorChange' listener on 
Object {_eventHandlers: Object, on: function, off: function, one: function, trigger: function…}
 TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at setActivePaneId (/view/MainViewManager.js:368:21) /utils/EventDispatcher.js:224
Assertion failed: /utils/EventDispatcher.js:225
Exception in 'activeEditorChange' listener on 
Object {_eventHandlers: Object, on: function, off: function, one: function, trigger: function…}
 TypeError: Cannot read property 'addModeClass' of undefined TypeError: Cannot read property 'addModeClass' of undefined
    at eval (/view/ThemeManager.js:268:54)
    at j (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:26860)
    at Object.k.add [as done] (file:///opt/brackets/www/thirdparty/thirdparty.min.js:559:27169)
    at refresh (/view/ThemeManager.js:260:45)
    at eval (/view/ThemeManager.js:357:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at _notifyActiveEditorChanged (/editor/EditorManager.js:165:17)
    at _handleCurrentFileChange (/editor/EditorManager.js:182:9)
    at Object.trigger (/utils/EventDispatcher.js:222:40)
    at setActivePaneId (/view/MainViewManager.js:368:21) /utils/EventDispatcher.js:224
Assertion failed: /utils/EventDispatcher.js:225
 
```

**Comment by ghominejad** [comment] 2015-03-01 18:08
I think it was chrome's problem, because occasionally after working a lot with chrome, i can't use my keyboard anymore. it happens when i have my browser open for a long time (3 days) with a lot of page opened.
i have reset my computer and i have installed newer linux version of brackets and it works and everything is ok. but i don't know the problem was the brackets version or my computer's memory. the url : 
https://github.com/adobe/brackets/releases/tag/release-1.2-prerelease1-Linux

**Closed** 2015-08-27 16:37 UTC

**Comment by pras14587** [comment] 2018-01-21 05:33
Please choose US keyboard layout.
And also remove other layout, most probably you have wrongly selected UK.

**Comment by cztomczak** [comment] 2018-02-06 13:36
Possibly related issue: https://github.com/adobe/brackets/issues/13721 ("Keyboard pt_BR")

**Comment by RushiBShah** [comment] 2020-05-15 07:37
@Fragalli 
Can you pls try below command in ubuntu shell?

setxkbmap -layout us

-- this command set up your keyboard layout to US and it worked for me
