### ISSUE TITLE
Internationalization problem in Ubuntu

### ISSUE THREAD

**Issue by dvshapkin** [adobe/brackets#13811] opened 2017-11-06 05:26 UTC
### Description

The Russian font is not displayed in the dialog box for opening a file or directory (see screenshot).
![2017-11-06 12-02-42](https://user-images.githubusercontent.com/6525348/32426528-8dbbed2a-c2ed-11e7-913f-6462d2a68503.png)

### Steps to Reproduce

1. File \ Open
2. File \ Open directory

### Versions

Ubuntu 16.04 / 16.10 / 17.10
sprint 11 build 1.11.0-17524 (release 86b5e2d4e)

**Comment by ficristo** [comment] 2017-11-09 19:37
Duplicate of #13738

**Closed by ficristo** 2017-11-09 19:37 UTC
