### ISSUE TITLE
change default landing page in "Extension Manager"

### ISSUE THREAD

**Issue by wshwshni** [adobe/brackets#12556] opened 2016-06-29 22:14 UTC
Hi there,
Please change the default landing page in "**Extension Manager**" , to be "**installed**" instead of "**Available**";
as we open this section to Enable / disable existing Extension, or to copy Extension name to our Friends.
also we have global internet issue in Egypt, and this page ("**Available**") take a awhile to load, based on internet speed. 
So, Please Help ! :v:  :D
![ab fw](https://cloud.githubusercontent.com/assets/10023880/16470269/8b8efa9c-3e55-11e6-85cf-25dbd9a24bd7.png)

**Comment by Tusko** [comment] 2016-07-03 08:57
+1

**Comment by petetnt** [comment] 2016-08-02 19:38
Duplicate of #11567, :+1:  for the idea from me though

**Closed by petetnt** 2016-08-02 19:38 UTC
