### ISSUE TITLE
Memory leak troubleshooting

### ISSUE THREAD

**Issue by lkrnac** [adobe/brackets#10599] opened 2015-02-14 22:05 UTC
I am experiencing memory leak in Adobe Brackets or some plugin. How can I figure out which plugin is it? Is it only uninstall + observe method?

**Comment by MarcelGerber** [comment] 2015-02-15 10:13
Yeah, Brackets (unfortunately) leaks memory in some places.
Known spots are (see also https://groups.google.com/forum/#!topic/brackets-dev/98FAtTKEKYw):
* Extension Manager (open and close): fixed in Release 1.2, coming soon
* Quick Open (open and close, big one)
* Reload with/without extensions

The easiest way to find if a leak is caused by Brackets itself or an extension is to use `Debug > Reload without extensions` and see if it still leaks memory.

**Closed** 2015-02-15 12:32 UTC

**Comment by schroef** [comment] 2016-03-26 04:17
Its there a other method to check this problem. Ive got one file and if i work in this at a certain moment brackets goes beserk. showing and hiding some sort of alert window which show and hides constant
