### ISSUE TITLE
In kali linux installed brackets out of the first garbled, how to solve it?

### ISSUE THREAD

**Issue by chonymeg** [adobe/brackets#13814] opened 2017-11-06 15:29 UTC
![2017-11-06 23-13-19](https://user-images.githubusercontent.com/33425421/32448518-0f59ce0e-c34a-11e7-8547-252879986b99.png)

**Comment by kiroma** [comment] 2017-11-06 18:53
Known issue at #13738, please look at #13731 for resolution.
In essence, to solve it please install libpangoft2-1.0-0 >= 1.40.5 or unpack the libs from the package to path of Brackets installation.

**Comment by ficristo** [comment] 2017-11-09 19:37
Duplicate of #13738

**Closed by ficristo** 2017-11-09 19:37 UTC
