### ISSUE TITLE
Code folding doesn't play well with View > Line Numbers toggle

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets#10864] opened 2015-04-09 22:42 UTC
1. Uncheck _View > Line Numbers_
   - Result: code folding triangles are too close to the left edge of the editor -- need more padding
2. Re-check _View > Line Numbers_
   - Result: code folding is on the _left_ of the line numbers now -- should be to the right

This seems relatively edge-casey, to the point where I could envision shipping 1.3 without fixing this.  I suspect most people who have line numbers hidden will also want folding triangles hidden, and they're unlikely to re-enable line numbers afterward (and issue 2 is easy to work around).

**Comment by VitorLuizC** [comment] 2015-08-13 20:00
<a href="https://gyazo.com/db7cb0136c4c3ba5ca3649b332c179ac"><img src="https://i.gyazo.com/db7cb0136c4c3ba5ca3649b332c179ac.gif" /></a>

**Comment by petetnt** [comment] 2016-08-27 17:33
Fixed in #12673

**Comment by zaggino** [comment] 2016-08-29 01:24
Re-opening as #12673 had to be reverted.

**Comment by ficristo** [comment] 2017-03-15 18:57
I cannot reproduce anymore. Fixed by #10864

**Closed by ficristo** 2017-03-15 18:57 UTC
Labels: F Code Folding, low priority
