### ISSUE TITLE
Would be awesome to Double-Click to hide Find window

### ISSUE THREAD

**Issue by tonybrasunas-sighten** [adobe/brackets#13617] opened 2017-08-17 00:21 UTC
### Description

This is a feature request for an easier way to hide the bottom pane.  

In Dreamweaver, one could double click on the top of the Find window to hide it. This Find window also appears during Linting and during use of many other plug-ins and features.

To close these window(s), as far as I can tell, the only way is to click the 'X' in the right hand corner. Admittedly, this is not too hard to do. Just click the 'X.' But when in superuser mode, flying around the IDE, it would be great to have a gesture easier to access than that 'X.' These lower pane windows appear all the time. It would be great to have an easy way to hide them.

**Expected behavior:**

After doing find-in-project, double-clicking (or use of some other gesture) on the top of the Find pane will hide it.

**Comment by petetnt** [comment] 2017-08-17 07:27
Hi @tonybrasunas-sighten!

This sounds like a good feature to me! Would you like to contribute it to `brackets`? We can help you get started with the code base and will guide you through the contribution path 👍

**Comment by tonybrasunas-sighten** [comment] 2017-08-18 02:10
I'd love to contribute to brackets and might be able to in the future. Right now, with a four-month-old son and a new job, I unfortunately don't have a spare minute.

I do love brackets and use it every day, and for now glad to contribute this as at least an idea to improve it for everyone.

**Comment by petetnt** [comment] 2017-08-18 05:38
@tonybrasunas-sighten congrats for the kid and the new job! I'll be tagging this is a starter issue and a pick me up so someone has a chance to take it up! 

Thanks for your support! 👍

**Comment by aistosi** [comment] 2017-08-19 12:22
Hi there! Would like to take a look at this.

**Comment by petetnt** [comment] 2017-08-19 14:56
Hi @aistosi!

That's great! See the article [How to hack on Brackets](https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets) to get started with the Brackets codebase. If you have any questions, feel free to post them here! We also have a [Slack channel](https://brackets.slack.com) for day-to-day communication. (You can join by sending a mail to admin@brackets.io with the subject line `slack registration request` specifying the email addresses you would like to register).

**Comment by aistosi** [comment] 2017-08-20 00:22
Hi @petetnt,

Would you know how to debug brackets from another IDE? I am using Webstorm and would like to debug Brackets from there. I read the debugging guide could not find similar info. You help is much appreciated.

**Comment by petetnt** [comment] 2017-08-20 17:46
Hello again!

Brackets can be debugged via the [Remote Debugging Protocol](https://chromedevtools.github.io/devtools-protocol/) that's exposed at http://localhost:9329. Here's the guide using it with Webstorm: https://www.jetbrains.com/help/webstorm/run-debug-configuration-chromium-remote.html

**Comment by nikshepsvn** [comment] 2017-08-23 13:45
Hey @petetnt mind if I give this a go too? Would be my first open source contribution :)

**Comment by petetnt** [comment] 2017-08-23 13:51
Hi @nikshepsvn! 

There seems to be a PR for this feature already in here: https://github.com/adobe/brackets/pull/13624 but you can help us by reviewing and testing it! Issue triaging and code reviewing are much appreciated contributions to OSS too 👍

**Comment by swmitra** [comment] 2017-08-23 17:33
@petetnt I had a look at the PR just now. It looks good to me for this particular use case. But what I was thinking,  can't we target this for all bottom panels? This brings one more option for us to evaluate. As the current bottom panels gets stacked up on each other,  it reduces the effective coding area.  Can't we just introduce a single resizable bottom panel container and have all the bottom panels appear as tabs?  Only trick would be to have an additional parameter for tab head string which might be a breaking change for user extensions.

**Comment by petetnt** [comment] 2017-08-23 17:43
@swmitra IIRC @ficristo has an old PR that was quite far with that a long while back. I am okay with having this as a stop gap solution

**Comment by ficristo** [comment] 2017-08-23 18:28
@swmitra FWIW a couple of years ago I put together https://github.com/adobe/brackets/pull/11586
From what I can remember, that PR still had some problems and messed a bit with the API.
Since stacked panels pained me to no end I created https://github.com/ficristo/brackets-panels-hack

**Comment by tonybrasunas-sighten** [comment] 2017-08-23 19:16
IMHO, having the stopgap available soon would be a big win. It's exciting that the PR looks good, and the fact that it looks relatively minor says a lot about Brackets' underlying code quality.

The vision of tabbed bottom panels is a very good one too, and @ficristo your plugin looks very cool (despite its `hack`y name). I'll give it a go and see if it doesn't break anything in my current setup. 

(The two ideas aren't mutually exclusive of course. Double-click to close Search now, tab-able bottom panel with double-click to close later.)

**Comment by aistosi** [comment] 2017-08-24 01:05
So is this basically done. Finally have some time to work on this

**Comment by lukaszsobek** [comment] 2017-08-26 22:20
the PR seems to solve the issue requested and can be reproduced in other panels as well, or even be applied in a general feature with very little rewrite if the bottom panels are to be unified in future.

**Comment by jibraniqbal666** [comment] 2017-09-25 10:20
Hi, there i would to work on this feature where do i start? I have already got the source and everything on my Linux environment where should i make changes? thank you.

**Comment by swmitra** [comment] 2017-09-25 11:31
@jibraniqbal666 Thanks for showing interest in contributing to Brackets community. Incidentally this particular feature is already implemented and part of Brackets 1.11 released today!

**Comment by Nepaltechguy2** [comment] 2017-10-26 03:43
Should this be closed?

**Comment by swmitra** [comment] 2017-10-26 06:39
Closing as implemented and released with Brackets 1.11.

**Closed by swmitra** 2017-10-26 06:39 UTC
Labels: Enhancement, PICK ME UP, Starter bug

**Comment by Hirse** [comment] 2018-03-19 21:29
This issue was moved to Hirse/brackets#1
