### ISSUE TITLE
Wrong order when switching documents using Ctrl+Tab or Ctrl+Shift+Tab

### ISSUE THREAD

**Issue by GameplayJDK** [adobe/brackets#10776] opened 2015-03-21 13:23 UTC
I noticed this as I wanted to switch using the shortcut keys after changing the order of the "Working Files":

![bug00](https://cloud.githubusercontent.com/assets/4069263/6765185/c3dad4d8-cfd5-11e4-85b0-9e49dfd10b31.gif)

**Comment by prafulVaishnav** [comment] 2015-03-23 08:36
@GameplayJDK Are you able to consistently reproduce the issue? Can you tell if there is any console error ( open Debug -> Show Developer Tools & see console tab)

**Comment by petetnt** [comment] 2015-03-23 11:40
Duplicate of #9538 , being tracked at #6273

**Comment by peterflynn** [comment] 2015-03-23 20:05
Closing.  Ctrl-Tab moves in MRU order (like most other code editors, but unlike web browsers). We plan to add alternate shortcuts in a future version to move in linear order; in the meantime, you can use my File Navigation Shortcuts extension.

**Closed** 2015-03-23 20:06 UTC

**Comment by prafulVaishnav** [comment] 2015-03-24 04:27
@peterflynn I think ctrl-tab should go through each file in the working set in MRU order before repeating the file. In snapshot above, ctrl-tab is not traversing through all files before repeating.

**Comment by prksingh** [comment] 2015-03-25 09:20
@prafulVaishnav I see all files in working set being selected at least once. It may appear that ctrl + tab moves to 'Readme.md' from 'convert_to_unix_style_line_ending' but I think that may be because the gif ends and repeats

**Comment by prafulVaishnav** [comment] 2015-03-25 09:43
@prksingh Initially I also thought the same. But when I extract the gif into frames, I came across this anamoly. @GameplayJDK Can you please confirm this?

**Comment by GameplayJDK** [comment] 2015-03-25 16:56
It goes through all files before repeating. I might missed the right moment to stop the gif: 

![demo](https://cloud.githubusercontent.com/assets/4069263/6830069/d8741586-d317-11e4-9e05-ffbba6126eb8.gif)
(this one does not repeat)

(If it's a feature that it goes through 'em in a non-linear order, I'm sorry, because I didn't know that :disappointed: )

**Comment by prksingh** [comment] 2015-03-27 04:40
Thanks @GameplayJDK. Yes it is a feature. You can use @peterflynn 's extension https://github.com/peterflynn/brackets-editor-nav if you want a non MRU navigation as mentioned above.
