### ISSUE TITLE
extension / whitespace

### ISSUE THREAD

**Issue by maxgrass** [adobe/brackets#10891] opened 2015-04-13 16:52 UTC
Mouse Right click deletes the word.

I could not localize the problem deeper, since this has been discussed on trello and considered more or less like a important feature, maybe worth looking into it, since the author seems not to be an active user and **the issue might be with brackets rather than with plugin**.

https://github.com/DennisKehrig/brackets-show-whitespace/issues/42

**Comment by prafulVaishnav** [comment] 2015-04-14 04:32
@maxgrass Please reload Brackets without Extensions (Debug > Reload Without Extensions) to make sure its not due to any extensions. You have already filed this bug to extension author. If you are sure it is caused by that particular extension not by core Brackets, please close this bug.

**Comment by maxgrass** [comment] 2015-04-14 04:51
very helpful.

**Closed** 2015-04-14 04:50 UTC
