### ISSUE TITLE
LB: LOC: fr_FR: WIN/MAC: truncation issue in "To use a local server, enter a URL like http://localhost:8000/"

### ISSUE THREAD

**Issue by Tania-Jiacomini** [adobe/brackets#11812] opened 2015-10-13 07:41 UTC
String "To use a local server, enter a URL like http://localhost:8000/" is truncated in French screen.

EN:
To use a local server, enter a URL like http://localhost:8000/

FR:
Pour utiliser un serveur local, entrez une URL telle que http://localhost:8000/

Translation really cannot be shortened here, please adjust layout.

![enu_brackets1 5_lk1_164_1 5 0 16538](https://cloud.githubusercontent.com/assets/2284774/10448649/73c12672-718e-11e5-959c-9f3504973fa2.jpg)

![fra_brackets1 5_lk1_164_1 5 0 16538](https://cloud.githubusercontent.com/assets/2284774/10448652/79073608-718e-11e5-992a-66fb99c79e2a.jpg)

**Comment by ficristo** [comment] 2016-11-08 19:10
Dupe of #11460

**Closed by ficristo** 2016-11-08 19:10 UTC
Labels: French, loc: truncation/layout
