### ISSUE TITLE
Grave accent char problem

### ISSUE THREAD

**Issue by traBolic** [adobe/brackets#12903] opened 2016-11-11 15:54 UTC
Hi screenshot describing itself.

![image](https://cloud.githubusercontent.com/assets/5789670/20220851/cc682d6c-a837-11e6-8227-500028075095.png)

**Comment by ficristo** [comment] 2016-11-12 06:59
The JSLint version that come with Brackets it is really outdated. 
My advice is to switch to ESLint.

Closing as dupe of https://github.com/adobe/brackets/issues/12000

**Closed by ficristo** 2016-11-12 06:59 UTC
Labels: F Code Inspection (Linting)

**Comment by traBolic** [comment] 2016-11-14 18:26
I did install ESLint but nothings changed. Still getting error 
![image](https://cloud.githubusercontent.com/assets/5789670/20277265/86c9d224-aaa8-11e6-9b55-afd9e8d4407a.png)

**Comment by ficristo** [comment] 2016-11-14 18:38
I think you need the `es6` environment: `/*eslint-env es6*/`
