### ISSUE TITLE
Wrong file mapped to file contents

### ISSUE THREAD

**Issue by andrewkfiedler** [adobe/brackets#12668] opened 2016-08-11 22:53 UTC
I've noticed a few times that the contents I'm looking at for a file are wrong (they belong to another file).  I'm not sure how to recreate this issue, but I will mention that I'm using git integration.  

The issue is, the original file contents for that filename will be overwritten by the other file's contents if you happen to save.  

I almost got into an unfortunate situation, but luckily was able to recover my file contents from my running instance of the page (using the sources in the developer tools).  

Has anyone else encountered this issue?

**Comment by petetnt** [comment] 2016-08-11 22:56
Hi @andrewkfiedler,

this issue is a duplicate of #12317, no idea what causes it though 😕 

Let's continue the discussion in #12317 👍

**Closed by petetnt** 2016-08-11 22:56 UTC
