### ISSUE TITLE
Error- crash window current and closes the current file working. Error- Choca la ventana actual cerrando el archivo actual.

### ISSUE THREAD

**Issue by macdg** [adobe/brackets#12173] opened 2016-01-29 18:02 UTC
English:Error- crash window current and closes the current file working. Spanish: Error- Choca la ventana actual cerrando el archivo actual.

English: I have version Release 1.6 version experimental 1.6.0-16680 (release 3df0ac6fa) , when syntax errors occur after correcting the error and save, the current window is displayed in white and the current window is closed.
Thanks and greetings.

Tengo la versión Release 1.6 version experimental 1.6.0-16680 (release 3df0ac6fa), cuando se presentan errores de sintaxis, después de corregir el error y guardar, se muestra la ventana actual en blanco y se cierra la ventana actual.
Gracias y Saludos.

**Comment by ficristo** [comment] 2016-08-17 07:41
Can you reproduce the issue on latest version?

**Comment by ficristo** [comment] 2016-10-30 08:00
I close this since we didn't hear back from you.

**Closed by ficristo** 2016-10-30 08:00 UTC
Labels: Waiting for user
