### ISSUE TITLE
Directory is still being used, after you close the file in it.

### ISSUE THREAD

**Issue by whysqwhw** [adobe/brackets#11549] opened 2015-08-06 09:13 UTC
This scene is hard to describe:
1. open a file in a directory via context menu 'Open with Brackets ',
2. close the file,not close the Brackets.
3. move the directory.
you will find that the directory is still under using.

**Comment by MarcelGerber** [comment] 2015-08-06 17:11
Which OS are you on? For me on Windows, I can even move the file while it's still open in Brackets.

**Comment by whysqwhw** [comment] 2015-08-07 09:24
win7.
yes,but I said move the directory.

**Comment by MarcelGerber** [comment] 2015-08-07 11:32
Same thing when moving the directory.
Are you able to move it after closing Brackets (to make sure it's actually caused by Brackets, and not some other program)?

**Comment by whysqwhw** [comment] 2015-08-10 09:04
Have a try follow the describe,please.

**Comment by dragonship** [comment] 2017-05-26 12:01
Hi, is this still open or has been closed. Could you please attach the file that you are having trouble with, if still open?

**Closed** 2017-06-18 14:56 UTC
