### ISSUE TITLE
Dilato:LOC: JPN/FRA: Strings are localized inconsistent in About dialog

### ISSUE THREAD

**Issue by chunyan123** [adobe/brackets#12475] opened 2016-05-31 12:38 UTC
1. Launch Brackets.
2. Help-> About Brackets.
3. Observe all strings in About dialog.

Result:
String "Web Platform Docs... , CC-BY 3.0 Unported." and " Notice, ... reference herein." are localized in FRA, But they are un-localized in JPN.
Expected:
String "Web Platform Docs... , CC-BY 3.0 Unported." and " Notice, ... reference herein." should be localized/Uncalized in JPN and FRA.
![jpn](https://cloud.githubusercontent.com/assets/19649461/15674483/93c1fbee-276f-11e6-924e-cf7b25740636.png)

**Comment by Zhanxin** [comment] 2016-05-31 15:08
Checked this issue also reproduce on release 1.3 build.

**Comment by ficristo** [comment] 2016-11-08 19:25
French seems translated to me.
The japanese is a dupe of #12264

**Closed by ficristo** 2016-11-08 19:25 UTC
Labels: French, IQE, Japanese
