### ISSUE TITLE
Wrong operation on using Ctrl+Tab after closing files

### ISSUE THREAD

**Issue by mbsmt** [adobe/brackets#12553] opened 2016-06-28 07:35 UTC
`Ctrl+Tab` is working normally when you are navigating between opened files. But if you close the current file, and use `Ctrl+Tab` on the next focused file to navigate to another one, the closed file will be re-opened and focus will be set on it. This is because of wrong priority in the recent files (You can see that by pressing and holding `Ctrl+Tab`. I think priority must be from opened files to closed files.

**Comment by arunikayadav42** [comment] 2018-06-02 06:18
Is this issue still open?I would love to contribute :)

**Comment by navch** [comment] 2018-06-02 14:37
Hi @mbsmt I think this as designed. Because it's not about navigating opened file. It's meant to be check recent file opened. Closing this bug for now. Feel free to reopen if you have any concern.

Thanks @arunikayadav42 for your interest in contributing. If you are looking some bugs to start then You could look into some bugs marked with starter label.

**Closed by navch** 2018-06-02 14:37 UTC
