### ISSUE TITLE
Translation Issues with Brackets Release 1.8 Build 1.8.0-17108

### ISSUE THREAD

**Issue by iam-phild** [adobe/brackets#12967] opened 2016-12-03 10:29 UTC
### The problem
Translation not working correctly.

### The problem explained
I just wanted to change the language from "system default" to "german" and it worked for the most part. Some parts aren't translated and stays in "french". It's a french MacBook so i guess the error comes from the system. I tried also to switch the language to english or any other but some parts always stays in french. 
When Brackets is "restarting" after changing the language you see in the mac menu bar that the menu "window" (in my case "fenêtre") always stays and never change the language. Same goes for the main menu. It's not a big deal but would be nice if everything would be in one language.

![03](https://cloud.githubusercontent.com/assets/23381199/20858685/2626d0fa-b94b-11e6-8c79-f8b599883198.jpg)
![02](https://cloud.githubusercontent.com/assets/23381199/20858684/2438ede6-b94b-11e6-8f9f-ece674d2522c.jpg)
![04](https://cloud.githubusercontent.com/assets/23381199/20858686/27ee0962-b94b-11e6-933b-76c737af10ad.jpg)
![01](https://cloud.githubusercontent.com/assets/23381199/20858683/212f3164-b94b-11e6-8ed3-6d5151a45c1c.jpg)

### Versions
Macbook Pro Retina, 13', macOS Sierra: Version 10.12.1
Brackets Version: Release 1.8 Build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4)

**Comment by iam-phild** [comment] 2016-12-03 12:09
Ok i think i found the issue.

I went inside of the app and watched for the languages and so on. I found in the folder "Resources" three languages folders. English, French and Japanese. 
So i deleted the "French" one and the issue fro above noticed disappeared. 
Now it's still not completely fixed because instead of the german word "Fenster" i have the english word "window" which is normal i suppose because the "German.Iproj" is missing. See attached screenshots for more details.

<img width="670" alt="01" src="https://cloud.githubusercontent.com/assets/23381199/20859259/c1adc444-b959-11e6-8b0a-f99c40ec35c6.png">
<img width="573" alt="02" src="https://cloud.githubusercontent.com/assets/23381199/20859260/c56897f8-b959-11e6-86b6-75fc6fe45939.png">

**Comment by ficristo** [comment] 2016-12-03 15:48
Dupe of https://github.com/adobe/brackets/issues/10659
As you found the Brackets and Window menus are translated only in English, French and Japanese.
The *.lproj are coming from https://github.com/adobe/brackets-shell/tree/3f77cd77e57b7725bbfaeb371167adfd4c9333d3/appshell/mac

**Closed by ficristo** 2016-12-03 15:48 UTC
