### ISSUE TITLE
[Linux] Brackets depends on nonexistent libgcrypt11

### ISSUE THREAD

**Issue by thany** [adobe/brackets#13078] opened 2017-02-03 22:57 UTC
I can't install Brackets on Mint Cinnamon 18.1, because it depends on `libgcrypt11` which doesn't exist.

Yes, I've seen the discussion. The issue appears to be brushed off, since it has existed for some **2.5 years!!**

Here's a suggestion: *include* a suitable libgcrypt if you can't update to libgcrypt20. Include it in the deb package, so there won't be an impossible dependency. This will most likely make Brackets run again for every self-respecting (i.e. up-to-date) user who uses a Debian-based distro.

**Comment by zaggino** [comment] 2017-02-03 23:42
There's a point in the README about this: https://github.com/adobe/brackets#download
Also, you're welcome to open a PR with the fix that you've suggested. Right now Brackets don't have anyone who would maintain Linux builds.

**Comment by thany** [comment] 2017-02-04 02:59
I'm not that kind of programmer.

The fact of the matter is that this issue has existed for 2.5 years. So it magically survived several Brackets releases, and at least four Ubuntu releases. For shame!

The whole idea of deb packages is so that dependencies can be handled automatically and painlessly. By requiring a nonexisting dependency, you're defeating the whole purpose of the package system. Please, *just* include libgcrypt11 in the deb package if you must absolutely use it. Requiring users to manually fiddle with third-party packages is a no-go.

**Comment by zaggino** [comment] 2017-02-04 03:21
As I mentioned above, right now there's no-one to do this kind of work. Linux shell is basically not-maintained at all. It's a shame, I can agree with you on that.

**Comment by thany** [comment] 2017-02-04 03:25
It's not because Brackets is backed by Adobe, is it? Because I think we all know Adobe hates Linux...

Maybe I'll try Brackets-Electron then. As it stands now, that one is just as well supported as the official Brackets on Linux.

**Comment by petetnt** [comment] 2017-02-04 22:33
@thany It doesn't have anything to do with Adobe, more that the Brackets project has been unable to find a contributor that would have the required skill set of the difficult task of keeping up with complexity of Linux version of CEF. The C++ coders on Linux using Brackets is understandably small subset of users.

@ficristo has done superb job trying to get the Linux version up-to-date but there's so much to do. Brackets-Electron successfully removes the step of native coding, making it much easier to keep up with the changes.

That said, any Linux knowledgeable programmers are more than welcome to join the project, or to help @zaggino to ensure that Brackets-Electron would be at feature parity with the CEF version. In the long run I except Brackets to move to Electron based builds all together, but its time might not be right now.

Closing as a duplicate of #10255, workarounds and other suggestions can be found in https://github.com/adobe/brackets/wiki/Brackets-Linux-Guide.

Thanks! 👍

**Closed by petetnt** 2017-02-04 22:33 UTC
