### ISSUE TITLE
Brackets doesn't pick up on file modifications

### ISSUE THREAD

**Issue by joakimc** [adobe/brackets#13217] opened 2017-03-23 22:53 UTC
### Description

When checking out an earlier commit with GIT, Brackets doesn't pick up on the  file changes. Even if I close the file and open it again the file changes don't get picked up. I have to restart Brackets to see the changes. Still happens when reloading without extensions.

### Steps to Reproduce

1. Check out some GIT commit
2. Witness changes not picked up by Brackets
3. Close file in Brackets and open it again
4. Still no changes in Brackets

**Expected behavior:** Changes should be picked up

**Actual behavior:** Changes don't get picked up

### Versions

OS X El Capitan 10.11.6
Brackets Release 1.8 build 1.8.0-17108 (alf_localization_release_1.8 3af64fae4)

**Comment by joakimc** [comment] 2017-03-28 14:12
I think I found out what's causing this. I believe it's related to path names with parenthesises in them.

I use Dropbox for syncing, and had my project in `/Users/me/Dropbox (Teamname)/dev/project`. When moving my project outside Brackets started picking up file changes. Also, the side panel file structure started reflecting changes, which previously also was missing.

**Comment by ficristo** [comment] 2017-03-29 18:59
Closing as dupe of #12864

**Closed by ficristo** 2017-03-29 18:59 UTC
