### ISSUE TITLE
Language modes added via extensions don't update the extension-language map

### ISSUE THREAD

**Issue by bobrocke** [adobe/brackets#11252] opened 2015-06-11 19:31 UTC
In a conversion with @TomMalbran on Slack, he found that:

"Yes it seems that the internal map of extension to language does not get updated when a new language is added. Is just a problem because the language is added from an extension, which is loaded after the map is set. Is a bug that needs to be fixed in master. It even fails with the less language which is defined in a default extension."

**Comment by MarcelGerber** [comment] 2015-06-12 12:08
Repro steps, for easier understanding:
1. Create a new file "test.css"
2. In the language picker in the lower right, choose the "LESS" language
3. Open the picker again and click "Set as default for .css files"
4. Close and re-open Brackets

Result:
The language indicator says "CSS" again.

Expected:
The language indicator says "LESS".

Notice how LESS is not defined in the core, but rather in the `LESSSupport` extension.

**Comment by MarcelGerber** [comment] 2015-06-12 12:11
Looks like this is actually a dupe of #10177.

I'm inclined to close the other one, though, as this issue points out this also happens with the LESS language, and the repro steps are quite a lot easier.

**Comment by saurabh95** [comment] 2017-02-19 06:31
@MarcelGerber @zaggino  I am not able to repro the issue on the current master using the above repro steps, Could you verify it again?

**Comment by zaggino** [comment] 2017-02-20 00:46
We've merged some fixes around this so this might be fixed in master already as a side-effect, closing.
@MarcelGerber please re-open if you can still replicate.

**Closed by zaggino** 2017-02-20 00:46 UTC
Labels: medium priority
