### ISSUE TITLE
Ctrl-C (Copy) when nothing is selected empties the clipboard and replaces it with the current line

### ISSUE THREAD

**Issue by timothylrobb** [adobe/brackets#11211] opened 2015-06-04 15:38 UTC
I sometimes fat finger Ctrl-C when I'm trying to place the contents of my clipboard at the cursor location using Ctrl-V.  Unfortunately, when I do, Brackets replaces the contents of the clipboard with the current line of text.  For me, it would be beneficial to not copy anything to the clipboard when nothing is selected.  For me that would save time of having to undo, re-select text and paste.

If that feature is desired by some, perhaps consider making it optional in the brackets.json file.
Thanks.  I do love Brackets.

**Comment by redmunds** [comment] 2015-06-04 16:21
Duplicate of https://github.com/adobe/brackets/issues/9311. Closing.

**Closed by redmunds** 2015-06-04 16:21 UTC
