### ISSUE TITLE
Scaling Text and Menus to 4K (+)

### ISSUE THREAD

**Issue by danielhickman** [adobe/brackets#10407] opened 2015-01-18 09:34 UTC
The text and menus are fuzzy on my 4K monitor. My Sublime text editor is perfect scaling. I am running Windows 8.1 with ClearType and Text Scaling.

I can't tell if a screenshot would help but here is one:
![image](https://cloud.githubusercontent.com/assets/5341898/5791975/311d3202-9eb2-11e4-8b62-782bbbd27987.png)

**Comment by peterflynn** [comment] 2015-01-18 10:15
Closing as a duplicate of #10178

**Closed by peterflynn** 2015-01-18 10:15 UTC
