### ISSUE TITLE
Suggestion (Not on Trello): Make a browser inside of brackets

### ISSUE THREAD

**Issue by StephenSantilli9** [adobe/brackets#11183] opened 2015-05-30 21:51 UTC
Well, I want to suggest this, because it would be really cool.  Instead of needing to open your browser at all, you could just have one in brackets.

**Comment by sprintr** [comment] 2015-05-30 22:03
A duplicate of #10766

**Comment by StephenSantilli9** [comment] 2015-05-31 00:59
Oh, sorry, next time I'll look harder, when I searched I didn't see it.

**Comment by busykai** [comment] 2015-05-31 01:09
@StephenSantilli9 strictly speaking, #10766 talks about doing LivePreview within Brackets. If you want to view an arbitrary pages in Brackets, then I doubt it will ever be implemented since Brackets is the code editor, not a browser replacement. It's just a no-goal for us. It can be done via an extension, though, you could try it and see how popular it will become.

If you're interested in doing LivePreview in Brackets, then please upvote https://trello.com/c/YG0BBlrl . I'm going to close this issue for these reasons.

**Closed by busykai** 2015-05-31 01:09 UTC
