### ISSUE TITLE
Periodicly most keyboard shortcuts involving Ctrl failing

### ISSUE THREAD

**Issue by jedkcanderson** [adobe/brackets#10703] opened 2015-03-06 00:12 UTC
From time to time Brackets gets into a state where the only keyboard shortcut that works is Ctrl-- (reduce font size). All other commands fail if I use the keyboard shortcut but work if I use the mouse or Alt-[arrow keys] to the menu item.

I think this is similar to https://github.com/adobe/brackets/issues/9588 but maybe not the exact same issue.

I'm on Windows Vista, US keyboard, Brackets 1.2 build 1.2.0-15697.  I'm doing brackets extension hacking so I do open & close windows and the developer tools a lot.

Following the suggestions in Issue 9588 I found that sometimes, after reloading without extensions, the shortcuts are are back to normal again... but if I open a second window using Debug->New Brackets Window shortcuts in that window are broken.  Sometimes if I reload the 2nd window, it will fix the shortcuts, but when I go back to the original window the shortcuts will be broken again.  Sorry I don't have a deterministic recipe here (if I find one I will be back!).

I was unable to follow Peter's suggestion about adding a breakpoint because DocumentCommandHandlers.js is now just one big eval();  Is there a trick here to expand it I don't know?

I do see some warnings similar to the following in the Console.

 Deprecated: Do not use $().on/off() on Brackets modules and model objects. Call on()/off() directly on the object without a $() wrapper.
    at new jQuery.fn.init (/brackets.js:481:36)
    at n (file:///C:/Program%20Files%20(x86)/Brackets/www/thirdparty/thirdparty.min.js:559:405)

Let me know if you need more info!  I get into this state fairly often.

**Comment by jedkcanderson** [comment] 2015-03-06 15:17
Another quick note, when I get into this state, the gutter in my editors does not render.

![empty_gutter](https://cloud.githubusercontent.com/assets/3990696/6527592/89f8089e-c3e1-11e4-92a4-59cecb7481bf.png)

**Comment by DenisVuyka** [comment] 2015-03-06 17:18
I get this issue very often, all keyboard combinations that involve Ctrl just stop working, especially after calling "Debug/New Brackets Window". One of the windows randomly stop reacting. The only workaround I have so far is shutting down all Brackets instances and launching again.

**Comment by peterflynn** [comment] 2015-03-06 23:49
@jedkcanderson @DenisVuyka  If you're using _Debug > New Brackets Window_, then this is a duplicate of #8135.  I _strongly_ suggest avoiding the New Brackets Window command as it is intended for debugging only, and has many serious problems.

Also, @jedkcanderson: what are you expecting to see in that space in the gutter?  Your screenshot looks normal to me.

**Comment by jedkcanderson** [comment] 2015-03-07 00:10
@peterflynn Agreed, this looks like a duplicate.  Sorry about that, thought I had searched exhaustively.  From the your comments, and the comments in other bugs, the fix for this sounds involved.  Is that a fair assessment?  I ask because I have a team of developers who are starting to look at Brackets development and we're looking for ways we can help that are actively effecting us.

As for the gutter issue, here's a screenshot when the shortcuts are functioning.

![working_gutter](https://cloud.githubusercontent.com/assets/3990696/6538720/65cf1a30-c42b-11e4-818c-240b71647383.png)

**Comment by peterflynn** [comment] 2015-03-07 00:43
@jedkcanderson The gutter marker you're seeing looks like part of the Brackets Git extension.  Normally I'd suggest filing a bug over there, but I suspect use of the buggy New Window command may be breaking that extension too (due to sharing one copy of Node) -- not the extension's fault, really.

Fixing the keyboard shortcuts in particular (#8135) shouldn't be that hard -- for a dev with native Windows programming experience (since that's where the fix must lie).  Fixing _all_ the New Window command's problems is a much bigger undertaking, though.  If you're interested, I think a good first step would be to review the list of issues on the [multiple windows feature card](https://trello.com/c/YM0YySxX/679-multiple-separate-windows-official-new-window-command) and then start a thread on [brackets-dev](https://groups.google.com/forum/#!forum/brackets-dev) to discuss further.

**Closed** 2015-03-07 00:43 UTC
