### ISSUE TITLE
Cannot expand objects in Chrome DevTools

### ISSUE THREAD

**Issue by Wikunia** [adobe/brackets#10537] opened 2015-02-06 14:40 UTC
I cannot expand nested objects in the Chrome DevTools. 
My nested object:
`console.log({test:{test:123}});` 
It's possible to "expand" using the first arrow but the nested arrows doesn't work
![brackets-devtools](https://cloud.githubusercontent.com/assets/4931746/6080967/fa46bad2-ae15-11e4-9b86-20dc11252eb8.png)

Btw: It's possible when I use my code snippet directly inside the DevTools.

My machine:
ArchLinux
v3.18.5
Brackets:
newest version (1.2)
Google Chrome
Version 40.0.2214.95 (64-bit)

**Comment by JeffryBooher** [comment] 2015-02-06 17:40
@Wikunia does this happen in chrome's dev tools or just brackets?  I've seen this recently with node-inspector as well but eventually it starts working so I don't know if it's a problem with chrome 40 or older devtools packages.  I get frustrated and start double-triple clicking like crazy and it eventually expands.

**Comment by Wikunia** [comment] 2015-02-06 17:44
It's possible when I type the `console` code directly inside the DevTools in Chrome so I think the problem is somewhere between `Brackets` and `Chrome`

**Comment by peterflynn** [comment] 2015-02-06 19:51
@Wikunia I can't repro this either, whether I type the `console.log()` directly into the console manually, or add it to the Brackets source code.  Sometimes dev tools will give less info if the `console.log()` runs before dev tools are opened, but in this case I can't repro even if I leave dev tools closed initially.

Are you building brackets-shell yourself or using an official build?

**Comment by Wikunia** [comment] 2015-02-06 19:56
I am using this to get the newest version on brackets: 
https://github.com/adobe/brackets/wiki/How-to-Hack-on-Brackets
Neither official nor shell :) I've not using `console.log` directly inside brackets source code but inside my extensions.

**Comment by peterflynn** [comment] 2015-02-06 20:17
@Wikunia But the native shell you're running -- are you getting it by downloading an official brackets.io build, or are you checking out the separate brackets-shell repo and following https://github.com/adobe/brackets-shell/wiki/Building-Brackets-Shell ?

**Comment by Wikunia** [comment] 2015-02-06 20:30
I've downloaded an official brackets.io build.

**Comment by redmunds** [comment] 2015-02-06 21:37
This sounds like a duplicate of #10315. Since Linux is still on CEF 1519, then it only has dev tools via Chrome browser, so there's no workaround. I *think* there's a pending PR with CEF 2171 fro Linux that you could try.

**Comment by Wikunia** [comment] 2015-02-07 14:24
It looks like `CEF 2171` is already part of the brackets master branch, right?

**Comment by redmunds** [comment] 2015-02-07 16:45
@Wikunia Yes, but it's broken. Fixes are in PR https://github.com/adobe/brackets-shell/pull/499

**Comment by Wikunia** [comment] 2015-02-07 17:38
Don't have enough time to try something with `brackets-shell`. I hope it will be available here in some days/weeks.

**Comment by sprintr** [comment] 2015-02-07 17:53
There is a linux build available with [CEF 2171](https://github.com/adobe/brackets/releases/tag/linux-cef-2171) you may wanna try.

**Comment by Wikunia** [comment] 2015-02-07 18:11
I think that one is already merged to master, right? If that is the case I've tried it.

**Comment by peterflynn** [comment] 2015-02-09 00:29
@Wikunia No, it's not on master. But you can download a test build from https://github.com/adobe/brackets/releases/tag/linux-cef-2171.

Since this is a duplicate of #10315 though, I'll close this one and generalize the title there.

**Closed by peterflynn** 2015-02-09 00:29 UTC
