### ISSUE TITLE
 problem with the menu in ubuntu 17.10

### ISSUE THREAD

**Issue by paletGerardo** [adobe/brackets#13905] opened 2017-11-22 20:40 UTC
the bracket menu bar appears with symbols. this only happens with the latest version. I already try several methods but I can not solve it.

**Comment by nethip** [comment] 2017-11-23 05:05
@paletGerardo This is currently being worked upon. Sorry for the inconvenience! This is currently fixed and in under testing and we will be refreshing the builds with the fix in a few days time.

**Comment by ogerly** [comment] 2017-12-12 11:49
the problem is still there

**Comment by archandha** [comment] 2017-12-13 13:40
Probably this issue is a duplicate from #13738 (cf. https://github.com/adobe/brackets/issues/13738 )

This fixed it for me:
https://github.com/adobe/brackets/issues/13738#issuecomment-342639039

**Comment by paletGerardo** [comment] 2017-12-13 16:13
Hola! cambie el sistema op por kde neo, y aca si funciona perfecto.

2017-12-12 8:49 GMT-03:00 Alexander Friedland <notifications@github.com>:

**Comment by nethip** [comment] 2017-12-21 08:45
This is fixed now. We have refreshed the builds of 1.11 release. Please re-download the installers from http://brackets.io

**Closed by nethip** 2017-12-21 08:45 UTC
Labels: Linux only
