### ISSUE TITLE
Extension Manager not fully visible

### ISSUE THREAD

**Issue by GameplayJDK** [adobe/brackets#10743] opened 2015-03-14 13:54 UTC
I've docked the brackets window to the right side of my screen, but as I tried to open the extension manager it wasn't fully visible:

![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/6651897/9d6569e8-ca59-11e4-87c3-268960a98f50.png)

**Comment by petetnt** [comment] 2015-03-15 13:04
Duplicate of #10728

**Comment by prksingh** [comment] 2015-03-16 06:27
Closing as it looks like a duplicate. Please reopen if your problem is different

**Closed by prksingh** 2015-03-16 06:27 UTC
