### ISSUE TITLE
Brackets window does not close on Linux

### ISSUE THREAD

**Issue by minhazul-haque** [adobe/brackets#10408] opened 2015-01-18 10:16 UTC
Clicking on close (x) should terminate the program and close the Bracket window, but it does not.

When I select "Restart Node" from "Debug" menu, and click the close button, it works as expected. Tried both in normal mode and no extension mode.

OS: Kubutnu x64
Version: 1.1 experimental build 1.1.0-15558 (release ea908cae5)

The following line appears when the program is launched for the first time.

```ATTENTION: default value of option force_s3tc_enable overridden by environment.
[0118/161230:ERROR:sandbox_linux.cc(130)] InitializeSandbox() called with multiple threads in process gpu-process```

I have been using Brackets since release 1.0, and this problem was still there.

**Comment by peterflynn** [comment] 2015-01-18 10:33
@minhazul-haque Does it close if you click the "X" twice?  If so, this is a duplicate of #4611.

**Comment by minhazul-haque** [comment] 2015-01-18 12:10
@peterflynn It does.

**Comment by peterflynn** [comment] 2015-01-18 12:17
@minhazul-haque Ok, thanks for the quick response!  Closing as a duplicate then.  From the latest comments in #4611 it sounds like someone may already be working on a fix...

**Closed by peterflynn** 2015-01-18 12:17 UTC
Labels: Linux only
