### ISSUE TITLE
Autocomplete doesn't work after using spread operator

### ISSUE THREAD

**Issue by EkaterinaMironova** [adobe/brackets#12666] opened 2016-08-11 07:00 UTC
If I use [spread operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_operator) in variable declaration, Autocomplete doesn't work.

For example:
`let model = new Model(...args);`

In function declaration it's ok.
`function createModel(Model, ...args) {};`

What's wrong? Thanks a lot!

Brackets version - sprint 7 build 1.7.0-16898 (release b0a363b71), russian language
OS version - Windows 10 build 10586

**Comment by dblachut** [comment] 2016-08-23 16:17
I can confirm this issue, please fix asap. :+1:

**Comment by dblachut** [comment] 2016-08-23 23:23
Looks like tern does not have support for "SpreadElement". After adding stub implementation in https://github.com/ternjs/tern/blob/a53d2ee43d091a44fb4291779a786ed3fc010ba3/lib/infer.js#L1373 it works.

I will try to investigate it further, or event fix it, tomorrow. Unless someone will do it first(?). :)

**Comment by ficristo** [comment] 2016-08-24 07:47
Could you try this PR https://github.com/adobe/brackets/pull/11569 to see if it fixes this issue?

**Comment by dblachut** [comment] 2016-08-24 08:28
Looks like it did, at least for me. I can use it as a temporary solution. Thanks.

**Comment by EkaterinaMironova** [comment] 2016-08-24 12:45
Cool! It works! Thanks a lot =)

**Comment by MarcelGerber** [comment] 2016-08-26 13:37
This is fixed with the merge of #11569 and will come to you in Release 1.8.
Please let us know if it still doesn't work for you when the Release ships.

**Closed by MarcelGerber** 2016-08-26 13:37 UTC
Labels: F Code Hints
