### ISSUE TITLE
Cannot call method 'enableDebugger' of undefined

### ISSUE THREAD

**Issue by TheBenji** [adobe/brackets#10688] opened 2015-03-04 10:05 UTC
Since version 1.2 I get an JS alert error if I click on "Debug->Enable Node Debugger" that says:
"Failed trying to enable Node Debugger: Cannot call method 'enableDebugger' of undefined".

Find more here: https://github.com/TheBenji/brackets-node-debugger/issues/13

**Comment by peterflynn** [comment] 2015-03-04 10:33
This is a duplicate of #9131.  It only happens if the user has clicked _Debug > Restart Node_ one or more times quickly... which in this case sounds like confusion on the part of your extension's users.  I'd recommend moving your extension's menu items to a different menu -- we may hide the Debug menu by default in future versions of Brackets (to avoid exactly this sort of confusion).

**Closed** 2015-03-04 10:33 UTC

**Comment by TheBenji** [comment] 2015-03-04 10:55
Actually it happened to me right after I started Brackets - didn't restart node at all...

**Comment by peterflynn** [comment] 2015-03-04 22:21
If you do it very soon after launching Brackets, you could hit the same problem too -- in either case, the issue is that Node is not done (re)starting at the time when you click the menu item.
