### ISSUE TITLE
Whitescreen issue

### ISSUE THREAD

**Issue by gfcnani** [adobe/brackets#12869] opened 2016-11-02 08:43 UTC
I'm getting whitescreen suddenly while using brackets. I tried clear cache folder, uninstall and reinstall and tried different version but the issue is still coming. I'm using windows 10 and brackets version is 1.7

**Comment by petetnt** [comment] 2016-11-02 08:44
Possible duplicate of #12617

**Comment by ficristo** [comment] 2016-11-06 11:39
I close as a dupe of #12617 for now.

**Closed by ficristo** 2016-11-06 11:39 UTC
