### ISSUE TITLE
Popup boxes are off center

### ISSUE THREAD

**Issue by CPCookieMan** [adobe/brackets#10977] opened 2015-04-23 02:20 UTC
This is driving me up a wall. It looks terrible. Something changed between 1.1 and 1.2 that made popup boxes go all wonky. It makes brackets-git look really weird as well, as the popup boxes got smaller for some reason, and the titles for popup boxes go on to two lines.
![centering](https://cloud.githubusercontent.com/assets/1424353/7289410/b1c981e6-e93d-11e4-9b52-9caed3cd17af.PNG)
Upon further review, it's still happening to me all the way back to 1.0. I'm almost sure this wasn't always the case. What could cause that?
And on yet more review, it would seem that .modal-wrapper is on a position:absolute system. It has left:0 and right:0 set, with margins of auto. Theoretically, that should center it, but for some reason, 0 is actually 360px out into the editor (which as far as I can tell, doesn't correlate with anything. It's not like the size of the sidebar or anything.) This can be solved by setting left:-360px, but that seems pretty hacky. Any ideas?
![centering2](https://cloud.githubusercontent.com/assets/1424353/7289738/467fec2c-e942-11e4-9c87-4826a176f01a.PNG)

**Comment by CPCookieMan** [comment] 2015-04-23 03:54
I've submitted a pull request which has fixed the problem. Request #10978.

**Comment by nethip** [comment] 2015-04-30 09:10
@CPCookieMan This problem got introduced because of a change in our Extract for Brackets plugin. Basically the plugin was overriding some CSS styles. Could you try this with our latest build. This must not be there.

**Comment by ficristo** [comment] 2016-08-21 07:30
Closing as was an Extract bug.
If you can still reproduce on latest release please open a new issue.

**Closed by ficristo** 2016-08-21 07:30 UTC
