### ISSUE TITLE
Second click to close Brackets under Linux

### ISSUE THREAD

**Issue by loup-brun** [adobe/brackets#11886] opened 2015-11-01 23:07 UTC
When attempting to close a Brackets window under Linux Mint 17.2, a second click is required on the "x" close button (it doesn't with any other application).

This issue was present in release 1.3, as well as in 1.4 and still is in 1.5.

**Comment by abose** [comment] 2015-11-02 09:14
Duplicate of https://github.com/adobe/brackets/issues/4611
Closing.

**Closed by abose** 2015-11-02 09:14 UTC
