### ISSUE TITLE
"Live Preview was cancelled ..." pop-up (balloon) leaves an unclickable area after it disappears

### ISSUE THREAD

**Issue by Ripley6811** [adobe/brackets#10309] opened 2015-01-05 04:57 UTC
Steps to trigger the problem:
1. Open browser using the lightning bolt button.
2. Close browser (and see the "Live Preview was cancelled..." message next to button)
3. Try to click in the area where the message was.

The text-entry mouse-pointer turns into an arrow pointer when hovering over that area. Expected to be able to click that side area to move cursor to the end of the second line of text.

Brackets version:
Release 1.1 build 1.1.0-15558 (release ea908cae5) 
build timestamp: Thu Dec 18 2014 10:23:10 GMT-0800

OS version:
Windows 8
Tried reloading without extensions and it still occurs.

**Comment by ElegantScripting** [comment] 2015-01-10 16:32
He's not kidding, I have this problem on both my Mac and Windows computer.

**Comment by MarcelGerber** [comment] 2015-01-10 19:26
@sebaslv @busykai `git bisect` points to https://github.com/adobe/brackets/commit/235c551.
Notice though that this happens with `livedev.multibrowser: false`, too.

**Comment by busykai** [comment] 2015-01-11 20:21
Thanks for the info, @MarcelGerber! It helps!

**Comment by peterflynn** [comment] 2015-01-27 23:46
Reviewed - marking medium since this is a regression.

**Comment by MarcelGerber** [comment] 2015-02-14 19:57
This was fixed in eef9c68a1fdff372b9ea6352cacb5e2506e55be9.

**Comment by MarcelGerber** [comment] 2015-06-03 21:16
Closing as fixed. (see above)

**Closed by MarcelGerber** 2015-06-03 21:16 UTC
Labels: F Live Preview, F Live Preview MultiBrowser, medium priority
