### ISSUE TITLE
Core: One file could be opened twice on Brackets

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets#13144] opened 2017-03-03 09:17 UTC
Steps:
1. Launch the Brackets
2. Click View->Vertical Split
3. Open one file to the left panel
4. Open other files and move to right panel
5. Open the file again to the right panel

Result: The file could be opened again, and modify on left panel, the change also could see on right panel
Expect: The file only could be open in one panel
![onefileopentwice](https://cloud.githubusercontent.com/assets/2245179/23545143/1ea8c4ba-0035-11e7-9d56-1143debe9d86.gif)

**Comment by zaggino** [comment] 2017-03-03 09:34
@Zhanxin this is actually a feature, not a bug :-) When having a very long file, you can have the top of the file on left and bottom on right for example.

**Comment by petetnt** [comment] 2017-03-03 15:35
Closing as a feature :)

**Closed by petetnt** 2017-03-03 15:35 UTC
Labels: IQE
